/**
 *
 * $Id$
 */
package org.bonitasoft.studio.identity.organization.model.organization.validation;


/**
 * A sample validator interface for {@link org.bonitasoft.studio.organization.model.organization.ContactData}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContactDataValidator {
    boolean validate();

    boolean validateEmail(String value);
    boolean validatePhoneNumber(String value);
    boolean validateMobileNumber(String value);
    boolean validateFaxNumber(String value);
    boolean validateBuilding(String value);
    boolean validateRoom(String value);
    boolean validateAddress(String value);
    boolean validateZipCode(String value);
    boolean validateCity(String value);
    boolean validateState(String value);
    boolean validateCountry(String value);
    boolean validateWebsite(String value);
}
