/**
 *
 * $Id$
 */
package org.bonitasoft.studio.identity.organization.model.organization.validation;

import org.bonitasoft.studio.identity.organization.model.organization.Membership;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.bonitasoft.studio.organization.model.organization.Memberships}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MembershipsValidator {
    boolean validate();

    boolean validateMembership(EList<Membership> value);
}
