/**
 *
 * $Id$
 */
package org.bonitasoft.studio.identity.organization.model.organization.validation;

import org.bonitasoft.studio.identity.organization.model.organization.CustomUserInfoDefinitions;
import org.bonitasoft.studio.identity.organization.model.organization.Groups;
import org.bonitasoft.studio.identity.organization.model.organization.Memberships;
import org.bonitasoft.studio.identity.organization.model.organization.Roles;
import org.bonitasoft.studio.identity.organization.model.organization.Users;

/**
 * A sample validator interface for {@link org.bonitasoft.studio.organization.model.organization.Organization}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OrganizationValidator {
    boolean validate();

    boolean validateCustomUserInfoDefinitions(CustomUserInfoDefinitions value);
    boolean validateUsers(Users value);
    boolean validateRoles(Roles value);
    boolean validateGroups(Groups value);
    boolean validateMemberships(Memberships value);
    boolean validateName(String value);
    boolean validateDescription(String value);
    boolean validateModelVersion(String value);
}
