/**
 *
 * $Id$
 */
package org.bonitasoft.studio.identity.organization.model.organization.validation;

import org.bonitasoft.studio.identity.organization.model.organization.ContactData;
import org.bonitasoft.studio.identity.organization.model.organization.CustomUserInfoValuesType;
import org.bonitasoft.studio.identity.organization.model.organization.MetaDatasType;
import org.bonitasoft.studio.identity.organization.model.organization.PasswordType;

/**
 * A sample validator interface for {@link org.bonitasoft.studio.organization.model.organization.User}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UserValidator {
    boolean validate();

    boolean validateFirstName(String value);
    boolean validateLastName(String value);
    boolean validateIconName(String value);
    boolean validateIconPath(String value);
    boolean validateTitle(String value);
    boolean validateJobTitle(String value);
    boolean validateManager(String value);
    boolean validatePersonalData(ContactData value);
    boolean validateProfessionalData(ContactData value);
    boolean validateMetaDatas(MetaDatasType value);
    boolean validateUserName(String value);
    boolean validateEnabled(boolean value);
    boolean validatePassword(PasswordType value);
    boolean validateCustomUserInfoValues(CustomUserInfoValuesType value);
}
