<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.bonitasoft.org/studio/bdm" nsPrefix="businessDataModel">
  <eClassifiers xsi:type="ecore:EClass" name="BusinessObjectModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessObjects" upperBound="-1"
        eType="#//BusinessObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simpleName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uniqueConstraints" upperBound="-1"
        eType="#//UniqueConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
        eType="#//Index" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queries" upperBound="-1"
        eType="#//Query" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultQueries" upperBound="-1"
        eType="#//Query" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldNames" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryParameters" upperBound="-1"
        eType="#//QueryParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleField" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//FieldType"
        defaultValueLiteral="STRING"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationField" eSuperTypes="#//Field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//BusinessObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//RelationType"
        defaultValueLiteral="AGGREGATION"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fetchType" eType="#//FetchType"
        defaultValueLiteral="LAZY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FieldType">
    <eLiterals name="STRING"/>
    <eLiterals name="TEXT" value="1" literal="TEXT"/>
    <eLiterals name="INTEGER" value="2" literal="INTEGER"/>
    <eLiterals name="DOUBLE" value="3"/>
    <eLiterals name="LONG" value="4"/>
    <eLiterals name="FLOAT" value="5"/>
    <eLiterals name="DATE" value="6"/>
    <eLiterals name="BOOLEAN" value="7"/>
    <eLiterals name="BYTE" value="8"/>
    <eLiterals name="SHORT" value="9"/>
    <eLiterals name="CHAR" value="10"/>
    <eLiterals name="LOCALDATETIME" value="11"/>
    <eLiterals name="LOCALDATE" value="12"/>
    <eLiterals name="OFFSETDATETIME" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationType">
    <eLiterals name="AGGREGATION"/>
    <eLiterals name="COMPOSITION" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FetchType">
    <eLiterals name="EAGER"/>
    <eLiterals name="LAZY" value="1"/>
  </eClassifiers>
</ecore:EPackage>
