/*
* generated by Xtext
*/
package org.bonitasoft.studio.condition.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class ConditionModelDescriptionLabelProvider extends DefaultDescriptionLabelProvider {

	public String text(IEObjectDescription ele) {
	  return "my "+ele.getName();
	}
	 
 /*   public String image(IEObjectDescription ele) {
      return ele.getEClass().getName() + ".gif";
    }	 */


}
