/*
* generated by Xtext
*/
package org.bonitasoft.studio.condition.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ConditionModelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
