/*
* generated by Xtext
*/
package org.bonitasoft.studio.condition.ui.contentassist;

import org.bonitasoft.studio.condition.ui.contentassist.AbstractConditionModelProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ConditionModelProposalProvider extends AbstractConditionModelProposalProvider {

}
