/*
* generated by Xtext
*/
package org.bonitasoft.studio.condition.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractConditionModelJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.bonitasoft.studio.condition.conditionModel.ConditionModelPackage.eINSTANCE);
		return result;
	}

}
