= Eclipse target platform

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Purpose of the target platform

From https://www.vogella.com/tutorials/EclipseTargetPlatform/article.html[Lars Vogel's Eclipse Target Platform article]

The set of plug-ins available for your application development is defined by the plug-ins in your workspace in addition to the plug-ins defined by your target platform. For example, the SWT and JFace plug-ins are typically provided by your target platform. By default, the plug-in installed in your Eclipse IDE installation are used as target platform.

It is good practice to develop and build against a explicit target definition which is stored in a configuration file. This way the plug-in dependencies and the used versions are controlled and specified during the development. A target definition file is typically shared between the developers to ensure that everyone is using the same basis for development. If such a target definition file does not exists, than every developer develops against his version of the Eclipse IDE, which can lead to incompatible changes.

You can activate and switch the target platform in the Eclipse Preferences. Select Window  Preferences  Plug-in Development  Target Platform. It is also possible to active a target platform via its editor via the Set as Active Target Platform link on the first page.

== Updating the target platform

The Tycho build uses the `platform.target` file. However, in addition, we use a `remote_platform.target` that keeps the reference to the actual p2 update sites. In order to ensure reliability of our builds, we mirror the required content of those update sites and publish it to `https://update-site.bonitasoft.com/p2/<eclipse_version>/`.

During the development phase, you can update the `remote_platform.target` and the `platform.target` to be in sync and pointing to the actual p2 update sites. The mirror is build and published before the RC version.

When possible, do not explicitly set the plugins/features version. It eases the update process. Often eclipse update sites are already versioned (eg: __https://download.eclipse.org/releases/2022-06__, __https://download.eclipse.org/technology/swtbot/releases/4.0.0/__...).

== Validating the target platform

You may use the `target-platform-validation-plugin` to validate the target platform:

[source, shell]
----
./mvnw -f platform/pom.xml validate -Pvalidate
----

== Build the mirror

Once ready and stable for the release, the target platform can be mirrored using the following Maven commands:

[source, shell]
----
./mvnw -f platform/pom.xml groovy:execute@configure-mirror-plugin
----
This execution will update the configuration of the `tycho-p2-extras-plugin` to synch the `mirror` goal with the content of the `remote_platform.target`

[source, shell]
----
./mvnw -f platform/pom.xml package -Pmirror-tp
----
Runs the `mirror` goal. This can take a while as it downloads all the required plugins and features.

The result can be found as an archive in `platform/target/studio-target-platform-<version>.zip`.

== Use the mirror

Update the `target.platform` to use the mirror.

[source, shell]
----
./mvnw -f platform/pom.xml groovy:execute@generate-mirror-tp -Dmirror.target.filename=platform.target -Dmirror.location=https://update-site.bonitasoft.com/p2/<eclipse_version>/
----
Updates the `platform.target` to point to the mirror location.

NOTE: Do not set `-Dmirror.location` to use the locally generated mirror (in `platform/target/repository`)
