<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process">
  <process:MainProcess xmi:id="_OLSUUHIhEd-LorYRZnxm3A" name="BPMN_Showcase" label="BPMN_Showcase" bonitaVersion="5.2" bonitaModelVersion="5.2">
    <elements xmi:type="process:Pool" xmi:id="_Ob-bsHIhEd-LorYRZnxm3A" name="process1" label="process1" byPassFormsGeneration="true">
      <elements xmi:type="process:Task" xmi:id="_OcQIgHIhEd-LorYRZnxm3A" name="Request" label="Request" outgoing="_cT8REHIhEd-LorYRZnxm3A" incoming="_OcziIHIhEd-LorYRZnxm3A" groups="_OcpKEHIhEd-LorYRZnxm3A">
        <form xmi:type="form:Form" xmi:id="_qel8cHIiEd-LorYRZnxm3A" name="Request" label="Request" nLine="3" pageLabel="Request">
          <widgets xmi:type="form:TextFormField" xmi:id="_qel8cXIiEd-LorYRZnxm3A" name="listAsString" label="listAsString" displayLabel="listAsString">
            <script xmi:type="form:GroovyScript" xmi:id="_qel8cnIiEd-LorYRZnxm3A" inputScript="${listAsString}" setVar="_Uh4C8HIhEd-LorYRZnxm3A"/>
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_qel8c3IiEd-LorYRZnxm3A"/>
          </widgets>
          <widgets xmi:type="form:SubmitFormButton" xmi:id="_qel8dHIiEd-LorYRZnxm3A" name="Submit" label="Submit" displayLabel="Submit">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_qel8dXIiEd-LorYRZnxm3A" line="2"/>
          </widgets>
        </form>
      </elements>
      <elements xmi:type="process:StartEvent" xmi:id="_OccVwHIhEd-LorYRZnxm3A" name="Start1" label="Start1" outgoing="_OcziIHIhEd-LorYRZnxm3A"/>
      <elements xmi:type="process:Task" xmi:id="_dX6PgHIhEd-LorYRZnxm3A" name="Loop" label="Loop" outgoing="_iZqSIHIhEd-LorYRZnxm3A _rhBfQHIhEd-LorYRZnxm3A" incoming="_cT8REHIhEd-LorYRZnxm3A" isLoop="true" loopCondition="counter==0" user="" groups="_OcpKEHIhEd-LorYRZnxm3A">
        <form xmi:type="form:Form" xmi:id="_tYI8cHIiEd-LorYRZnxm3A" name="Loop" label="Loop" nLine="3" pageLabel="Loop">
          <widgets xmi:type="form:TextFormField" xmi:id="_tYI8cXIiEd-LorYRZnxm3A" name="counter" label="counter" displayLabel="counter">
            <script xmi:type="form:GroovyScript" xmi:id="_tYI8cnIiEd-LorYRZnxm3A" inputScript="${counter}" setVar="_TPcxwHIhEd-LorYRZnxm3A"/>
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_tYI8c3IiEd-LorYRZnxm3A"/>
          </widgets>
          <widgets xmi:type="form:SubmitFormButton" xmi:id="_tYI8dHIiEd-LorYRZnxm3A" name="Submit" label="Submit" displayLabel="Submit">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_tYI8dXIiEd-LorYRZnxm3A" line="2"/>
          </widgets>
          <widgets xmi:type="form:Table" xmi:id="_wb4aQHIiEd-LorYRZnxm3A" name="Table1" label="Table1" displayLabel="List">
            <script xmi:type="form:GroovyScript" xmi:id="_x8JTIHIiEd-LorYRZnxm3A" inputScript="${list}"/>
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_wcFOkHIiEd-LorYRZnxm3A" line="1"/>
          </widgets>
        </form>
      </elements>
      <elements xmi:type="process:ScriptTask" xmi:id="_k2jyYHIhEd-LorYRZnxm3A" name="Script_Task" label="Script Task" outgoing="_2FqisHIhEd-LorYRZnxm3A" incoming="_iZqSIHIhEd-LorYRZnxm3A">
        <connectors xmi:type="process:Connector" xmi:id="_qYnFsHIhEd-LorYRZnxm3A" name="set_text_to_script" label="set text to script" connectorId="GroovyConnector" event="automaticOnEnter">
          <parameters xmi:type="process:Parameter" xmi:id="_qYnswHIhEd-LorYRZnxm3A" key="setScript" value="ACED00057400082273637269707422"/>
          <outputs xmi:type="process:OutputParameterMapping" xmi:id="_qYnswXIhEd-LorYRZnxm3A" valueExpression="result" targetData="_TxlOcHIhEd-LorYRZnxm3A"/>
        </connectors>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_tF8OoHIhEd-LorYRZnxm3A" name="Service_Task" label="Service Task" outgoing="_2ggroHIhEd-LorYRZnxm3A" incoming="_rhBfQHIhEd-LorYRZnxm3A">
        <connectors xmi:type="process:Connector" xmi:id="_wr620HIhEd-LorYRZnxm3A" name="set_text_to_service" label="set text to service" connectorId="SetVariable" event="automaticOnEnter">
          <parameters xmi:type="process:Parameter" xmi:id="_wr620XIhEd-LorYRZnxm3A" key="setVariableName" value="ACED000574000474657874"/>
          <parameters xmi:type="process:Parameter" xmi:id="_wr620nIhEd-LorYRZnxm3A" key="setValue" value="ACED000574000773657276696365"/>
        </connectors>
      </elements>
      <elements xmi:type="process:ANDGateway" xmi:id="_2FdHUHIhEd-LorYRZnxm3A" name="Gate1" label="Gate1" outgoing="_4Q5EIHIhEd-LorYRZnxm3A" incoming="_2FqisHIhEd-LorYRZnxm3A _2ggroHIhEd-LorYRZnxm3A"/>
      <elements xmi:type="process:Task" xmi:id="_6V3zoHIhEd-LorYRZnxm3A" name="Get_Results" label="Get Results" outgoing="_9Ir5gHIhEd-LorYRZnxm3A" incoming="_4Q5EIHIhEd-LorYRZnxm3A" user="" groups="_OcpKEHIhEd-LorYRZnxm3A"/>
      <elements xmi:type="process:ThrowLinkEvent" xmi:id="_9IeeIHIhEd-LorYRZnxm3A" name="line1" label="line1" incoming="_9Ir5gHIhEd-LorYRZnxm3A" to="__dtQIHIhEd-LorYRZnxm3A"/>
      <elements xmi:type="process:CatchLinkEvent" xmi:id="__dtQIHIhEd-LorYRZnxm3A" name="line2" label="line2" outgoing="_DDvisHIiEd-LorYRZnxm3A" from="_9IeeIHIhEd-LorYRZnxm3A"/>
      <elements xmi:type="process:EndMessageEvent" xmi:id="_DDiHUHIiEd-LorYRZnxm3A" name="Send_message_to_process2" label="Send message to process2" incoming="_DDvisHIiEd-LorYRZnxm3A">
        <events xmi:type="process:EventObject" xmi:id="_LGIr0HIiEd-LorYRZnxm3A" name="message" label="message" throwEvent="automaticOnEnter" targetProcessName="process2" targetElementName="Receive_message_from_process1">
          <data xmi:type="process:Data" xmi:id="_O5iE8HIiEd-LorYRZnxm3A" name="sentVariable" label="sentVariable" dataType="_OLSUU3IhEd-LorYRZnxm3A" defaultValue="${counter}"/>
        </events>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_owNvEHIiEd-LorYRZnxm3A" path="black/application/css">
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvEXIiEd-LorYRZnxm3A" path="/bonita_form_default.css"/>
      </resourceFolders>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_owNvEnIiEd-LorYRZnxm3A" path="black/application/images">
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvE3IiEd-LorYRZnxm3A" path="/avatar-default.gif"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvFHIiEd-LorYRZnxm3A" path="/background.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvFXIiEd-LorYRZnxm3A" path="/bloc-identification.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvFnIiEd-LorYRZnxm3A" path="/bonita-open-solution-logo.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvF3IiEd-LorYRZnxm3A" path="/button.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvGHIiEd-LorYRZnxm3A" path="/object-area-bottom.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvGXIiEd-LorYRZnxm3A" path="/object-area-middle.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvGnIiEd-LorYRZnxm3A" path="/object-area-top.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvG3IiEd-LorYRZnxm3A" path="/principal-container-bottom.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvHHIiEd-LorYRZnxm3A" path="/principal-container-middle.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvHXIiEd-LorYRZnxm3A" path="/principal-container-top.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvHnIiEd-LorYRZnxm3A" path="/principal-container.png"/>
        <resourceFiles xmi:type="process:ResourceFile" xmi:id="_owNvH3IiEd-LorYRZnxm3A" path="/sprite.png"/>
      </resourceFolders>
      <data xmi:type="process:Data" xmi:id="_TPcxwHIhEd-LorYRZnxm3A" name="counter" label="counter" dataType="_OLSUU3IhEd-LorYRZnxm3A" defaultValue="0"/>
      <data xmi:type="process:JavaObjectData" xmi:id="_VtwnQHIhEd-LorYRZnxm3A" name="list" label="list" dataType="_OLSUV3IhEd-LorYRZnxm3A" defaultValue="" className="java.lang.Object"/>
      <data xmi:type="process:Data" xmi:id="_Uh4C8HIhEd-LorYRZnxm3A" name="listAsString" label="listAsString" dataType="_OLSUVXIhEd-LorYRZnxm3A"/>
      <data xmi:type="process:Data" xmi:id="_TxlOcHIhEd-LorYRZnxm3A" name="text" label="text" dataType="_OLSUVXIhEd-LorYRZnxm3A"/>
      <confirmationTemplate xmi:type="process:AssociatedFile" xmi:id="_owNvI3IiEd-LorYRZnxm3A" path="black/WEB-INF/classes/html/confirmation.html"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OcziIHIhEd-LorYRZnxm3A" source="_OccVwHIhEd-LorYRZnxm3A" target="_OcQIgHIhEd-LorYRZnxm3A"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cT8REHIhEd-LorYRZnxm3A" source="_OcQIgHIhEd-LorYRZnxm3A" target="_dX6PgHIhEd-LorYRZnxm3A"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iZqSIHIhEd-LorYRZnxm3A" source="_dX6PgHIhEd-LorYRZnxm3A" target="_k2jyYHIhEd-LorYRZnxm3A" condition="counter &lt; 10"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rhBfQHIhEd-LorYRZnxm3A" source="_dX6PgHIhEd-LorYRZnxm3A" target="_tF8OoHIhEd-LorYRZnxm3A" isDefault="true" condition=""/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2FqisHIhEd-LorYRZnxm3A" source="_k2jyYHIhEd-LorYRZnxm3A" target="_2FdHUHIhEd-LorYRZnxm3A"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2ggroHIhEd-LorYRZnxm3A" source="_tF8OoHIhEd-LorYRZnxm3A" target="_2FdHUHIhEd-LorYRZnxm3A"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4Q5EIHIhEd-LorYRZnxm3A" source="_2FdHUHIhEd-LorYRZnxm3A" target="_6V3zoHIhEd-LorYRZnxm3A"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_9Ir5gHIhEd-LorYRZnxm3A" source="_6V3zoHIhEd-LorYRZnxm3A" target="_9IeeIHIhEd-LorYRZnxm3A"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DDvisHIiEd-LorYRZnxm3A" source="__dtQIHIhEd-LorYRZnxm3A" target="_DDiHUHIiEd-LorYRZnxm3A"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_owNvIXIiEd-LorYRZnxm3A" path="black/WEB-INF/classes/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_owNvIHIiEd-LorYRZnxm3A" path="black/WEB-INF/classes/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_owNvInIiEd-LorYRZnxm3A" path="black/WEB-INF/classes/html/page.html"/>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_GA4CMHIiEd-LorYRZnxm3A" name="process2" label="process2">
      <elements xmi:type="process:StartMessageEvent" xmi:id="_IkqNkHIiEd-LorYRZnxm3A" name="Receive_message_from_process1" label="Receive message from process1" outgoing="_ZDA2YHIiEd-LorYRZnxm3A" event="message">
        <connectors xmi:type="process:Connector" xmi:id="_XxXoUHIiEd-LorYRZnxm3A" name="map_received_variable" label="map received variable" connectorId="SetVariable">
          <parameters xmi:type="process:Parameter" xmi:id="_XxXoUXIiEd-LorYRZnxm3A" key="setVariableName" value="ACED000574001072656365697665645661726961626C65"/>
          <parameters xmi:type="process:Parameter" xmi:id="_XxYPYHIiEd-LorYRZnxm3A" key="setValue" value="ACED000574000F247B73656E745661726961626C657D"/>
        </connectors>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_ZbwtkHIiEd-LorYRZnxm3A" name="Dynamic_label_Task" label="Dynamic label Task" outgoing="_iLBjwHIiEd-LorYRZnxm3A" incoming="_ZDA2YHIiEd-LorYRZnxm3A" dynamicLabel="${&quot;This is the dynamic label. Received variable is: &quot; + receivedVariable}" user="admin" actorType="USER"/>
      <elements xmi:type="process:EndEvent" xmi:id="_iK3LsHIiEd-LorYRZnxm3A" name="End1" label="End1" incoming="_iLBjwHIiEd-LorYRZnxm3A"/>
      <data xmi:type="process:Data" xmi:id="_TKVLwHIiEd-LorYRZnxm3A" name="receivedVariable" label="receivedVariable" dataType="_OLSUU3IhEd-LorYRZnxm3A" defaultValue="0"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZDA2YHIiEd-LorYRZnxm3A" source="_IkqNkHIiEd-LorYRZnxm3A" target="_ZbwtkHIiEd-LorYRZnxm3A"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iLBjwHIiEd-LorYRZnxm3A" source="_ZbwtkHIiEd-LorYRZnxm3A" target="_iK3LsHIiEd-LorYRZnxm3A"/>
    </elements>
    <groups xmi:type="process:Group" xmi:id="_OcpKEHIhEd-LorYRZnxm3A" documentation="Person who takes the first action to start the process" name="Initiator" label="Initiator" connectorId="ProcessInitiatior"/>
    <datatypes xmi:type="process:BooleanType" xmi:id="_OLSUUXIhEd-LorYRZnxm3A" name="Boolean" label="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_OLSUUnIhEd-LorYRZnxm3A" name="Date" label="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_OLSUU3IhEd-LorYRZnxm3A" name="Integer" label="Integer"/>
    <datatypes xmi:type="process:FloatType" xmi:id="_OLSUVHIhEd-LorYRZnxm3A" name="Decimal" label="Decimal"/>
    <datatypes xmi:type="process:StringType" xmi:id="_OLSUVXIhEd-LorYRZnxm3A" name="Text" label="Text"/>
    <datatypes xmi:type="process:AttachmentType" xmi:id="_OLSUVnIhEd-LorYRZnxm3A" name="Attachment" label="Attachment"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_OLSUV3IhEd-LorYRZnxm3A" name="Java_object" label="Java object"/>
    <includedEntries>bonita/bonita-5.2.jar</includedEntries>
    <includedEntries>CreateList.jar</includedEntries>
    <includedEntries>scripting/scripting-5.2.jar</includedEntries>
  </process:MainProcess>
  <notation:Diagram xmi:id="_OLS7YHIhEd-LorYRZnxm3A" type="Process" element="_OLSUUHIhEd-LorYRZnxm3A" name="BPMN_Showcase_1.0.proc" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_OcHloHIhEd-LorYRZnxm3A" type="2007" element="_Ob-bsHIhEd-LorYRZnxm3A">
      <children xmi:type="notation:DecorationNode" xmi:id="_OcIMsHIhEd-LorYRZnxm3A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_OcIMsXIhEd-LorYRZnxm3A" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_OcTL0HIhEd-LorYRZnxm3A" type="3005" element="_OcQIgHIhEd-LorYRZnxm3A" fontName="Lucida Grande">
          <children xmi:type="notation:DecorationNode" xmi:id="_OcTL0nIhEd-LorYRZnxm3A" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OcTL0XIhEd-LorYRZnxm3A" x="110" y="55"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_OcfZEHIhEd-LorYRZnxm3A" type="3002" element="_OccVwHIhEd-LorYRZnxm3A" fontName="Lucida Grande">
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OcfZEXIhEd-LorYRZnxm3A" x="25" y="65"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_dX_vEHIhEd-LorYRZnxm3A" type="3005" element="_dX6PgHIhEd-LorYRZnxm3A" fontName="Lucida Grande">
          <children xmi:type="notation:DecorationNode" xmi:id="_dYAWIHIhEd-LorYRZnxm3A" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dX_vEXIhEd-LorYRZnxm3A" x="294" y="55" width="100" height="50"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_k2oq4HIhEd-LorYRZnxm3A" type="3028" element="_k2jyYHIhEd-LorYRZnxm3A" fontName="Lucida Grande">
          <children xmi:type="notation:DecorationNode" xmi:id="_k2pR8HIhEd-LorYRZnxm3A" type="5018"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_k2oq4XIhEd-LorYRZnxm3A" x="459" y="10" width="100" height="50"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_tGBHIHIhEd-LorYRZnxm3A" type="3027" element="_tF8OoHIhEd-LorYRZnxm3A" fontName="Lucida Grande">
          <children xmi:type="notation:DecorationNode" xmi:id="_tGBuMHIhEd-LorYRZnxm3A" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tGBHIXIhEd-LorYRZnxm3A" x="459" y="104" width="100" height="50"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_2FhYwHIhEd-LorYRZnxm3A" type="3009" element="_2FdHUHIhEd-LorYRZnxm3A" fontName="Lucida Grande">
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2FhYwXIhEd-LorYRZnxm3A" x="618" y="58"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_6V96QHIhEd-LorYRZnxm3A" type="3005" element="_6V3zoHIhEd-LorYRZnxm3A" fontName="Lucida Grande">
          <children xmi:type="notation:DecorationNode" xmi:id="_6V-hUHIhEd-LorYRZnxm3A" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6V96QXIhEd-LorYRZnxm3A" x="690" y="55" width="100" height="50"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_9IivkHIhEd-LorYRZnxm3A" type="3018" element="_9IeeIHIhEd-LorYRZnxm3A" fontName="Lucida Grande">
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9IivkXIhEd-LorYRZnxm3A" x="834" y="65"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="__dzWwHIhEd-LorYRZnxm3A" type="3019" element="__dtQIHIhEd-LorYRZnxm3A" fontName="Lucida Grande">
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__dzWwXIhEd-LorYRZnxm3A" x="25" y="189"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_DDoN8HIiEd-LorYRZnxm3A" type="3011" element="_DDiHUHIiEd-LorYRZnxm3A" fontName="Lucida Grande">
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DDoN8XIiEd-LorYRZnxm3A" x="145" y="191"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_OcHloXIhEd-LorYRZnxm3A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_OcHlonIhEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_OcHlo3IhEd-LorYRZnxm3A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OcHlpHIhEd-LorYRZnxm3A" x="20" width="1040" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_GA8ToHIiEd-LorYRZnxm3A" type="2007" element="_GA4CMHIiEd-LorYRZnxm3A">
      <children xmi:type="notation:DecorationNode" xmi:id="_GA86sHIiEd-LorYRZnxm3A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_GA86sXIiEd-LorYRZnxm3A" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_IkvGEHIiEd-LorYRZnxm3A" type="3012" element="_IkqNkHIiEd-LorYRZnxm3A" fontName="Lucida Grande">
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IkvGEXIiEd-LorYRZnxm3A" x="27" y="35"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Zb20MHIiEd-LorYRZnxm3A" type="3005" element="_ZbwtkHIiEd-LorYRZnxm3A" fontName="Lucida Grande">
          <children xmi:type="notation:DecorationNode" xmi:id="_Zb20MnIiEd-LorYRZnxm3A" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Zb20MXIiEd-LorYRZnxm3A" x="124" y="27" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_iK62EHIiEd-LorYRZnxm3A" type="3003" element="_iK3LsHIiEd-LorYRZnxm3A" fontName="Lucida Grande">
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iK62EXIiEd-LorYRZnxm3A" x="340" y="42"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_GA8ToXIiEd-LorYRZnxm3A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_GA8TonIiEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_GA8To3IiEd-LorYRZnxm3A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GA8TpHIiEd-LorYRZnxm3A" x="20" width="1040" height="100"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_OLS7YXIhEd-LorYRZnxm3A"/>
    <edges xmi:type="notation:Connector" xmi:id="_Oc1XUHIhEd-LorYRZnxm3A" type="4001" element="_OcziIHIhEd-LorYRZnxm3A" source="_OcfZEHIhEd-LorYRZnxm3A" target="_OcTL0HIhEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_Oc1XU3IhEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Oc1XVHIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_Oc1XVXIhEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Oc1-YHIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Oc1XUXIhEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Oc1XUnIhEd-LorYRZnxm3A" points="[0, 0, -110, -55]$[110, 55, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cT-tUHIhEd-LorYRZnxm3A" type="4001" element="_cT8REHIhEd-LorYRZnxm3A" source="_OcTL0HIhEd-LorYRZnxm3A" target="_dX_vEHIhEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_cT_UYnIhEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cT_UY3IhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_cT_UZHIhEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cT_UZXIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cT_UYHIhEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cT_UYXIhEd-LorYRZnxm3A" points="[50, -10, -84, 15]$[134, -25, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iZujkHIhEd-LorYRZnxm3A" type="4001" element="_iZqSIHIhEd-LorYRZnxm3A" source="_dX_vEHIhEd-LorYRZnxm3A" target="_k2oq4HIhEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_iZvKoHIhEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iZvKoXIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_iZvKonIhEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iZvKo3IhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iZujkXIhEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iZujknIhEd-LorYRZnxm3A" points="[41, -25, -74, 45]$[115, -70, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rhFwsHIhEd-LorYRZnxm3A" type="4001" element="_rhBfQHIhEd-LorYRZnxm3A" source="_dX_vEHIhEd-LorYRZnxm3A" target="_tGBHIHIhEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_rhFws3IhEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rhFwtHIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_rhGXwHIhEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rhGXwXIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rhFwsXIhEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rhFwsnIhEd-LorYRZnxm3A" points="[50, 10, -65, -14]$[115, 24, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2FtmAHIhEd-LorYRZnxm3A" type="4001" element="_2FqisHIhEd-LorYRZnxm3A" source="_k2oq4HIhEd-LorYRZnxm3A" target="_2FhYwHIhEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_2FtmA3IhEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2FtmBHIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_2FuNEHIhEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2FuNEXIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2FtmAXIhEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2FtmAnIhEd-LorYRZnxm3A" points="[-50, -4, 459, 31]$[-509, -35, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2gk9EHIhEd-LorYRZnxm3A" type="4001" element="_2ggroHIhEd-LorYRZnxm3A" source="_tGBHIHIhEd-LorYRZnxm3A" target="_2FhYwHIhEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_2glkIHIhEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2glkIXIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_2glkInIhEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2glkI3IhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2gk9EXIhEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2gk9EnIhEd-LorYRZnxm3A" points="[0, 0, -80, 75]$[69, -64, -11, 11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2goncHIhEd-LorYRZnxm3A" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4Q8HcHIhEd-LorYRZnxm3A" type="4001" element="_4Q5EIHIhEd-LorYRZnxm3A" source="_2FhYwHIhEd-LorYRZnxm3A" target="_6V96QHIhEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_4Q8ugHIhEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4Q8ugXIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_4Q8ugnIhEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4Q8ug3IhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4Q8HcXIhEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4Q8HcnIhEd-LorYRZnxm3A" points="[15, -7, -36, 17]$[51, -24, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_9IwK8HIhEd-LorYRZnxm3A" type="4001" element="_9Ir5gHIhEd-LorYRZnxm3A" source="_6V96QHIhEd-LorYRZnxm3A" target="_9IivkHIhEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_9IwK83IhEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9IwK9HIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_9IwK9XIhEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_9IwK9nIhEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_9IwK8XIhEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_9IwK8nIhEd-LorYRZnxm3A" points="[50, -8, -44, 7]$[94, -15, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DDx-8HIiEd-LorYRZnxm3A" type="4001" element="_DDvisHIiEd-LorYRZnxm3A" source="__dzWwHIhEd-LorYRZnxm3A" target="_DDoN8HIiEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_DDx-83IiEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DDx-9HIiEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_DDx-9XIiEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DDx-9nIiEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DDx-8XIiEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DDx-8nIiEd-LorYRZnxm3A" points="[17, -3, -86, 12]$[103, -15, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZDD5sHIiEd-LorYRZnxm3A" type="4001" element="_ZDA2YHIiEd-LorYRZnxm3A" source="_IkvGEHIiEd-LorYRZnxm3A" target="_Zb20MHIiEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZDEgwHIiEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZDEgwXIiEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_ZDEgwnIiEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZDEgw3IiEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZDD5sXIiEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZDD5snIiEd-LorYRZnxm3A" points="[17, -6, -63, 19]$[80, -25, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iLEnEHIiEd-LorYRZnxm3A" type="4001" element="_iLBjwHIiEd-LorYRZnxm3A" source="_Zb20MHIiEd-LorYRZnxm3A" target="_iK62EHIiEd-LorYRZnxm3A" routing="Rectilinear" roundedBendpointsRadius="10">
      <children xmi:type="notation:DecorationNode" xmi:id="_iLFOIHIiEd-LorYRZnxm3A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iLFOIXIiEd-LorYRZnxm3A" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_iLFOInIiEd-LorYRZnxm3A" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iLFOI3IiEd-LorYRZnxm3A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iLEnEXIiEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iLEnEnIiEd-LorYRZnxm3A" points="[-60, -19, 124, 38]$[-184, -57, 0, 0]"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_qel8dnIiEd-LorYRZnxm3A" type="Form" element="_qel8cHIiEd-LorYRZnxm3A" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_qel8d3IiEd-LorYRZnxm3A"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_tYNN4HIiEd-LorYRZnxm3A" type="Form" element="_tYI8cHIiEd-LorYRZnxm3A" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_tZBtQHIiEd-LorYRZnxm3A" type="2120" element="_tYI8cXIiEd-LorYRZnxm3A" fontName="Lucida Grande">
      <children xmi:type="notation:DecorationNode" xmi:id="_tZBtQnIiEd-LorYRZnxm3A" type="5108"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tZBtQXIiEd-LorYRZnxm3A"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_tZBtQ3IiEd-LorYRZnxm3A" type="2126" element="_tYI8dHIiEd-LorYRZnxm3A">
      <children xmi:type="notation:DecorationNode" xmi:id="_tZBtSHIiEd-LorYRZnxm3A" type="5125"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_tZBtRHIiEd-LorYRZnxm3A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_tZBtRXIiEd-LorYRZnxm3A" fontName="Lucida Grande"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_tZBtRnIiEd-LorYRZnxm3A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tZBtR3IiEd-LorYRZnxm3A"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_wcEngHIiEd-LorYRZnxm3A" type="2139" element="_wb4aQHIiEd-LorYRZnxm3A" fontName="Lucida Grande">
      <children xmi:type="notation:DecorationNode" xmi:id="_wcEngnIiEd-LorYRZnxm3A" type="5151"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wcEngXIiEd-LorYRZnxm3A"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_tYNN4XIiEd-LorYRZnxm3A"/>
  </notation:Diagram>
</xmi:XMI>
