<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process">
  <process:MainProcess xmi:id="_qSGu0D2lEeCPOrv-sXwSpQ" name="TRAVEL_Diagram1" label="TRAVEL Diagram1" bonitaVersion="5.4" bonitaModelVersion="5.4">
    <elements xmi:type="process:Pool" xmi:id="_qUtW4D2lEeCPOrv-sXwSpQ" name="Travel_request_approval_process" label="Travel request/approval process" welcomePageInternal="false">
      <elements xmi:type="process:Task" xmi:id="_qVKC0D2lEeCPOrv-sXwSpQ" name="Submit_travel_request" label="Submit travel request" outgoing="_xDxacD2mEeCPOrv-sXwSpQ" incoming="_qzoHgD2lEeCPOrv-sXwSpQ" user="" groups="_qVmuwD2lEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:StartEvent" xmi:id="_qVZTYD2lEeCPOrv-sXwSpQ" name="Start1" label="Start1" outgoing="_qzoHgD2lEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:Task" xmi:id="_0PQUcD2lEeCPOrv-sXwSpQ" name="Approve_travel_request" label="Approve travel request" outgoing="_zCkpcD2mEeCPOrv-sXwSpQ" incoming="_xDxacD2mEeCPOrv-sXwSpQ" user="" groups="_qVmuwD2lEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:Activity" xmi:id="_5FdOYD2lEeCPOrv-sXwSpQ" name="Travel" label="Travel" outgoing="_rGPFAD2mEeCPOrv-sXwSpQ" incoming="_iJ_34D2oEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:Activity" xmi:id="_77AfMD2lEeCPOrv-sXwSpQ" name="Notify_employee" label="Notify employee" outgoing="_JN-KED2mEeCPOrv-sXwSpQ" incoming="_zkylsD2mEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:XORGateway" xmi:id="__OfpMD2lEeCPOrv-sXwSpQ" name="_" label=" " exclusiveOutgoingTransition="true" outgoing="_qOyfoD2mEeCPOrv-sXwSpQ" incoming="_JN-KED2mEeCPOrv-sXwSpQ _rGPFAD2mEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:EndEvent" xmi:id="_AWiPUD2mEeCPOrv-sXwSpQ" name="End1" label="End1" incoming="_qOyfoD2mEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:XORGateway" xmi:id="_yFDRQD2mEeCPOrv-sXwSpQ" name="__" label="  " exclusiveOutgoingTransition="true" outgoing="_zkylsD2mEeCPOrv-sXwSpQ _56dR0D2nEeCPOrv-sXwSpQ" incoming="_zCkpcD2mEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:ANDGateway" xmi:id="_56P2cD2nEeCPOrv-sXwSpQ" name="____" label="    " outgoing="_6aKsoD2nEeCPOrv-sXwSpQ _7eNjkD2nEeCPOrv-sXwSpQ" incoming="_56dR0D2nEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:XORGateway" xmi:id="_-BFwAD2nEeCPOrv-sXwSpQ" name="___" label="   " exclusiveOutgoingTransition="true" outgoing="_DVtEQD2oEeCPOrv-sXwSpQ _EMfiUD2oEeCPOrv-sXwSpQ _JB0SgD2oEeCPOrv-sXwSpQ" incoming="_6aKsoD2nEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:XORGateway" xmi:id="_-dn7AD2nEeCPOrv-sXwSpQ" name="_____" label="     " exclusiveOutgoingTransition="true" outgoing="_mg_GQD2oEeCPOrv-sXwSpQ _n7q7kD2oEeCPOrv-sXwSpQ" incoming="_7eNjkD2nEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:XORGateway" xmi:id="_H__pID2oEeCPOrv-sXwSpQ" name="______" label="      " exclusiveOutgoingTransition="true" outgoing="_hF7LwD2oEeCPOrv-sXwSpQ" incoming="_JB0SgD2oEeCPOrv-sXwSpQ _Jwk18D2oEeCPOrv-sXwSpQ _KQHRoD2oEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:ANDGateway" xmi:id="_cOeUoD2oEeCPOrv-sXwSpQ" name="________" label="        " outgoing="_iJ_34D2oEeCPOrv-sXwSpQ" incoming="_hF7LwD2oEeCPOrv-sXwSpQ _pP0EAD2oEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:XORGateway" xmi:id="_ocTjcD2oEeCPOrv-sXwSpQ" name="Gate1" label="Gate1" exclusiveOutgoingTransition="true" outgoing="_pP0EAD2oEeCPOrv-sXwSpQ" incoming="_n7q7kD2oEeCPOrv-sXwSpQ _qAD1MD2oEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:Task" xmi:id="_9bL7sD2pEeCPOrv-sXwSpQ" name="airplane_ticket" label="airplane ticket" outgoing="_Jwk18D2oEeCPOrv-sXwSpQ" incoming="_DVtEQD2oEeCPOrv-sXwSpQ" user="" groups="_qVmuwD2lEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:Task" xmi:id="__bg0sD2pEeCPOrv-sXwSpQ" name="train_ticket" label="train ticket" outgoing="_KQHRoD2oEeCPOrv-sXwSpQ" incoming="_EMfiUD2oEeCPOrv-sXwSpQ" user="" groups="_qVmuwD2lEeCPOrv-sXwSpQ"/>
      <elements xmi:type="process:Task" xmi:id="_BwH7oD2qEeCPOrv-sXwSpQ" name="hotel_room_booking" label="hotel room booking" outgoing="_qAD1MD2oEeCPOrv-sXwSpQ" incoming="_mg_GQD2oEeCPOrv-sXwSpQ" user="" groups="_qVmuwD2lEeCPOrv-sXwSpQ"/>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_qzdvcD2lEeCPOrv-sXwSpQ" path="User/_qUtW4D2lEeCPOrv-sXwSpQ/application/application"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_qzdvcT2lEeCPOrv-sXwSpQ" path="User/_qUtW4D2lEeCPOrv-sXwSpQ/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_qzdvcz2lEeCPOrv-sXwSpQ" path="User/_qUtW4D2lEeCPOrv-sXwSpQ/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_qzdvcj2lEeCPOrv-sXwSpQ" path="User/_qUtW4D2lEeCPOrv-sXwSpQ/html/consultation.html"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qzoHgD2lEeCPOrv-sXwSpQ" name="t1" label="t1" source="_qVZTYD2lEeCPOrv-sXwSpQ" target="_qVKC0D2lEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JN-KED2mEeCPOrv-sXwSpQ" name="t5" label="t5" source="_77AfMD2lEeCPOrv-sXwSpQ" target="__OfpMD2lEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qOyfoD2mEeCPOrv-sXwSpQ" name="t15" label="t15" source="__OfpMD2lEeCPOrv-sXwSpQ" target="_AWiPUD2mEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rGPFAD2mEeCPOrv-sXwSpQ" name="t14" label="t14" source="_5FdOYD2lEeCPOrv-sXwSpQ" target="__OfpMD2lEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xDxacD2mEeCPOrv-sXwSpQ" name="t2" label="t2" source="_qVKC0D2lEeCPOrv-sXwSpQ" target="_0PQUcD2lEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zCkpcD2mEeCPOrv-sXwSpQ" name="t3" label="t3" source="_0PQUcD2lEeCPOrv-sXwSpQ" target="_yFDRQD2mEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zkylsD2mEeCPOrv-sXwSpQ" name="t4" label="t4" source="_yFDRQD2mEeCPOrv-sXwSpQ" target="_77AfMD2lEeCPOrv-sXwSpQ" isDefault="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_56dR0D2nEeCPOrv-sXwSpQ" name="ok" label="ok" source="_yFDRQD2mEeCPOrv-sXwSpQ" target="_56P2cD2nEeCPOrv-sXwSpQ" condition="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6aKsoD2nEeCPOrv-sXwSpQ" name="t6" label="t6" source="_56P2cD2nEeCPOrv-sXwSpQ" target="_-BFwAD2nEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7eNjkD2nEeCPOrv-sXwSpQ" name="t7" label="t7" source="_56P2cD2nEeCPOrv-sXwSpQ" target="_-dn7AD2nEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DVtEQD2oEeCPOrv-sXwSpQ" name="airplane_needed__" label="airplane needed ?" source="_-BFwAD2nEeCPOrv-sXwSpQ" target="_9bL7sD2pEeCPOrv-sXwSpQ" condition="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EMfiUD2oEeCPOrv-sXwSpQ" name="train_needed__" label="train needed ?" source="_-BFwAD2nEeCPOrv-sXwSpQ" target="__bg0sD2pEeCPOrv-sXwSpQ" condition="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JB0SgD2oEeCPOrv-sXwSpQ" name="no_transport_needed" label="no transport needed" source="_-BFwAD2nEeCPOrv-sXwSpQ" target="_H__pID2oEeCPOrv-sXwSpQ" isDefault="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Jwk18D2oEeCPOrv-sXwSpQ" name="t8" label="t8" source="_9bL7sD2pEeCPOrv-sXwSpQ" target="_H__pID2oEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KQHRoD2oEeCPOrv-sXwSpQ" name="t9" label="t9" source="__bg0sD2pEeCPOrv-sXwSpQ" target="_H__pID2oEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hF7LwD2oEeCPOrv-sXwSpQ" name="t12" label="t12" source="_H__pID2oEeCPOrv-sXwSpQ" target="_cOeUoD2oEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iJ_34D2oEeCPOrv-sXwSpQ" name="t13" label="t13" source="_cOeUoD2oEeCPOrv-sXwSpQ" target="_5FdOYD2lEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mg_GQD2oEeCPOrv-sXwSpQ" name="hotel_needed__" label="hotel needed ?" source="_-dn7AD2nEeCPOrv-sXwSpQ" target="_BwH7oD2qEeCPOrv-sXwSpQ" condition="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_n7q7kD2oEeCPOrv-sXwSpQ" name="no_need" label="no need" source="_-dn7AD2nEeCPOrv-sXwSpQ" target="_ocTjcD2oEeCPOrv-sXwSpQ" isDefault="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pP0EAD2oEeCPOrv-sXwSpQ" name="t11" label="t11" source="_ocTjcD2oEeCPOrv-sXwSpQ" target="_cOeUoD2oEeCPOrv-sXwSpQ"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qAD1MD2oEeCPOrv-sXwSpQ" name="t10" label="t10" source="_BwH7oD2qEeCPOrv-sXwSpQ" target="_ocTjcD2oEeCPOrv-sXwSpQ"/>
    </elements>
    <groups xmi:type="process:Group" xmi:id="_qVmuwD2lEeCPOrv-sXwSpQ" documentation="Person who takes the first action to start the process" name="Initiator" label="Initiator" connectorId="ProcessInitiatior"/>
    <datatypes xmi:type="process:BooleanType" xmi:id="_qSHV4D2lEeCPOrv-sXwSpQ" name="Boolean" label="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_qSHV4T2lEeCPOrv-sXwSpQ" name="Date" label="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_qSHV4j2lEeCPOrv-sXwSpQ" name="Integer" label="Integer"/>
    <datatypes xmi:type="process:FloatType" xmi:id="_qSHV4z2lEeCPOrv-sXwSpQ" name="Decimal" label="Decimal"/>
    <datatypes xmi:type="process:StringType" xmi:id="_qSHV5D2lEeCPOrv-sXwSpQ" name="Text" label="Text"/>
    <datatypes xmi:type="process:AttachmentType" xmi:id="_qSHV5T2lEeCPOrv-sXwSpQ" name="Attachment" label="Attachment"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_qSHV5j2lEeCPOrv-sXwSpQ" name="Java_object" label="Java object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_qSHV5z2lEeCPOrv-sXwSpQ" name="XML" label="XML"/>
    <includedEntries>bonita/bonita-5.4.jar</includedEntries>
  </process:MainProcess>
  <notation:Diagram xmi:id="_qSHV6D2lEeCPOrv-sXwSpQ" type="Process" element="_qSGu0D2lEeCPOrv-sXwSpQ" name="TRAVEL_Diagram1_1.0.proc" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_qU6yQD2lEeCPOrv-sXwSpQ" type="2007" element="_qUtW4D2lEeCPOrv-sXwSpQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_qU7ZUD2lEeCPOrv-sXwSpQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_qU7ZUT2lEeCPOrv-sXwSpQ" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_qVTMwD2lEeCPOrv-sXwSpQ" type="3005" element="_qVKC0D2lEeCPOrv-sXwSpQ" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_qVTz0D2lEeCPOrv-sXwSpQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qVTMwT2lEeCPOrv-sXwSpQ" x="66" y="18" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_qVidUD2lEeCPOrv-sXwSpQ" type="3002" element="_qVZTYD2lEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_qVidUj2lEeCPOrv-sXwSpQ" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_qVjEYD2lEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qVidUT2lEeCPOrv-sXwSpQ" x="21" y="110"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_0Pdv0D2lEeCPOrv-sXwSpQ" type="3005" element="_0PQUcD2lEeCPOrv-sXwSpQ" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_0PeW4D2lEeCPOrv-sXwSpQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0Pdv0T2lEeCPOrv-sXwSpQ" x="28" y="240" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_5FrQ0D2lEeCPOrv-sXwSpQ" type="3006" element="_5FdOYD2lEeCPOrv-sXwSpQ" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_5Fr34D2lEeCPOrv-sXwSpQ" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5FrQ0T2lEeCPOrv-sXwSpQ" x="844" y="144"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_77OhoD2lEeCPOrv-sXwSpQ" type="3006" element="_77AfMD2lEeCPOrv-sXwSpQ" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_77Ohoj2lEeCPOrv-sXwSpQ" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_77OhoT2lEeCPOrv-sXwSpQ" x="574" y="10"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="__OuSsD2lEeCPOrv-sXwSpQ" type="3008" element="__OfpMD2lEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="__Ou5wD2lEeCPOrv-sXwSpQ" visible="false" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="__Ou5wT2lEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__OuSsT2lEeCPOrv-sXwSpQ" x="892" y="68"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_AWvqsD2mEeCPOrv-sXwSpQ" type="3003" element="_AWiPUD2mEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_AWvqsj2mEeCPOrv-sXwSpQ" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_AWvqsz2mEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AWvqsT2mEeCPOrv-sXwSpQ" x="975" y="75"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_yFLNED2mEeCPOrv-sXwSpQ" type="3008" element="_yFDRQD2mEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_yFL0ID2mEeCPOrv-sXwSpQ" visible="false" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_yFL0IT2mEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yFLNET2mEeCPOrv-sXwSpQ" x="143" y="147"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_56YZUD2nEeCPOrv-sXwSpQ" type="3009" element="_56P2cD2nEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_56YZUj2nEeCPOrv-sXwSpQ" visible="false" type="5020">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_56YZUz2nEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_56YZUT2nEeCPOrv-sXwSpQ" x="268" y="147"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_-BPhAD2nEeCPOrv-sXwSpQ" type="3008" element="_-BFwAD2nEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_-BQIED2nEeCPOrv-sXwSpQ" visible="false" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_-BQIET2nEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-BPhAT2nEeCPOrv-sXwSpQ" x="317" y="81" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_-dwd4D2nEeCPOrv-sXwSpQ" type="3008" element="_-dn7AD2nEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_-dwd4j2nEeCPOrv-sXwSpQ" visible="false" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_-dwd4z2nEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-dwd4T2nEeCPOrv-sXwSpQ" x="318" y="240" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_IAL2YD2oEeCPOrv-sXwSpQ" type="3008" element="_H__pID2oEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_IAMdcD2oEeCPOrv-sXwSpQ" visible="false" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_IAMdcT2oEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IAL2YT2oEeCPOrv-sXwSpQ" x="700" y="78"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_cOlpYD2oEeCPOrv-sXwSpQ" type="3009" element="_cOeUoD2oEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_cOlpYj2oEeCPOrv-sXwSpQ" visible="false" type="5020">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_cOlpYz2oEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cOlpYT2oEeCPOrv-sXwSpQ" x="748" y="147"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_oca4MD2oEeCPOrv-sXwSpQ" type="3008" element="_ocTjcD2oEeCPOrv-sXwSpQ" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_oca4Mj2oEeCPOrv-sXwSpQ" visible="false" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_oca4Mz2oEeCPOrv-sXwSpQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oca4MT2oEeCPOrv-sXwSpQ" x="700" y="240" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_9bWTwD2pEeCPOrv-sXwSpQ" type="3005" element="_9bL7sD2pEeCPOrv-sXwSpQ" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_9bWTwj2pEeCPOrv-sXwSpQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9bWTwT2pEeCPOrv-sXwSpQ" x="508" y="75" width="100" height="50"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="__bsa4D2pEeCPOrv-sXwSpQ" type="3005" element="__bg0sD2pEeCPOrv-sXwSpQ" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="__bsa4j2pEeCPOrv-sXwSpQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__bsa4T2pEeCPOrv-sXwSpQ" x="475" y="144" width="100" height="50"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_BwRsoD2qEeCPOrv-sXwSpQ" type="3005" element="_BwH7oD2qEeCPOrv-sXwSpQ" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_BwSTsD2qEeCPOrv-sXwSpQ" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BwRsoT2qEeCPOrv-sXwSpQ" x="498" y="220" width="100" height="50"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_qU6yQT2lEeCPOrv-sXwSpQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_qU6yQj2lEeCPOrv-sXwSpQ" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_qU6yQz2lEeCPOrv-sXwSpQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_qU7ZUj2lEeCPOrv-sXwSpQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qU6yRD2lEeCPOrv-sXwSpQ" width="1034" height="337"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_qSHV6T2lEeCPOrv-sXwSpQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_qztAAD2lEeCPOrv-sXwSpQ" type="4001" element="_qzoHgD2lEeCPOrv-sXwSpQ" source="_qVidUD2lEeCPOrv-sXwSpQ" target="_qVTMwD2lEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qztnED2lEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qztnET2lEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_qztnEj2lEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qzu1MD2lEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qztAAT2lEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qztAAj2lEeCPOrv-sXwSpQ" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_e95aMD2mEeCPOrv-sXwSpQ" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_e95aMT2mEeCPOrv-sXwSpQ" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JOH7ED2mEeCPOrv-sXwSpQ" type="4001" element="_JN-KED2mEeCPOrv-sXwSpQ" source="_77OhoD2lEeCPOrv-sXwSpQ" target="__OuSsD2lEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JOIiID2mEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JOIiIT2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_JOIiIj2mEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JOIiIz2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JOH7ET2mEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JOH7Ej2mEeCPOrv-sXwSpQ" points="[0, 0, -152, -40]$[151, 39, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JOK-YD2mEeCPOrv-sXwSpQ" id="(1.0,0.56)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JOK-YT2mEeCPOrv-sXwSpQ" id="(0.27906976744186046,0.23255813953488372)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qPEMcD2mEeCPOrv-sXwSpQ" type="4001" element="_qOyfoD2mEeCPOrv-sXwSpQ" source="__OuSsD2lEeCPOrv-sXwSpQ" target="_AWvqsD2mEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qPEMcz2mEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qPEMdD2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_qPEMdT2mEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qPEzgD2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qPEMcT2mEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qPEMcj2mEeCPOrv-sXwSpQ" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qPJE8D2mEeCPOrv-sXwSpQ" id="(1.0,0.4883720930232558)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_A6kUAD2nEeCPOrv-sXwSpQ" id="(0.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rGT9gD2mEeCPOrv-sXwSpQ" type="4001" element="_rGPFAD2mEeCPOrv-sXwSpQ" source="_5FrQ0D2lEeCPOrv-sXwSpQ" target="__OuSsD2lEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rGUkkD2mEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rGUkkT2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_rGUkkj2mEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rGUkkz2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rGT9gT2mEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rGT9gj2mEeCPOrv-sXwSpQ" points="[0, 0, -65, 62]$[65, -40, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rGY2AD2mEeCPOrv-sXwSpQ" id="(1.0,0.62)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xD3hED2mEeCPOrv-sXwSpQ" type="4001" element="_xDxacD2mEeCPOrv-sXwSpQ" source="_qVTMwD2lEeCPOrv-sXwSpQ" target="_0Pdv0D2lEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xD3hEz2mEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xD4IID2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_xD4IIT2mEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xD4IIj2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xD3hET2mEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xD3hEj2mEeCPOrv-sXwSpQ" points="[-99, 31, 50, -202]$[-99, 112, 50, -121]$[-124, 112, 25, -121]$[-124, 193, 25, -40]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xD7LcD2mEeCPOrv-sXwSpQ" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xD7LcT2mEeCPOrv-sXwSpQ" id="(0.075,0.6666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zCslQD2mEeCPOrv-sXwSpQ" type="4001" element="_zCkpcD2mEeCPOrv-sXwSpQ" source="_0Pdv0D2lEeCPOrv-sXwSpQ" target="_yFLNED2mEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zCtMUD2mEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zCtMUT2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_zCtMUj2mEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zCtMUz2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zCslQT2mEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zCslQj2mEeCPOrv-sXwSpQ" points="[0, 0, -60, -32]$[61, 33, 1, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zCvokD2mEeCPOrv-sXwSpQ" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zCvokT2mEeCPOrv-sXwSpQ" id="(0.3023255813953488,0.11627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zk4sUD2mEeCPOrv-sXwSpQ" type="4001" element="_zkylsD2mEeCPOrv-sXwSpQ" source="_yFLNED2mEeCPOrv-sXwSpQ" target="_77OhoD2lEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zk4sUz2mEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zk4sVD2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_zk4sVT2mEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zk4sVj2mEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zk4sUT2mEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zk4sUj2mEeCPOrv-sXwSpQ" points="[0, -7, -409, 116]$[34, -7, -375, 116]$[34, -127, -375, -4]$[388, -127, -21, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zk7voD2mEeCPOrv-sXwSpQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zk7voT2mEeCPOrv-sXwSpQ" id="(0.21,0.84)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_56lNoD2nEeCPOrv-sXwSpQ" type="4001" element="_56dR0D2nEeCPOrv-sXwSpQ" source="_yFLNED2mEeCPOrv-sXwSpQ" target="_56YZUD2nEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_56lNoz2nEeCPOrv-sXwSpQ" visible="false" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_56lNpD2nEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_56l0sD2nEeCPOrv-sXwSpQ" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_56l0sT2nEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_56lNoT2nEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_56lNoj2nEeCPOrv-sXwSpQ" points="[0, 22, -125, 30]$[0, 31, -125, 39]$[125, 31, 0, 39]$[125, 14, 0, 22]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6aSocD2nEeCPOrv-sXwSpQ" type="4001" element="_6aKsoD2nEeCPOrv-sXwSpQ" source="_56YZUD2nEeCPOrv-sXwSpQ" target="_-BPhAD2nEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6aSocz2nEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6aSodD2nEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_6aTPgD2nEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6aTPgT2nEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6aSocT2nEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6aSocj2nEeCPOrv-sXwSpQ" points="[-15, -7, 312, 153]$[-327, -160, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7eVfYD2nEeCPOrv-sXwSpQ" type="4001" element="_7eNjkD2nEeCPOrv-sXwSpQ" source="_56YZUD2nEeCPOrv-sXwSpQ" target="_-dwd4D2nEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7eVfYz2nEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7eWGcD2nEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_7eWGcT2nEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7eWGcj2nEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7eVfYT2nEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7eVfYj2nEeCPOrv-sXwSpQ" points="[-15, -7, 312, 153]$[-327, -160, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DV2OMD2oEeCPOrv-sXwSpQ" type="4001" element="_DVtEQD2oEeCPOrv-sXwSpQ" source="_-BPhAD2nEeCPOrv-sXwSpQ" target="_9bWTwD2pEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DV2OMz2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DV2OND2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_DV2ONT2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DV21QD2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DV2OMT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DV2OMj2oEeCPOrv-sXwSpQ" points="[-18, -4, 405, 94]$[-423, -98, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EMoFMD2oEeCPOrv-sXwSpQ" type="4001" element="_EMfiUD2oEeCPOrv-sXwSpQ" source="_-BPhAD2nEeCPOrv-sXwSpQ" target="__bsa4D2pEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EMosQD2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EMosQT2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_EMosQj2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EMosQz2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EMoFMT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EMoFMj2oEeCPOrv-sXwSpQ" points="[0, 22, -269, -20]$[0, 61, -269, 19]$[219, 61, -50, 19]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JB81YD2oEeCPOrv-sXwSpQ" type="4001" element="_JB0SgD2oEeCPOrv-sXwSpQ" source="_-BPhAD2nEeCPOrv-sXwSpQ" target="_IAL2YD2oEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JB9ccD2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JB9ccT2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_JB9ccj2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JB9ccz2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JB81YT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JB81Yj2oEeCPOrv-sXwSpQ" points="[-8, -14, -412, -8]$[-8, -36, -412, -30]$[390, -36, -14, -30]$[390, -13, -14, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JB_RoD2oEeCPOrv-sXwSpQ" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JwvOAD2oEeCPOrv-sXwSpQ" type="4001" element="_Jwk18D2oEeCPOrv-sXwSpQ" source="_9bWTwD2pEeCPOrv-sXwSpQ" target="_IAL2YD2oEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Jwv1ED2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Jwv1ET2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_Jwv1Ej2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Jwv1Ez2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JwvOAT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JwvOAj2oEeCPOrv-sXwSpQ" points="[0, 1, -209, 5]$[195, 3, -14, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JwyRUD2oEeCPOrv-sXwSpQ" id="(1.0,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KQSQwD2oEeCPOrv-sXwSpQ" type="4001" element="_KQHRoD2oEeCPOrv-sXwSpQ" source="__bsa4D2pEeCPOrv-sXwSpQ" target="_IAL2YD2oEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KQS30D2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KQS30T2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_KQS30j2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KQS30z2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KQSQwT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KQSQwj2oEeCPOrv-sXwSpQ" points="[0, 0, -146, 74]$[115, 0, -31, 74]$[115, -11, -31, 63]$[146, -11, 0, 63]$[146, -52, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KQVUED2oEeCPOrv-sXwSpQ" id="(1.0,0.58)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hGBSYD2oEeCPOrv-sXwSpQ" type="4001" element="_hF7LwD2oEeCPOrv-sXwSpQ" source="_IAL2YD2oEeCPOrv-sXwSpQ" target="_cOlpYD2oEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hGBSYz2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hGBSZD2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_hGB5cD2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hGB5cT2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hGBSYT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hGBSYj2oEeCPOrv-sXwSpQ" points="[-8, -2, -54, -11]$[45, 8, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hGDuoD2oEeCPOrv-sXwSpQ" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hGDuoT2oEeCPOrv-sXwSpQ" id="(0.3023255813953488,0.20930232558139536)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iKFXcD2oEeCPOrv-sXwSpQ" type="4001" element="_iJ_34D2oEeCPOrv-sXwSpQ" source="_cOlpYD2oEeCPOrv-sXwSpQ" target="_5FrQ0D2lEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iKF-gT2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iKF-gj2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_iKF-gz2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iKF-hD2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iKFXcT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iKF-gD2oEeCPOrv-sXwSpQ" points="[-2, -7, -9, -56]$[8, 24, 1, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iKIawD2oEeCPOrv-sXwSpQ" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mhCwoD2oEeCPOrv-sXwSpQ" type="4001" element="_mg_GQD2oEeCPOrv-sXwSpQ" source="_-dwd4D2nEeCPOrv-sXwSpQ" target="_BwRsoD2qEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mhDXsD2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mhDXsT2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_mhDXsj2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mhDXsz2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mhCwoT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mhCwoj2oEeCPOrv-sXwSpQ" points="[-14, -8, 367, 210]$[-381, -218, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_n7y3YD2oEeCPOrv-sXwSpQ" type="4001" element="_n7q7kD2oEeCPOrv-sXwSpQ" source="_-dwd4D2nEeCPOrv-sXwSpQ" target="_oca4MD2oEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_n7zecD2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_n7zecT2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_n7zecj2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_n7zecz2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_n7y3YT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_n7y3Yj2oEeCPOrv-sXwSpQ" points="[0, 22, -340, -21]$[0, 70, -340, 27]$[340, 70, 0, 27]$[340, 65, 0, 22]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pP6xsD2oEeCPOrv-sXwSpQ" type="4001" element="_pP0EAD2oEeCPOrv-sXwSpQ" source="_oca4MD2oEeCPOrv-sXwSpQ" target="_cOlpYD2oEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pP7YwD2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pP7YwT2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_pP7Ywj2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pP7Ywz2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pP6xsT2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pP6xsj2oEeCPOrv-sXwSpQ" points="[-10, -20, -112, 90]$[81, -110, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pP9N8D2oEeCPOrv-sXwSpQ" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qAJ70D2oEeCPOrv-sXwSpQ" type="4001" element="_qAD1MD2oEeCPOrv-sXwSpQ" source="_BwRsoD2qEeCPOrv-sXwSpQ" target="_oca4MD2oEeCPOrv-sXwSpQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qAKi4D2oEeCPOrv-sXwSpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qAKi4T2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <children xmi:type="notation:DecorationNode" xmi:id="_qAKi4j2oEeCPOrv-sXwSpQ" visible="false" type="6002">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qAKi4z2oEeCPOrv-sXwSpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qAJ70T2oEeCPOrv-sXwSpQ" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qAJ70j2oEeCPOrv-sXwSpQ" points="[0, 0, -200, -24]$[199, 24, -1, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qAM_ID2oEeCPOrv-sXwSpQ" id="(1.0,0.62)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qAM_IT2oEeCPOrv-sXwSpQ" id="(0.6744186046511628,0.16279069767441862)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
