<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_KTMAAPtMEeGd6Ji6z6XNAg" name="TestSkipForms" bonitaVersion="6.0.0" bonitaModelVersion="6.0.0">
    <elements xmi:type="process:Pool" xmi:id="_KVVVEPtMEeGd6Ji6z6XNAg" name="testSkipForms" welcomePageInternal="false" basedOnLookAndFeel="Default Application" entryPageFlowType="SKIP">
      <elements xmi:type="process:Task" xmi:id="_KVno8PtMEeGd6Ji6z6XNAg" name="Step1" incoming="_KV4usPtMEeGd6Ji6z6XNAg" entryPageFlowType="SKIP" actor="_KVcCwPtMEeGd6Ji6z6XNAg">
        <viewForm xmi:type="form:ViewForm" xmi:id="_nhJLIPtQEeGd6Ji6z6XNAg" name="viewFormStep" nLine="3">
          <widgets xmi:type="form:TextFormField" xmi:id="_rtwVgPtQEeGd6Ji6z6XNAg" name="Text_field1">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_rt44YftQEeGd6Ji6z6XNAg"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_r_F9IPtQEeGd6Ji6z6XNAg" name="testData" content="testData" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_sUBEQPtQEeGd6Ji6z6XNAg" name="testData" dataType="_KTMnFftMEeGd6Ji6z6XNAg">
                <defaultValue xmi:type="expression:Expression" xmi:id="_sUBEQftQEeGd6Ji6z6XNAg"/>
              </referencedElements>
            </inputExpression>
            <displayLabel xmi:type="expression:Expression" xmi:id="_rt3DMPtQEeGd6Ji6z6XNAg" name="Text_field1" content="Text_field1" returnTypeFixed="true"/>
            <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_r-I64PtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_r9MfsPtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          </widgets>
          <pageLabel xmi:type="expression:Expression" xmi:id="_nhJLIftQEeGd6Ji6z6XNAg" name="viewFormStep" content="viewFormStep" returnTypeFixed="true"/>
        </viewForm>
        <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ldppYPtQEeGd6Ji6z6XNAg" content=""/>
        <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_NyG98PtMEeGd6Ji6z6XNAg" content=""/>
        <confirmationMessage xmi:type="expression:Expression" xmi:id="_w3ZI0PtQEeGd6Ji6z6XNAg"/>
      </elements>
      <elements xmi:type="process:StartEvent" xmi:id="_KVzPIPtMEeGd6Ji6z6XNAg" name="Start1" outgoing="_KV4usPtMEeGd6Ji6z6XNAg"/>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_KWz7wPtMEeGd6Ji6z6XNAg" path="_KVVVEPtMEeGd6Ji6z6XNAg/application/application"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_KWz7w_tMEeGd6Ji6z6XNAg" path="_KVVVEPtMEeGd6Ji6z6XNAg/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_KWz7wftMEeGd6Ji6z6XNAg" path="_KVVVEPtMEeGd6Ji6z6XNAg/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_KWz7xPtMEeGd6Ji6z6XNAg" path="_KVVVEPtMEeGd6Ji6z6XNAg/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_KWz7wvtMEeGd6Ji6z6XNAg" path="_KVVVEPtMEeGd6Ji6z6XNAg/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_qjorwPtQEeGd6Ji6z6XNAg" name="testData" dataType="_KTMnFftMEeGd6Ji6z6XNAg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_qjorwftQEeGd6Ji6z6XNAg"/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_KVVVEftMEeGd6Ji6z6XNAg" content=""/>
      <recapForms xmi:type="form:ViewForm" xmi:id="_01O3YPtQEeGd6Ji6z6XNAg" name="overviewForm" nLine="3">
        <widgets xmi:type="form:TextFormField" xmi:id="_01O3YftQEeGd6Ji6z6XNAg" name="testData">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_01O3YvtQEeGd6Ji6z6XNAg"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_01O3Y_tQEeGd6Ji6z6XNAg" name="testData" content="testData" type="TYPE_VARIABLE">
            <referencedElements xmi:type="process:Data" xmi:id="_01O3ZPtQEeGd6Ji6z6XNAg" name="testData" dataType="_KTMnFftMEeGd6Ji6z6XNAg">
              <defaultValue xmi:type="expression:Expression" xmi:id="_01O3ZftQEeGd6Ji6z6XNAg"/>
            </referencedElements>
          </inputExpression>
          <action xmi:type="expression:Operation" xmi:id="_01O3ZvtQEeGd6Ji6z6XNAg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_01O3Z_tQEeGd6Ji6z6XNAg" name="testData" content="testData" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_01O3aPtQEeGd6Ji6z6XNAg" name="testData" dataType="_KTMnFftMEeGd6Ji6z6XNAg">
                <defaultValue xmi:type="expression:Expression" xmi:id="_01O3aftQEeGd6Ji6z6XNAg"/>
              </referencedElements>
            </leftOperand>
            <operator xmi:type="expression:Operator" xmi:id="_01O3avtQEeGd6Ji6z6XNAg" type="ASSIGNMENT"/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_01O3a_tQEeGd6Ji6z6XNAg" name="field_testData" content="field_testData" type="TYPE_INPUT">
              <referencedElements xmi:type="form:TextFormField" xmi:id="_01O3bPtQEeGd6Ji6z6XNAg" name="testData">
                <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_01O3bftQEeGd6Ji6z6XNAg"/>
                <inputExpression xmi:type="expression:Expression" xmi:id="_01O3bvtQEeGd6Ji6z6XNAg" name="testData" content="testData" type="TYPE_VARIABLE">
                  <referencedElements xmi:type="process:Data" xmi:id="_01O3b_tQEeGd6Ji6z6XNAg" name="testData" dataType="_KTMnFftMEeGd6Ji6z6XNAg">
                    <defaultValue xmi:type="expression:Expression" xmi:id="_01O3cPtQEeGd6Ji6z6XNAg"/>
                  </referencedElements>
                </inputExpression>
                <displayLabel xmi:type="expression:Expression" xmi:id="_01O3cftQEeGd6Ji6z6XNAg" name="testData" content="testData"/>
              </referencedElements>
            </rightOperand>
          </action>
          <displayLabel xmi:type="expression:Expression" xmi:id="_01O3cvtQEeGd6Ji6z6XNAg" name="testData" content="testData"/>
          <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_2KyVEPtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_2JX_0PtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:type="expression:Expression" xmi:id="_01O3c_tQEeGd6Ji6z6XNAg" name="overviewForm" content="overviewForm" returnTypeFixed="true"/>
      </recapForms>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_xy7kAPtQEeGd6Ji6z6XNAg" content=""/>
      <viewForm xmi:type="form:ViewForm" xmi:id="_e9iLUPtQEeGd6Ji6z6XNAg" name="viewFormInst" nLine="3">
        <widgets xmi:type="form:TextFormField" xmi:id="_fyyYUPtQEeGd6Ji6z6XNAg" name="testData">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_fy00kPtQEeGd6Ji6z6XNAg"/>
          <inputExpression xmi:type="expression:Expression" xmi:id="_iKxjYPtQEeGd6Ji6z6XNAg" content=""/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_fyy_YPtQEeGd6Ji6z6XNAg" name="testData" content="testData" returnTypeFixed="true"/>
          <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_iJ5ZoPtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_iIo1YPtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:type="expression:Expression" xmi:id="_e9iLUftQEeGd6Ji6z6XNAg" name="viewFormInst" content="viewFormInst" returnTypeFixed="true"/>
      </viewForm>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_dCtdYPtQEeGd6Ji6z6XNAg" content=""/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KV4usPtMEeGd6Ji6z6XNAg" source="_KVzPIPtMEeGd6Ji6z6XNAg" target="_KVno8PtMEeGd6Ji6z6XNAg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KV4usftMEeGd6Ji6z6XNAg"/>
        <condition xmi:type="expression:Expression" xmi:id="_KV4usvtMEeGd6Ji6z6XNAg" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_KVcCwPtMEeGd6Ji6z6XNAg" name="Employee"/>
      <actors xmi:type="process:Actor" xmi:id="_KVcCwftMEeGd6Ji6z6XNAg" name="Finance"/>
      <actors xmi:type="process:Actor" xmi:id="_KVcCwvtMEeGd6Ji6z6XNAg" name="Human resource" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_KVcCw_tMEeGd6Ji6z6XNAg" name="Infrastructure"/>
      <actors xmi:type="process:Actor" xmi:id="_KVcCxPtMEeGd6Ji6z6XNAg" name="Sales"/>
      <actors xmi:type="process:Actor" xmi:id="_KVcCxftMEeGd6Ji6z6XNAg" name="Production"/>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_KTMAAftMEeGd6Ji6z6XNAg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_KTMnEPtMEeGd6Ji6z6XNAg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_KTMnEftMEeGd6Ji6z6XNAg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_KTMnEvtMEeGd6Ji6z6XNAg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_KTMnE_tMEeGd6Ji6z6XNAg" name="Double"/>
    <datatypes xmi:type="process:FloatType" xmi:id="_KTMnFPtMEeGd6Ji6z6XNAg" name="Decimal"/>
    <datatypes xmi:type="process:StringType" xmi:id="_KTMnFftMEeGd6Ji6z6XNAg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_KTMnFvtMEeGd6Ji6z6XNAg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_KTMnF_tMEeGd6Ji6z6XNAg" name="XML"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_KTMnGPtMEeGd6Ji6z6XNAg" type="Process" element="_KTMAAPtMEeGd6Ji6z6XNAg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_KVWjMPtMEeGd6Ji6z6XNAg" type="2007" element="_KVVVEPtMEeGd6Ji6z6XNAg">
      <children xmi:type="notation:DecorationNode" xmi:id="_KVXKQPtMEeGd6Ji6z6XNAg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_KVXKQftMEeGd6Ji6z6XNAg" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_KVoQAPtMEeGd6Ji6z6XNAg" type="3005" element="_KVno8PtMEeGd6Ji6z6XNAg" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_KVo3EPtMEeGd6Ji6z6XNAg" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KVoQAftMEeGd6Ji6z6XNAg" x="110" y="55"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_KVz2MPtMEeGd6Ji6z6XNAg" type="3002" element="_KVzPIPtMEeGd6Ji6z6XNAg" fontName="Lucida Grande">
          <children xmi:type="notation:DecorationNode" xmi:id="_KV0dQPtMEeGd6Ji6z6XNAg" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_KV0dQftMEeGd6Ji6z6XNAg" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KVz2MftMEeGd6Ji6z6XNAg" x="40" y="65"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_KVWjMftMEeGd6Ji6z6XNAg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_KVWjMvtMEeGd6Ji6z6XNAg" fontName="Lucida Grande"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_KVWjM_tMEeGd6Ji6z6XNAg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_KVXKQvtMEeGd6Ji6z6XNAg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KVWjNPtMEeGd6Ji6z6XNAg"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_KTMnGftMEeGd6Ji6z6XNAg"/>
    <edges xmi:type="notation:Connector" xmi:id="_KV5VwPtMEeGd6Ji6z6XNAg" type="4001" element="_KV4usPtMEeGd6Ji6z6XNAg" source="_KVz2MPtMEeGd6Ji6z6XNAg" target="_KVoQAPtMEeGd6Ji6z6XNAg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KV580PtMEeGd6Ji6z6XNAg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KV580ftMEeGd6Ji6z6XNAg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KV5VwftMEeGd6Ji6z6XNAg" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KV5VwvtMEeGd6Ji6z6XNAg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_e-AscPtQEeGd6Ji6z6XNAg" type="Form" element="_e9iLUPtQEeGd6Ji6z6XNAg" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_fy0NgPtQEeGd6Ji6z6XNAg" type="2120" element="_fyyYUPtQEeGd6Ji6z6XNAg" fontName="Lucida Grande">
      <children xmi:type="notation:DecorationNode" xmi:id="_fy0NgvtQEeGd6Ji6z6XNAg" type="5157"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fy0NgftQEeGd6Ji6z6XNAg"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_e-AscftQEeGd6Ji6z6XNAg"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_nho6YPtQEeGd6Ji6z6XNAg" type="Form" element="_nhJLIPtQEeGd6Ji6z6XNAg" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_rt4RUPtQEeGd6Ji6z6XNAg" type="2120" element="_rtwVgPtQEeGd6Ji6z6XNAg" fontName="Lucida Grande">
      <children xmi:type="notation:DecorationNode" xmi:id="_rt44YPtQEeGd6Ji6z6XNAg" type="5157"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rt4RUftQEeGd6Ji6z6XNAg"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_nho6YftQEeGd6Ji6z6XNAg"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_01zfIPtQEeGd6Ji6z6XNAg" type="Form" element="_01O3YPtQEeGd6Ji6z6XNAg" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_01zfIftQEeGd6Ji6z6XNAg"/>
  </notation:Diagram>
</xmi:XMI>
