<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_YfdRcPtMEeGd6Ji6z6XNAg" name="TestVariableBoundDiagram" bonitaVersion="6.0.0" bonitaModelVersion="6.0.0">
    <elements xmi:type="process:Pool" xmi:id="_YhLIsPtMEeGd6Ji6z6XNAg" name="TestVariableBound" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Task" xmi:id="_YhZyMPtMEeGd6Ji6z6XNAg" name="Step1" incoming="_YhmmgPtMEeGd6Ji6z6XNAg" actor="_YhRPUPtMEeGd6Ji6z6XNAg">
        <data xmi:type="process:Data" xmi:id="_s2s3YPtMEeGd6Ji6z6XNAg" name="booleanActivity" dataType="_YfdRcftMEeGd6Ji6z6XNAg">
          <defaultValue xmi:type="expression:Expression" xmi:id="_s2tecPtMEeGd6Ji6z6XNAg" content=""/>
        </data>
        <data xmi:type="process:Data" xmi:id="_tiMZgPtOEeGd6Ji6z6XNAg" name="dateActivity" dataType="_YfdRcvtMEeGd6Ji6z6XNAg">
          <defaultValue xmi:type="expression:Expression" xmi:id="_tiMZgftOEeGd6Ji6z6XNAg" content=""/>
        </data>
        <data xmi:type="process:Data" xmi:id="_uvBD4PtMEeGd6Ji6z6XNAg" name="textActivity" dataType="_Yfd4gvtMEeGd6Ji6z6XNAg">
          <defaultValue xmi:type="expression:Expression" xmi:id="_uvBD4ftMEeGd6Ji6z6XNAg"/>
        </data>
        <form xmi:type="form:Form" xmi:id="_zs_u4PtOEeGd6Ji6z6XNAg" name="Step1" nLine="5">
          <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_zs_u4ftOEeGd6Ji6z6XNAg" name="booleanActivity">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_zs_u4vtOEeGd6Ji6z6XNAg"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_zs_u4_tOEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_zs_u5PtOEeGd6Ji6z6XNAg" name="booleanActivity" dataType="_YfdRcftMEeGd6Ji6z6XNAg">
                <defaultValue xmi:type="expression:Expression" xmi:id="_zs_u5ftOEeGd6Ji6z6XNAg" content=""/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_zs_u5vtOEeGd6Ji6z6XNAg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_zs_u5_tOEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="process:Data" xmi:id="_zs_u6PtOEeGd6Ji6z6XNAg" name="booleanActivity" dataType="_YfdRcftMEeGd6Ji6z6XNAg">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_zs_u6ftOEeGd6Ji6z6XNAg" content=""/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_zs_u6vtOEeGd6Ji6z6XNAg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_zs_u6_tOEeGd6Ji6z6XNAg" name="field_booleanActivity" content="field_booleanActivity" type="TYPE_INPUT" returnType="java.lang.Boolean">
                <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_zs_u7PtOEeGd6Ji6z6XNAg" name="booleanActivity">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_zs_u7ftOEeGd6Ji6z6XNAg"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_zs_u7vtOEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                    <referencedElements xmi:type="process:Data" xmi:id="_zs_u7_tOEeGd6Ji6z6XNAg" name="booleanActivity" dataType="_YfdRcftMEeGd6Ji6z6XNAg">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_zs_u8PtOEeGd6Ji6z6XNAg" content=""/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_zs_u8ftOEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_zs_u8vtOEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity"/>
          </widgets>
          <widgets xmi:type="form:FileWidget" xmi:id="_zs_u8_tOEeGd6Ji6z6XNAg" name="myDocument" document="_h5os4PtMEeGd6Ji6z6XNAg" inputType="Document" outputDocumentName="myDocument">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_zs_u9PtOEeGd6Ji6z6XNAg" line="1"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_zs_u9ftOEeGd6Ji6z6XNAg" name="myDocument" content="myDocument"/>
          </widgets>
          <widgets xmi:type="form:DateFormField" xmi:id="_zs_u9vtOEeGd6Ji6z6XNAg" name="dateActivity">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_zs_u9_tOEeGd6Ji6z6XNAg" line="2"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_zs_u-PtOEeGd6Ji6z6XNAg" name="dateActivity" content="dateActivity" type="TYPE_VARIABLE" returnType="java.util.Date">
              <referencedElements xmi:type="process:Data" xmi:id="_zs_u-ftOEeGd6Ji6z6XNAg" name="dateActivity" dataType="_YfdRcvtMEeGd6Ji6z6XNAg">
                <defaultValue xmi:type="expression:Expression" xmi:id="_zs_u-vtOEeGd6Ji6z6XNAg" content=""/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_zs_u-_tOEeGd6Ji6z6XNAg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_zs_u_PtOEeGd6Ji6z6XNAg" name="dateActivity" content="dateActivity" type="TYPE_VARIABLE" returnType="java.util.Date">
                <referencedElements xmi:type="process:Data" xmi:id="_zs_u_ftOEeGd6Ji6z6XNAg" name="dateActivity" dataType="_YfdRcvtMEeGd6Ji6z6XNAg">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_zs_u_vtOEeGd6Ji6z6XNAg" content=""/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_zs_u__tOEeGd6Ji6z6XNAg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_zs_vAPtOEeGd6Ji6z6XNAg" name="field_dateActivity" content="field_dateActivity" type="TYPE_INPUT" returnType="java.util.Date">
                <referencedElements xmi:type="form:DateFormField" xmi:id="_zs_vAftOEeGd6Ji6z6XNAg" name="dateActivity">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_zs_vAvtOEeGd6Ji6z6XNAg" line="2"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_zs_vA_tOEeGd6Ji6z6XNAg" name="dateActivity" content="dateActivity" type="TYPE_VARIABLE" returnType="java.util.Date">
                    <referencedElements xmi:type="process:Data" xmi:id="_zs_vBPtOEeGd6Ji6z6XNAg" name="dateActivity" dataType="_YfdRcvtMEeGd6Ji6z6XNAg">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_zs_vBftOEeGd6Ji6z6XNAg" content=""/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_zs_vBvtOEeGd6Ji6z6XNAg" name="dateActivity" content="dateActivity"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_zs_vB_tOEeGd6Ji6z6XNAg" name="dateActivity" content="dateActivity"/>
          </widgets>
          <widgets xmi:type="form:TextFormField" xmi:id="_zs_vCPtOEeGd6Ji6z6XNAg" name="textActivity">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_zs_vCftOEeGd6Ji6z6XNAg" line="3"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_zs_vCvtOEeGd6Ji6z6XNAg" name="textActivity" content="textActivity" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_zs_vC_tOEeGd6Ji6z6XNAg" name="textActivity" dataType="_Yfd4gvtMEeGd6Ji6z6XNAg">
                <defaultValue xmi:type="expression:Expression" xmi:id="_zs_vDPtOEeGd6Ji6z6XNAg"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_zs_vDftOEeGd6Ji6z6XNAg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_zs_vDvtOEeGd6Ji6z6XNAg" name="textActivity" content="textActivity" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_zs_vD_tOEeGd6Ji6z6XNAg" name="textActivity" dataType="_Yfd4gvtMEeGd6Ji6z6XNAg">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_zs_vEPtOEeGd6Ji6z6XNAg"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_zs_vEftOEeGd6Ji6z6XNAg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_zs_vEvtOEeGd6Ji6z6XNAg" name="field_textActivity" content="field_textActivity" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_zs_vE_tOEeGd6Ji6z6XNAg" name="textActivity">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_zs_vFPtOEeGd6Ji6z6XNAg" line="3"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_zs_vFftOEeGd6Ji6z6XNAg" name="textActivity" content="textActivity" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_zs_vFvtOEeGd6Ji6z6XNAg" name="textActivity" dataType="_Yfd4gvtMEeGd6Ji6z6XNAg">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_zs_vF_tOEeGd6Ji6z6XNAg"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_zs_vGPtOEeGd6Ji6z6XNAg" name="textActivity" content="textActivity"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_zs_vGftOEeGd6Ji6z6XNAg" name="textActivity" content="textActivity"/>
          </widgets>
          <widgets xmi:type="form:SubmitFormButton" xmi:id="_ztAV8PtOEeGd6Ji6z6XNAg" name="Submit1">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_ztAV8ftOEeGd6Ji6z6XNAg" line="4"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_ztAV8vtOEeGd6Ji6z6XNAg" name="Submit1" content="Submit1"/>
          </widgets>
          <pageLabel xmi:type="expression:Expression" xmi:id="_ztAV8_tOEeGd6Ji6z6XNAg" name="Step1" content="Step1" returnTypeFixed="true"/>
        </form>
        <form xmi:type="form:Form" xmi:id="_60I7QPtPEeGd6Ji6z6XNAg" name="Step2" nColumn="2">
          <widgets xmi:type="form:CheckBoxSingleFormField" xmi:id="_60I7QftPEeGd6Ji6z6XNAg" name="booleanActivityReadOnly" readOnly="true">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_60I7QvtPEeGd6Ji6z6XNAg"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_60I7Q_tPEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_60I7RPtPEeGd6Ji6z6XNAg" name="booleanActivity" dataType="_YfdRcftMEeGd6Ji6z6XNAg">
                <defaultValue xmi:type="expression:Expression" xmi:id="_60I7RftPEeGd6Ji6z6XNAg" content=""/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_60I7RvtPEeGd6Ji6z6XNAg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_60I7R_tPEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                <referencedElements xmi:type="process:Data" xmi:id="_60I7SPtPEeGd6Ji6z6XNAg" name="booleanActivity" dataType="_YfdRcftMEeGd6Ji6z6XNAg">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_60I7SftPEeGd6Ji6z6XNAg" content=""/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_60I7SvtPEeGd6Ji6z6XNAg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_60I7S_tPEeGd6Ji6z6XNAg" name="field_booleanActivity" content="field_booleanActivity" type="TYPE_INPUT" returnType="java.lang.Boolean">
                <referencedElements xmi:type="form:CheckBoxSingleFormField" xmi:id="_60I7TPtPEeGd6Ji6z6XNAg" name="booleanActivity">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_60I7TftPEeGd6Ji6z6XNAg" horizontalSpan="2"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_60I7TvtPEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
                    <referencedElements xmi:type="process:Data" xmi:id="_60I7T_tPEeGd6Ji6z6XNAg" name="booleanActivity" dataType="_YfdRcftMEeGd6Ji6z6XNAg">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_60JiUPtPEeGd6Ji6z6XNAg" content=""/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_60JiUftPEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_60JiUvtPEeGd6Ji6z6XNAg" name="booleanActivity" content="booleanActivity"/>
            <injectWidgetScript xmi:type="expression:Expression" xmi:id="_n3eVkftSEeGRJP-lyNjojw" content=""/>
          </widgets>
          <widgets xmi:type="form:FileWidget" xmi:id="_60JiU_tPEeGd6Ji6z6XNAg" name="myDocumentDownloadOnly" downloadOnly="true" document="_h5os4PtMEeGd6Ji6z6XNAg" inputType="Document" outputDocumentName="myDocument">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_60JiVPtPEeGd6Ji6z6XNAg" line="1" horizontalSpan="2"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_60JiVftPEeGd6Ji6z6XNAg" name="myDocument" content="myDocument"/>
            <injectWidgetScript xmi:type="expression:Expression" xmi:id="_o_HTEPtSEeGRJP-lyNjojw" content=""/>
            <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_GVXiwPtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_GTpEcPtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          </widgets>
          <widgets xmi:type="form:PreviousFormButton" xmi:id="_60JievtPEeGd6Ji6z6XNAg" name="Previous1">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_60Jie_tPEeGd6Ji6z6XNAg" line="3"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_60JifPtPEeGd6Ji6z6XNAg" name="Previous1" content="Previous1"/>
          </widgets>
          <widgets xmi:type="form:SubmitFormButton" xmi:id="_60JifftPEeGd6Ji6z6XNAg" name="Submit2">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_60JifvtPEeGd6Ji6z6XNAg" line="3" column="1"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_60Jif_tPEeGd6Ji6z6XNAg" name="Submit2" content="Submit2"/>
          </widgets>
          <widgets xmi:type="form:MessageInfo" xmi:id="_9N62EPtPEeGd6Ji6z6XNAg" name="Message1">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_9N9SU_tPEeGd6Ji6z6XNAg" column="1"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_C7L64PtQEeGd6Ji6z6XNAg" name="init" content="&quot;script for message&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_9N7dIPtPEeGd6Ji6z6XNAg" name="Message1" content="Message1" returnTypeFixed="true"/>
            <injectWidgetScript xmi:type="expression:Expression" xmi:id="_oYxr0PtSEeGRJP-lyNjojw" content=""/>
          </widgets>
          <widgets xmi:type="form:TextInfo" xmi:id="_AQw8APtQEeGd6Ji6z6XNAg" name="textActivityNotEditable">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_60JiaftPEeGd6Ji6z6XNAg" line="2" horizontalSpan="2"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_60JiavtPEeGd6Ji6z6XNAg" name="textActivity" content="textActivity" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_60Jia_tPEeGd6Ji6z6XNAg" name="textActivity" dataType="_Yfd4gvtMEeGd6Ji6z6XNAg">
                <defaultValue xmi:type="expression:Expression" xmi:id="_60JibPtPEeGd6Ji6z6XNAg"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_60JibftPEeGd6Ji6z6XNAg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_60JibvtPEeGd6Ji6z6XNAg" name="textActivity" content="textActivity" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_60Jib_tPEeGd6Ji6z6XNAg" name="textActivity" dataType="_Yfd4gvtMEeGd6Ji6z6XNAg">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_60JicPtPEeGd6Ji6z6XNAg"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_60JicftPEeGd6Ji6z6XNAg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_60JicvtPEeGd6Ji6z6XNAg" name="field_textActivity" content="field_textActivity" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_60Jic_tPEeGd6Ji6z6XNAg" name="textActivity">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_60JidPtPEeGd6Ji6z6XNAg" line="3" horizontalSpan="2"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_60JidftPEeGd6Ji6z6XNAg" name="textActivity" content="textActivity" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_60JidvtPEeGd6Ji6z6XNAg" name="textActivity" dataType="_Yfd4gvtMEeGd6Ji6z6XNAg">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_60Jid_tPEeGd6Ji6z6XNAg"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_60JiePtPEeGd6Ji6z6XNAg" name="textActivity" content="textActivity"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_60JieftPEeGd6Ji6z6XNAg" name="textActivity" content="textActivity"/>
            <injectWidgetScript xmi:type="expression:Expression" xmi:id="_qN-58PtSEeGRJP-lyNjojw" content=""/>
            <maxNumberOfDuplication xmi:type="expression:Expression" xmi:id="_I8QFcPtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
            <minNumberOfDuplication xmi:type="expression:Expression" xmi:id="_I6mfoPtQEeGd6Ji6z6XNAg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          </widgets>
          <pageLabel xmi:type="expression:Expression" xmi:id="_60JigPtPEeGd6Ji6z6XNAg" name="Step2" content="Step2" returnTypeFixed="true"/>
        </form>
        <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_reixoPtMEeGd6Ji6z6XNAg" content=""/>
      </elements>
      <elements xmi:type="process:StartEvent" xmi:id="_YhhG8PtMEeGd6Ji6z6XNAg" name="Start1" outgoing="_YhmmgPtMEeGd6Ji6z6XNAg"/>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_YiNDcPtMEeGd6Ji6z6XNAg" path="_YhLIsPtMEeGd6Ji6z6XNAg/application/application"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_YiNqgPtMEeGd6Ji6z6XNAg" path="_YhLIsPtMEeGd6Ji6z6XNAg/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_YiNDcftMEeGd6Ji6z6XNAg" path="_YhLIsPtMEeGd6Ji6z6XNAg/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_YiNqgftMEeGd6Ji6z6XNAg" path="_YhLIsPtMEeGd6Ji6z6XNAg/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_YiNDcvtMEeGd6Ji6z6XNAg" path="_YhLIsPtMEeGd6Ji6z6XNAg/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_nwX2wPtMEeGd6Ji6z6XNAg" name="booleanProcess" dataType="_YfdRcftMEeGd6Ji6z6XNAg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_nwX2wftMEeGd6Ji6z6XNAg" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_pflxoPtMEeGd6Ji6z6XNAg" name="dateProcess" dataType="_YfdRcvtMEeGd6Ji6z6XNAg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_pflxoftMEeGd6Ji6z6XNAg" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_qZd_8PtMEeGd6Ji6z6XNAg" name="textProcess" dataType="_Yfd4gvtMEeGd6Ji6z6XNAg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_qZd_8ftMEeGd6Ji6z6XNAg"/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_YhLIsftMEeGd6Ji6z6XNAg" content=""/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YhmmgPtMEeGd6Ji6z6XNAg" source="_YhhG8PtMEeGd6Ji6z6XNAg" target="_YhZyMPtMEeGd6Ji6z6XNAg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YhmmgftMEeGd6Ji6z6XNAg"/>
        <condition xmi:type="expression:Expression" xmi:id="_YhmmgvtMEeGd6Ji6z6XNAg" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_YhRPUPtMEeGd6Ji6z6XNAg" name="Employee"/>
      <actors xmi:type="process:Actor" xmi:id="_YhRPUftMEeGd6Ji6z6XNAg" name="Finance"/>
      <actors xmi:type="process:Actor" xmi:id="_YhRPUvtMEeGd6Ji6z6XNAg" name="Human resource" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_YhRPU_tMEeGd6Ji6z6XNAg" name="Infrastructure"/>
      <actors xmi:type="process:Actor" xmi:id="_YhRPVPtMEeGd6Ji6z6XNAg" name="Sales"/>
      <actors xmi:type="process:Actor" xmi:id="_YhRPVftMEeGd6Ji6z6XNAg" name="Production"/>
      <documents xmi:type="process:Document" xmi:id="_h5os4PtMEeGd6Ji6z6XNAg" name="myDocument">
        <mimeType xmi:type="expression:Expression" xmi:id="_h5os4ftMEeGd6Ji6z6XNAg" name="application/octet-stream" content="application/octet-stream"/>
        <url xmi:type="expression:Expression" xmi:id="_h5os4vtMEeGd6Ji6z6XNAg"/>
      </documents>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_YfdRcftMEeGd6Ji6z6XNAg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_YfdRcvtMEeGd6Ji6z6XNAg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_YfdRc_tMEeGd6Ji6z6XNAg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_YfdRdPtMEeGd6Ji6z6XNAg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Yfd4gPtMEeGd6Ji6z6XNAg" name="Double"/>
    <datatypes xmi:type="process:FloatType" xmi:id="_Yfd4gftMEeGd6Ji6z6XNAg" name="Decimal"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Yfd4gvtMEeGd6Ji6z6XNAg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Yfd4g_tMEeGd6Ji6z6XNAg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Yfd4hPtMEeGd6Ji6z6XNAg" name="XML"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Yfd4hftMEeGd6Ji6z6XNAg" type="Process" element="_YfdRcPtMEeGd6Ji6z6XNAg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_YhMW0PtMEeGd6Ji6z6XNAg" type="2007" element="_YhLIsPtMEeGd6Ji6z6XNAg">
      <children xmi:type="notation:DecorationNode" xmi:id="_YhMW1ftMEeGd6Ji6z6XNAg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_YhM94PtMEeGd6Ji6z6XNAg" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_YhaZQPtMEeGd6Ji6z6XNAg" type="3005" element="_YhZyMPtMEeGd6Ji6z6XNAg" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_YhbAUPtMEeGd6Ji6z6XNAg" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YhaZQftMEeGd6Ji6z6XNAg" x="110" y="55"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_YhhuAPtMEeGd6Ji6z6XNAg" type="3002" element="_YhhG8PtMEeGd6Ji6z6XNAg" fontName="Lucida Grande">
          <children xmi:type="notation:DecorationNode" xmi:id="_YhiVEPtMEeGd6Ji6z6XNAg" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_YhiVEftMEeGd6Ji6z6XNAg" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YhhuAftMEeGd6Ji6z6XNAg" x="40" y="65"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_YhMW0ftMEeGd6Ji6z6XNAg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_YhMW0vtMEeGd6Ji6z6XNAg" fontName="Lucida Grande"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_YhMW0_tMEeGd6Ji6z6XNAg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_YhM94ftMEeGd6Ji6z6XNAg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YhMW1PtMEeGd6Ji6z6XNAg"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Yfd4hvtMEeGd6Ji6z6XNAg"/>
    <edges xmi:type="notation:Connector" xmi:id="_YhnNkPtMEeGd6Ji6z6XNAg" type="4001" element="_YhmmgPtMEeGd6Ji6z6XNAg" source="_YhhuAPtMEeGd6Ji6z6XNAg" target="_YhaZQPtMEeGd6Ji6z6XNAg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Yhn0oPtMEeGd6Ji6z6XNAg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Yhn0oftMEeGd6Ji6z6XNAg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YhnNkftMEeGd6Ji6z6XNAg" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YhnNkvtMEeGd6Ji6z6XNAg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_ncOg0PtOEeGd6Ji6z6XNAg" type="Form" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_ncOg0ftOEeGd6Ji6z6XNAg"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_ztZXgPtOEeGd6Ji6z6XNAg" type="Form" element="_zs_u4PtOEeGd6Ji6z6XNAg" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_ztZXgftOEeGd6Ji6z6XNAg"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_60rGwPtPEeGd6Ji6z6XNAg" type="Form" element="_60I7QPtPEeGd6Ji6z6XNAg" measurementUnit="Pixel">
    <children xmi:type="notation:Shape" xmi:id="_617D8PtPEeGd6Ji6z6XNAg" type="2130" element="_60I7QftPEeGd6Ji6z6XNAg" fontName="Lucida Grande">
      <children xmi:type="notation:DecorationNode" xmi:id="_617D8vtPEeGd6Ji6z6XNAg" type="5148"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_617D8ftPEeGd6Ji6z6XNAg"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_617D8_tPEeGd6Ji6z6XNAg" type="2133" element="_60JiU_tPEeGd6Ji6z6XNAg" fontName="Lucida Grande">
      <children xmi:type="notation:DecorationNode" xmi:id="_617rAPtPEeGd6Ji6z6XNAg" type="5189"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_617D9PtPEeGd6Ji6z6XNAg"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_6185IPtPEeGd6Ji6z6XNAg" type="2128" element="_60JievtPEeGd6Ji6z6XNAg">
      <children xmi:type="notation:DecorationNode" xmi:id="_619gMPtPEeGd6Ji6z6XNAg" type="5162"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_6185IftPEeGd6Ji6z6XNAg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_6185IvtPEeGd6Ji6z6XNAg" fontName="Lucida Grande"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_6185I_tPEeGd6Ji6z6XNAg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6185JPtPEeGd6Ji6z6XNAg"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_619gMftPEeGd6Ji6z6XNAg" type="2126" element="_60JifftPEeGd6Ji6z6XNAg">
      <children xmi:type="notation:DecorationNode" xmi:id="_619gNvtPEeGd6Ji6z6XNAg" type="5160"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_619gMvtPEeGd6Ji6z6XNAg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_619gM_tPEeGd6Ji6z6XNAg" fontName="Lucida Grande"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_619gNPtPEeGd6Ji6z6XNAg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_619gNftPEeGd6Ji6z6XNAg"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_9N9SUPtPEeGd6Ji6z6XNAg" type="2131" element="_9N62EPtPEeGd6Ji6z6XNAg" fontName="Lucida Grande">
      <children xmi:type="notation:DecorationNode" xmi:id="_9N9SUvtPEeGd6Ji6z6XNAg" type="5135"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9N9SUftPEeGd6Ji6z6XNAg"/>
    </children>
    <children xmi:type="notation:Shape" xmi:id="_AQxjEftQEeGd6Ji6z6XNAg" type="2132" element="_AQw8APtQEeGd6Ji6z6XNAg" fontName="Lucida Grande">
      <children xmi:type="notation:DecorationNode" xmi:id="_AQyKIPtQEeGd6Ji6z6XNAg" type="5188"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AQxjEvtQEeGd6Ji6z6XNAg"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_60rGwftPEeGd6Ji6z6XNAg"/>
  </notation:Diagram>
</xmi:XMI>
