<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_fqWZkPtGEeGd6Ji6z6XNAg" name="TestProcessForActions" bonitaVersion="6.0.0" bonitaModelVersion="6.0.0">
    <elements xmi:type="process:Pool" xmi:id="_f7aUYPtGEeGd6Ji6z6XNAg" name="TestProcessForActions" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Task" xmi:id="_gaI3wPtGEeGd6Ji6z6XNAg" name="Step1" incoming="_gj4CkPtGEeGd6Ji6z6XNAg" actor="_gXvrEPtGEeGd6Ji6z6XNAg">
        <form xmi:type="form:Form" xmi:id="_fQddcPtHEeGd6Ji6z6XNAg" name="Step1" nLine="3">
          <widgets xmi:type="form:TextFormField" xmi:id="_fQddcftHEeGd6Ji6z6XNAg" name="plop">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_fQeEgPtHEeGd6Ji6z6XNAg"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_fQeEgftHEeGd6Ji6z6XNAg" name="plop" content="plop" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_fQeEgvtHEeGd6Ji6z6XNAg" name="plop" dataType="_fqWZl_tGEeGd6Ji6z6XNAg">
                <defaultValue xmi:type="expression:Expression" xmi:id="_fQeEg_tHEeGd6Ji6z6XNAg" content=""/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_fQeEhPtHEeGd6Ji6z6XNAg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_fQeEhftHEeGd6Ji6z6XNAg" name="plop" content="plop" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_fQeEhvtHEeGd6Ji6z6XNAg" name="plop" dataType="_fqWZl_tGEeGd6Ji6z6XNAg">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_fQeEh_tHEeGd6Ji6z6XNAg" content=""/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_fQeEiPtHEeGd6Ji6z6XNAg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_fQeEiftHEeGd6Ji6z6XNAg" name="field_plop" content="field_plop" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_fQeEivtHEeGd6Ji6z6XNAg" name="plop">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_fQeEi_tHEeGd6Ji6z6XNAg"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_fQeEjPtHEeGd6Ji6z6XNAg" name="plop" content="plop" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_fQeEjftHEeGd6Ji6z6XNAg" name="plop" dataType="_fqWZl_tGEeGd6Ji6z6XNAg">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_fQeEjvtHEeGd6Ji6z6XNAg" content=""/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_fQeEj_tHEeGd6Ji6z6XNAg" name="plop" content="plop"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_fQeEkPtHEeGd6Ji6z6XNAg" name="plop" content="plop"/>
          </widgets>
          <widgets xmi:type="form:SubmitFormButton" xmi:id="_fQeEkftHEeGd6Ji6z6XNAg" name="Submit1">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_fQeEkvtHEeGd6Ji6z6XNAg" line="2"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_fQeEk_tHEeGd6Ji6z6XNAg" name="Submit1" content="Submit1"/>
          </widgets>
          <pageLabel xmi:type="expression:Expression" xmi:id="_fQeElPtHEeGd6Ji6z6XNAg" name="Step1" content="Step1" returnTypeFixed="true"/>
        </form>
        <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_TdkeMPtHEeGd6Ji6z6XNAg" content=""/>
      </elements>
      <elements xmi:type="process:StartEvent" xmi:id="_giN1sPtGEeGd6Ji6z6XNAg" name="Start1" outgoing="_gj4CkPtGEeGd6Ji6z6XNAg"/>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_g6z74PtGEeGd6Ji6z6XNAg" path="_f7aUYPtGEeGd6Ji6z6XNAg/application/application"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_g60i8vtGEeGd6Ji6z6XNAg" path="_f7aUYPtGEeGd6Ji6z6XNAg/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_g60i8PtGEeGd6Ji6z6XNAg" path="_f7aUYPtGEeGd6Ji6z6XNAg/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_g60i8_tGEeGd6Ji6z6XNAg" path="_f7aUYPtGEeGd6Ji6z6XNAg/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_g60i8ftGEeGd6Ji6z6XNAg" path="_f7aUYPtGEeGd6Ji6z6XNAg/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_dIqqgPtHEeGd6Ji6z6XNAg" name="plop" dataType="_fqWZl_tGEeGd6Ji6z6XNAg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_dIqqgftHEeGd6Ji6z6XNAg" content=""/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_gJ6qcPtGEeGd6Ji6z6XNAg" content=""/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gj4CkPtGEeGd6Ji6z6XNAg" source="_giN1sPtGEeGd6Ji6z6XNAg" target="_gaI3wPtGEeGd6Ji6z6XNAg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gj4poPtGEeGd6Ji6z6XNAg"/>
        <condition xmi:type="expression:Expression" xmi:id="_gj4poftGEeGd6Ji6z6XNAg" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_gXvrEPtGEeGd6Ji6z6XNAg" name="Employee"/>
      <actors xmi:type="process:Actor" xmi:id="_gXvrEftGEeGd6Ji6z6XNAg" name="Finance"/>
      <actors xmi:type="process:Actor" xmi:id="_gXvrEvtGEeGd6Ji6z6XNAg" name="Human resource" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_gXvrE_tGEeGd6Ji6z6XNAg" name="Infrastructure"/>
      <actors xmi:type="process:Actor" xmi:id="_gXvrFPtGEeGd6Ji6z6XNAg" name="Sales"/>
      <actors xmi:type="process:Actor" xmi:id="_gXvrFftGEeGd6Ji6z6XNAg" name="Production"/>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_fqWZkftGEeGd6Ji6z6XNAg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_fqWZkvtGEeGd6Ji6z6XNAg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_fqWZk_tGEeGd6Ji6z6XNAg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_fqWZlPtGEeGd6Ji6z6XNAg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_fqWZlftGEeGd6Ji6z6XNAg" name="Double"/>
    <datatypes xmi:type="process:FloatType" xmi:id="_fqWZlvtGEeGd6Ji6z6XNAg" name="Decimal"/>
    <datatypes xmi:type="process:StringType" xmi:id="_fqWZl_tGEeGd6Ji6z6XNAg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_fqWZmPtGEeGd6Ji6z6XNAg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_fqWZmftGEeGd6Ji6z6XNAg" name="XML"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_fqWZmvtGEeGd6Ji6z6XNAg" type="Process" element="_fqWZkPtGEeGd6Ji6z6XNAg" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_gPGFYPtGEeGd6Ji6z6XNAg" type="2007" element="_f7aUYPtGEeGd6Ji6z6XNAg">
      <children xmi:type="notation:DecorationNode" xmi:id="_gPGscPtGEeGd6Ji6z6XNAg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_gPHTgPtGEeGd6Ji6z6XNAg" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_gaPlcPtGEeGd6Ji6z6XNAg" type="3005" element="_gaI3wPtGEeGd6Ji6z6XNAg" fontName="Lucida Grande" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_gaQMgPtGEeGd6Ji6z6XNAg" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gaPlcftGEeGd6Ji6z6XNAg" x="110" y="55"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_giPq4PtGEeGd6Ji6z6XNAg" type="3002" element="_giN1sPtGEeGd6Ji6z6XNAg" fontName="Lucida Grande">
          <children xmi:type="notation:DecorationNode" xmi:id="_giQR8ftGEeGd6Ji6z6XNAg" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_giQR8vtGEeGd6Ji6z6XNAg" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_giQR8PtGEeGd6Ji6z6XNAg" x="40" y="65"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_gPGFYftGEeGd6Ji6z6XNAg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_gPGFYvtGEeGd6Ji6z6XNAg" fontName="Lucida Grande"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_gPGFY_tGEeGd6Ji6z6XNAg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_gPHTgftGEeGd6Ji6z6XNAg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gPGFZPtGEeGd6Ji6z6XNAg"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_fqWZm_tGEeGd6Ji6z6XNAg"/>
    <edges xmi:type="notation:Connector" xmi:id="_gj7F4PtGEeGd6Ji6z6XNAg" type="4001" element="_gj4CkPtGEeGd6Ji6z6XNAg" source="_giPq4PtGEeGd6Ji6z6XNAg" target="_gaPlcPtGEeGd6Ji6z6XNAg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gkMysPtGEeGd6Ji6z6XNAg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gkMysftGEeGd6Ji6z6XNAg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gj7F4ftGEeGd6Ji6z6XNAg" fontName="Lucida Grande"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gj7F4vtGEeGd6Ji6z6XNAg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_fQnOcPtHEeGd6Ji6z6XNAg" type="Form" element="_fQddcPtHEeGd6Ji6z6XNAg" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_fQnOcftHEeGd6Ji6z6XNAg"/>
  </notation:Diagram>
</xmi:XMI>
