/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.w3._1999.xhtml.validation;

import java.util.List;

/**
 * A sample validator interface for {@link org.w3._1999.xhtml.BrType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BrTypeValidator {
	boolean validate();

	boolean validateClass(List<String> value);
	boolean validateId(String value);
	boolean validateStyle(String value);
	boolean validateTitle(String value);
}
