/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.w3._1999.xhtml.validation;

import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.util.FeatureMap;
import org.w3._1999.xhtml.AType;
import org.w3._1999.xhtml.AbbrType;
import org.w3._1999.xhtml.AcronymType;
import org.w3._1999.xhtml.AddressType;
import org.w3._1999.xhtml.AreaType;
import org.w3._1999.xhtml.BType;
import org.w3._1999.xhtml.BaseType;
import org.w3._1999.xhtml.BdoType;
import org.w3._1999.xhtml.BigType;
import org.w3._1999.xhtml.BlockquoteType;
import org.w3._1999.xhtml.BodyType;
import org.w3._1999.xhtml.BrType;
import org.w3._1999.xhtml.ButtonType;
import org.w3._1999.xhtml.CaptionType;
import org.w3._1999.xhtml.CiteType;
import org.w3._1999.xhtml.CodeType;
import org.w3._1999.xhtml.ColType;
import org.w3._1999.xhtml.ColgroupType;
import org.w3._1999.xhtml.DdType;
import org.w3._1999.xhtml.DelType;
import org.w3._1999.xhtml.DfnType;
import org.w3._1999.xhtml.DivType;
import org.w3._1999.xhtml.DlType;
import org.w3._1999.xhtml.DtType;
import org.w3._1999.xhtml.EmType;
import org.w3._1999.xhtml.FieldsetType;
import org.w3._1999.xhtml.FormType;
import org.w3._1999.xhtml.H1Type;
import org.w3._1999.xhtml.H2Type;
import org.w3._1999.xhtml.H3Type;
import org.w3._1999.xhtml.H4Type;
import org.w3._1999.xhtml.H5Type;
import org.w3._1999.xhtml.H6Type;
import org.w3._1999.xhtml.HeadType;
import org.w3._1999.xhtml.HrType;
import org.w3._1999.xhtml.Html;
import org.w3._1999.xhtml.HtmlType;
import org.w3._1999.xhtml.IType;
import org.w3._1999.xhtml.ImgType;
import org.w3._1999.xhtml.InputType1;
import org.w3._1999.xhtml.InsType;
import org.w3._1999.xhtml.KbdType;
import org.w3._1999.xhtml.LabelType;
import org.w3._1999.xhtml.LegendType;
import org.w3._1999.xhtml.LiType;
import org.w3._1999.xhtml.LinkType;
import org.w3._1999.xhtml.MapType;
import org.w3._1999.xhtml.MetaType;
import org.w3._1999.xhtml.NoscriptType;
import org.w3._1999.xhtml.ObjectType;
import org.w3._1999.xhtml.OlType;
import org.w3._1999.xhtml.OptgroupType;
import org.w3._1999.xhtml.OptionType;
import org.w3._1999.xhtml.PType;
import org.w3._1999.xhtml.ParamType;
import org.w3._1999.xhtml.PreType;
import org.w3._1999.xhtml.QType;
import org.w3._1999.xhtml.SampType;
import org.w3._1999.xhtml.ScriptType;
import org.w3._1999.xhtml.SelectType;
import org.w3._1999.xhtml.SmallType;
import org.w3._1999.xhtml.SpanType;
import org.w3._1999.xhtml.StrongType;
import org.w3._1999.xhtml.StyleType;
import org.w3._1999.xhtml.SubType;
import org.w3._1999.xhtml.SupType;
import org.w3._1999.xhtml.TableType;
import org.w3._1999.xhtml.TbodyType;
import org.w3._1999.xhtml.TdType;
import org.w3._1999.xhtml.TextareaType;
import org.w3._1999.xhtml.TfootType;
import org.w3._1999.xhtml.ThType;
import org.w3._1999.xhtml.TheadType;
import org.w3._1999.xhtml.TitleType;
import org.w3._1999.xhtml.TrType;
import org.w3._1999.xhtml.TtType;
import org.w3._1999.xhtml.UlType;
import org.w3._1999.xhtml.VarType;

/**
 * A sample validator interface for {@link org.w3._1999.xhtml.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateXMLNSPrefixMap(EMap<String, String> value);
	boolean validateXSISchemaLocation(EMap<String, String> value);
	boolean validateA(AType value);
	boolean validateAbbr(AbbrType value);
	boolean validateAcronym(AcronymType value);
	boolean validateAddress(AddressType value);
	boolean validateArea(AreaType value);
	boolean validateB(BType value);
	boolean validateBase(BaseType value);
	boolean validateBdo(BdoType value);
	boolean validateBig(BigType value);
	boolean validateBlockquote(BlockquoteType value);
	boolean validateBody(BodyType value);
	boolean validateBr(BrType value);
	boolean validateButton(ButtonType value);
	boolean validateCaption(CaptionType value);
	boolean validateCite(CiteType value);
	boolean validateCode(CodeType value);
	boolean validateCol(ColType value);
	boolean validateColgroup(ColgroupType value);
	boolean validateDd(DdType value);
	boolean validateDel(DelType value);
	boolean validateDfn(DfnType value);
	boolean validateDiv(DivType value);
	boolean validateDl(DlType value);
	boolean validateDt(DtType value);
	boolean validateEm(EmType value);
	boolean validateFieldset(FieldsetType value);
	boolean validateForm(FormType value);
	boolean validateH1(H1Type value);
	boolean validateH2(H2Type value);
	boolean validateH3(H3Type value);
	boolean validateH4(H4Type value);
	boolean validateH5(H5Type value);
	boolean validateH6(H6Type value);
	boolean validateHead(HeadType value);
	boolean validateHr(HrType value);
	boolean validateHtml(Html value);

	boolean validateHtml(HtmlType value);
	boolean validateI(IType value);
	boolean validateImg(ImgType value);
	boolean validateInput(InputType1 value);
	boolean validateIns(InsType value);
	boolean validateKbd(KbdType value);
	boolean validateLabel(LabelType value);
	boolean validateLegend(LegendType value);
	boolean validateLi(LiType value);
	boolean validateLink(LinkType value);
	boolean validateMap(MapType value);
	boolean validateMeta(MetaType value);
	boolean validateNoscript(NoscriptType value);
	boolean validateObject(ObjectType value);
	boolean validateOl(OlType value);
	boolean validateOptgroup(OptgroupType value);
	boolean validateOption(OptionType value);
	boolean validateP(PType value);
	boolean validateParam(ParamType value);
	boolean validatePre(PreType value);
	boolean validateQ(QType value);
	boolean validateSamp(SampType value);
	boolean validateScript(ScriptType value);
	boolean validateSelect(SelectType value);
	boolean validateSmall(SmallType value);
	boolean validateSpan(SpanType value);
	boolean validateStrong(StrongType value);
	boolean validateStyle(StyleType value);
	boolean validateSub(SubType value);
	boolean validateSup(SupType value);
	boolean validateTable(TableType value);
	boolean validateTbody(TbodyType value);
	boolean validateTd(TdType value);
	boolean validateTextarea(TextareaType value);
	boolean validateTfoot(TfootType value);
	boolean validateTh(ThType value);
	boolean validateThead(TheadType value);
	boolean validateTitle(TitleType value);
	boolean validateTr(TrType value);
	boolean validateTt(TtType value);
	boolean validateUl(UlType value);
	boolean validateVar(VarType value);
}
