/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.w3._1999.xhtml.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.util.FeatureMap;
import org.w3._1999.xhtml.AddressType;
import org.w3._1999.xhtml.AreaType;
import org.w3._1999.xhtml.BlockquoteType;
import org.w3._1999.xhtml.DelType;
import org.w3._1999.xhtml.DirType;
import org.w3._1999.xhtml.DivType;
import org.w3._1999.xhtml.DlType;
import org.w3._1999.xhtml.FieldsetType;
import org.w3._1999.xhtml.FormType;
import org.w3._1999.xhtml.H1Type;
import org.w3._1999.xhtml.H2Type;
import org.w3._1999.xhtml.H3Type;
import org.w3._1999.xhtml.H4Type;
import org.w3._1999.xhtml.H5Type;
import org.w3._1999.xhtml.H6Type;
import org.w3._1999.xhtml.HrType;
import org.w3._1999.xhtml.InsType;
import org.w3._1999.xhtml.NoscriptType;
import org.w3._1999.xhtml.OlType;
import org.w3._1999.xhtml.PType;
import org.w3._1999.xhtml.PreType;
import org.w3._1999.xhtml.ScriptType;
import org.w3._1999.xhtml.TableType;
import org.w3._1999.xhtml.UlType;

/**
 * A sample validator interface for {@link org.w3._1999.xhtml.MapType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MapTypeValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateP(EList<PType> value);
	boolean validateH1(EList<H1Type> value);
	boolean validateH2(EList<H2Type> value);
	boolean validateH3(EList<H3Type> value);
	boolean validateH4(EList<H4Type> value);
	boolean validateH5(EList<H5Type> value);
	boolean validateH6(EList<H6Type> value);
	boolean validateDiv(EList<DivType> value);
	boolean validateUl(EList<UlType> value);
	boolean validateOl(EList<OlType> value);
	boolean validateDl(EList<DlType> value);
	boolean validatePre(EList<PreType> value);
	boolean validateHr(EList<HrType> value);
	boolean validateBlockquote(EList<BlockquoteType> value);
	boolean validateAddress(EList<AddressType> value);
	boolean validateFieldset(EList<FieldsetType> value);
	boolean validateTable(EList<TableType> value);
	boolean validateForm(EList<FormType> value);
	boolean validateNoscript(EList<NoscriptType> value);
	boolean validateIns(EList<InsType> value);
	boolean validateDel(EList<DelType> value);
	boolean validateScript(EList<ScriptType> value);
	boolean validateArea(EList<AreaType> value);
	boolean validateClass(Object value);
	boolean validateDir(DirType value);
	boolean validateId(String value);
	boolean validateLang(String value);
	boolean validateLang1(String value);
	boolean validateName(String value);
	boolean validateOnclick(String value);
	boolean validateOndblclick(String value);
	boolean validateOnkeydown(String value);
	boolean validateOnkeypress(String value);
	boolean validateOnkeyup(String value);
	boolean validateOnmousedown(String value);
	boolean validateOnmousemove(String value);
	boolean validateOnmouseout(String value);
	boolean validateOnmouseover(String value);
	boolean validateOnmouseup(String value);
	boolean validateStyle(String value);
	boolean validateTitle(String value);
}
