/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.w3._1999.xhtml.validation;

import org.w3._1999.xhtml.ValuetypeType;

/**
 * A sample validator interface for {@link org.w3._1999.xhtml.ParamType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParamTypeValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateName(Object value);
	boolean validateType(String value);
	boolean validateValue(Object value);
	boolean validateValuetype(ValuetypeType value);
}
