/*
 * Copyright (C) 2009 BonitaSoft S.A.
 * BonitaSoft, 31 rue Gustave Eiffel - 38000 Grenoble
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2.0 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.bonitasoft.studio.model.process.diagram.edit.parts;

import org.bonitasoft.studio.common.diagram.ActivityCursorMouseMotionListener;
import org.bonitasoft.studio.common.diagram.ActivityNameCursorMouseMotionListener;
import org.bonitasoft.studio.common.diagram.tools.DragEditPartsTrackerExWithoutCopyWithModKeyPressed;
import org.bonitasoft.studio.common.gmf.tools.GMFTools;
import org.bonitasoft.studio.model.process.diagram.edit.policies.PoolItemSemanticEditPolicy;
import org.bonitasoft.studio.model.process.diagram.part.ProcessVisualIDRegistry;
import org.eclipse.draw2d.GridData;
import org.eclipse.draw2d.GridLayout;
import org.eclipse.draw2d.IFigure;
import org.eclipse.draw2d.PositionConstants;
import org.eclipse.draw2d.RectangleFigure;
import org.eclipse.draw2d.Shape;
import org.eclipse.draw2d.StackLayout;
import org.eclipse.draw2d.geometry.Dimension;
import org.eclipse.gef.DragTracker;
import org.eclipse.gef.EditPart;
import org.eclipse.gef.EditPolicy;
import org.eclipse.gef.Request;
import org.eclipse.gef.SnapToHelper;
import org.eclipse.gef.commands.Command;
import org.eclipse.gef.editpolicies.LayoutEditPolicy;
import org.eclipse.gef.editpolicies.NonResizableEditPolicy;
import org.eclipse.gef.editpolicies.ResizableEditPolicy;
import org.eclipse.gef.requests.CreateRequest;
import org.eclipse.gmf.runtime.diagram.ui.editparts.DiagramEditPart;
import org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart;
import org.eclipse.gmf.runtime.diagram.ui.editparts.IGraphicalEditPart;
import org.eclipse.gmf.runtime.diagram.ui.editparts.ShapeNodeEditPart;
import org.eclipse.gmf.runtime.diagram.ui.editpolicies.EditPolicyRoles;
import org.eclipse.gmf.runtime.draw2d.ui.figures.ConstrainedToolbarLayout;
import org.eclipse.gmf.runtime.draw2d.ui.figures.WrappingLabel;
import org.eclipse.gmf.runtime.gef.ui.figures.DefaultSizeNodeFigure;
import org.eclipse.gmf.runtime.gef.ui.figures.NodeFigure;
import org.eclipse.gmf.runtime.notation.View;
import org.eclipse.swt.graphics.Color;

/**
 * @generated
 */
public class PoolEditPart extends ShapeNodeEditPart {

	/**
	* @generated
	*/
	public static final int VISUAL_ID = 2007;

	/**
	* @generated
	*/
	protected IFigure contentPane;

	/**
	* @generated
	*/
	protected IFigure primaryShape;

	/**
	* @generated
	*/
	public PoolEditPart(View view) {
		super(view);
	}

	/**
	* @generated
	*/
	protected void createDefaultEditPolicies() {
		super.createDefaultEditPolicies();
		installEditPolicy(EditPolicyRoles.SEMANTIC_ROLE, new PoolItemSemanticEditPolicy());
		installEditPolicy(EditPolicy.LAYOUT_ROLE, createLayoutEditPolicy());
		// XXX need an SCR to runtime to have another abstract superclass that would let children add reasonable editpolicies
		// removeEditPolicy(org.eclipse.gmf.runtime.diagram.ui.editpolicies.EditPolicyRoles.CONNECTION_HANDLES_ROLE);
	}

	/**
	* @generated
	*/
	protected LayoutEditPolicy createLayoutEditPolicy() {
		org.eclipse.gmf.runtime.diagram.ui.editpolicies.LayoutEditPolicy lep = new org.eclipse.gmf.runtime.diagram.ui.editpolicies.LayoutEditPolicy() {

			protected EditPolicy createChildEditPolicy(EditPart child) {

				EditPolicy result = child.getEditPolicy(EditPolicy.PRIMARY_DRAG_ROLE);
				if (result == null) {
					result = new NonResizableEditPolicy();
				}
				return result;
			}

			protected Command getMoveChildrenCommand(Request request) {
				return null;
			}

			protected Command getCreateCommand(CreateRequest request) {
				return null;
			}
		};
		return lep;
	}

	/**
	* @generated
	*/
	protected IFigure createNodeShape() {
		return primaryShape = new PoolFigure();
	}

	/**
	* @generated
	*/
	public PoolFigure getPrimaryShape() {
		return (PoolFigure) primaryShape;
	}

	/*
	* @generated by BonitaSoft
	*/
	protected boolean addFixedChild(EditPart childEditPart) {
		if (childEditPart instanceof PoolNameEditPart) {
			((PoolNameEditPart) childEditPart).setLabel(getPrimaryShape().getFigurePoolNameFigure());
			if (VISUAL_ID != 3007 && VISUAL_ID != 2007 && VISUAL_ID != 3015 && VISUAL_ID != 3058) {
				getPrimaryShape().getFigurePoolNameFigure()
						.addMouseMotionListener(new ActivityNameCursorMouseMotionListener(this));
			}
			return true;
		}
		if (childEditPart instanceof PoolPoolCompartmentEditPart) {
			IFigure pane = getPrimaryShape().getFigurePoolContainerFigure();
			setupContentPane(pane); // FIXME each comparment should handle his content pane in his own way 
			pane.add(((PoolPoolCompartmentEditPart) childEditPart).getFigure());
			return true;
		}

		return false;
	}

	/**
	* @generated
	*/
	protected boolean removeFixedChild(EditPart childEditPart) {
		if (childEditPart instanceof PoolNameEditPart) {
			return true;
		}
		if (childEditPart instanceof PoolPoolCompartmentEditPart) {
			IFigure pane = getPrimaryShape().getFigurePoolContainerFigure();
			pane.remove(((PoolPoolCompartmentEditPart) childEditPart).getFigure());
			return true;
		}
		return false;
	}

	/**
	* @generated
	*/
	protected void addChildVisual(EditPart childEditPart, int index) {
		if (addFixedChild(childEditPart)) {
			return;
		}
		super.addChildVisual(childEditPart, -1);
	}

	/**
	* @generated
	*/
	protected void removeChildVisual(EditPart childEditPart) {
		if (removeFixedChild(childEditPart)) {
			return;
		}
		super.removeChildVisual(childEditPart);
	}

	/**
	* @generated
	*/
	protected IFigure getContentPaneFor(IGraphicalEditPart editPart) {
		if (editPart instanceof PoolPoolCompartmentEditPart) {
			return getPrimaryShape().getFigurePoolContainerFigure();
		}
		return getContentPane();
	}

	/**
	* @generated
	*/
	protected NodeFigure createNodePlate() {
		DefaultSizeNodeFigure result = new DefaultSizeNodeFigure(1000, 100);
		return result;
	}

	/**
	* @generated
	*/
	public EditPolicy getPrimaryDragEditPolicy() {
		EditPolicy result = super.getPrimaryDragEditPolicy();
		if (result instanceof ResizableEditPolicy) {
			ResizableEditPolicy ep = (ResizableEditPolicy) result;
			ep.setResizeDirections(PositionConstants.NONE);
		}
		return result;
	}

	/**
	* Creates figure for this edit part.
	* 
	* Body of this method does not depend on settings in generation model
	* so you may safely remove <i>generated</i> tag and modify it.
	* 
	* @generated
	*/
	protected NodeFigure createNodeFigure() {
		NodeFigure figure = createNodePlate();
		figure.setLayoutManager(new StackLayout());
		IFigure shape = createNodeShape();
		figure.add(shape);
		contentPane = setupContentPane(shape);
		return figure;
	}

	/**
	* Default implementation treats passed figure as content pane.
	* Respects layout one may have set for generated figure.
	* @param nodeShape instance of generated figure class
	* @generated
	*/
	protected IFigure setupContentPane(IFigure nodeShape) {
		if (nodeShape.getLayoutManager() == null) {
			ConstrainedToolbarLayout layout = new ConstrainedToolbarLayout();
			layout.setSpacing(5);
			nodeShape.setLayoutManager(layout);
		}
		if (VISUAL_ID != 3007 && VISUAL_ID != 2007) {
			getPrimaryShape().addMouseMotionListener(new ActivityCursorMouseMotionListener());
		}
		return nodeShape; // use nodeShape itself as contentPane
	}

	/**
	* @generated
	*/
	public IFigure getContentPane() {
		if (contentPane != null) {
			return contentPane;
		}
		return super.getContentPane();
	}

	/**
	* @generated
	*/
	protected void setForegroundColor(Color color) {
		if (primaryShape != null) {
			primaryShape.setForegroundColor(color);
		}
	}

	/**
	* @generated
	*/
	protected void setBackgroundColor(Color color) {
		if (primaryShape != null) {
			primaryShape.setBackgroundColor(color);
		}
	}

	/**
	* @generated
	*/
	protected void setLineWidth(int width) {
		if (primaryShape instanceof Shape) {
			((Shape) primaryShape).setLineWidth(width);
		}
	}

	/**
	* @generated
	*/
	protected void setLineType(int style) {
		if (primaryShape instanceof Shape) {
			((Shape) primaryShape).setLineStyle(style);
		}
	}

	/**
	* @generated
	*/
	public EditPart getPrimaryChildEditPart() {
		return getChildBySemanticHint(ProcessVisualIDRegistry.getType(PoolNameEditPart.VISUAL_ID));
	}

	/**
	 * @generated
	 */
	public class PoolFigure extends RectangleFigure {

		/**
		 * @generated
		 */
		private WrappingLabel fFigurePoolNameFigure;
		/**
		 * @generated
		 */
		private RectangleFigure fFigurePoolContainerFigure;

		/**
		 * @generated
		 */
		public PoolFigure() {

			GridLayout layoutThis = new GridLayout();
			layoutThis.numColumns = 2;
			layoutThis.makeColumnsEqualWidth = false;
			layoutThis.horizontalSpacing = 0;
			layoutThis.verticalSpacing = 0;
			layoutThis.marginWidth = 0;
			layoutThis.marginHeight = 0;
			this.setLayoutManager(layoutThis);

			this.setBackgroundColor(THIS_BACK);
			this.setPreferredSize(new Dimension(getMapMode().DPtoLP(1000), getMapMode().DPtoLP(100)));
			createContents();
		}

		/**
		 * @generated
		 */
		private void createContents() {

			RectangleFigure poolNameContainerFigure0 = new RectangleFigure();

			GridData constraintPoolNameContainerFigure0 = new GridData();
			constraintPoolNameContainerFigure0.verticalAlignment = GridData.FILL;
			constraintPoolNameContainerFigure0.horizontalAlignment = GridData.BEGINNING;
			constraintPoolNameContainerFigure0.horizontalIndent = 0;
			constraintPoolNameContainerFigure0.horizontalSpan = 1;
			constraintPoolNameContainerFigure0.verticalSpan = 1;
			constraintPoolNameContainerFigure0.grabExcessHorizontalSpace = false;
			constraintPoolNameContainerFigure0.grabExcessVerticalSpace = true;
			constraintPoolNameContainerFigure0.widthHint = 20;
			constraintPoolNameContainerFigure0.heightHint = 0;
			this.add(poolNameContainerFigure0, constraintPoolNameContainerFigure0);

			GridLayout layoutPoolNameContainerFigure0 = new GridLayout();
			layoutPoolNameContainerFigure0.numColumns = 1;
			layoutPoolNameContainerFigure0.makeColumnsEqualWidth = true;
			layoutPoolNameContainerFigure0.horizontalSpacing = 0;
			layoutPoolNameContainerFigure0.verticalSpacing = 0;
			layoutPoolNameContainerFigure0.marginWidth = 0;
			layoutPoolNameContainerFigure0.marginHeight = 0;
			poolNameContainerFigure0.setLayoutManager(layoutPoolNameContainerFigure0);

			fFigurePoolNameFigure = new WrappingLabel();

			fFigurePoolNameFigure.setText("");

			GridData constraintFFigurePoolNameFigure = new GridData();
			constraintFFigurePoolNameFigure.verticalAlignment = GridData.FILL;
			constraintFFigurePoolNameFigure.horizontalAlignment = GridData.FILL;
			constraintFFigurePoolNameFigure.horizontalIndent = 2;
			constraintFFigurePoolNameFigure.horizontalSpan = 1;
			constraintFFigurePoolNameFigure.verticalSpan = 1;
			constraintFFigurePoolNameFigure.grabExcessHorizontalSpace = true;
			constraintFFigurePoolNameFigure.grabExcessVerticalSpace = true;
			poolNameContainerFigure0.add(fFigurePoolNameFigure, constraintFFigurePoolNameFigure);

			fFigurePoolContainerFigure = new RectangleFigure();

			GridData constraintFFigurePoolContainerFigure = new GridData();
			constraintFFigurePoolContainerFigure.verticalAlignment = GridData.FILL;
			constraintFFigurePoolContainerFigure.horizontalAlignment = GridData.FILL;
			constraintFFigurePoolContainerFigure.horizontalIndent = 0;
			constraintFFigurePoolContainerFigure.horizontalSpan = 1;
			constraintFFigurePoolContainerFigure.verticalSpan = 1;
			constraintFFigurePoolContainerFigure.grabExcessHorizontalSpace = true;
			constraintFFigurePoolContainerFigure.grabExcessVerticalSpace = true;
			this.add(fFigurePoolContainerFigure, constraintFFigurePoolContainerFigure);

		}

		/**
		 * @generated
		 */
		public WrappingLabel getFigurePoolNameFigure() {
			return fFigurePoolNameFigure;
		}

		/**
		 * @generated
		 */
		public RectangleFigure getFigurePoolContainerFigure() {
			return fFigurePoolContainerFigure;
		}

	}

	/**
	 * @generated
	 */
	static final Color THIS_BACK = new Color(null, 246, 246, 237);

	/*
	* (non-Javadoc)
	* 
	* @see org.eclipse.gmf.runtime.diagram.ui.editparts.GraphicalEditPart#getDragTracker(org.eclipse.gef.Request)
	*/
	@Override
	public DragTracker getDragTracker(Request request) {
		return new DragEditPartsTrackerExWithoutCopyWithModKeyPressed(this);
	}

	/**
	 * @Generated BonitaSoft
	 */
	@Override
	public Object getAdapter(Class key) {

		if (key == SnapToHelper.class) {
			EditPart parent = getParent();
			while (!(parent instanceof DiagramEditPart)) {
				parent = parent.getParent();
			}
			return GMFTools.getSnapHelper((GraphicalEditPart) parent);
		}

		return super.getAdapter(key);
	}
}
