/*
* generated by Xtext
*/
package org.bonitasoft.studio.condition.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ConditionModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/bonitasoft/studio/condition/parser/antlr/internal/InternalConditionModel.tokens");
	}
}
