/*
* generated by Xtext
*/
package org.bonitasoft.studio.condition.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.bonitasoft.studio.condition.services.ConditionModelGrammarAccess;

public class ConditionModelParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ConditionModelGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected org.bonitasoft.studio.condition.parser.antlr.internal.InternalConditionModelParser createParser(XtextTokenStream stream) {
		return new org.bonitasoft.studio.condition.parser.antlr.internal.InternalConditionModelParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Operation_Compare";
	}
	
	public ConditionModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ConditionModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
