<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_Hziu8FtPEeS_U_Le4RccVQ" name="DiagramWithPoolWithInstanciationForm" author="aurelien" bonitaVersion="6.4.0" bonitaModelVersion="6.4.0-001" configId="ACED00057400324469616772616D57697468506F6F6C57697468496E7374616E63696174696F6E466F726D362E342E302D303031362E342E30">
    <elements xmi:type="process:Pool" xmi:id="_Hziu8VtPEeS_U_Le4RccVQ" name="PoolWithInstanciationForm" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Lane" xmi:id="_Hziu8ltPEeS_U_Le4RccVQ" name="Employee lane" actor="_HzivE1tPEeS_U_Le4RccVQ">
        <elements xmi:type="process:Task" xmi:id="_Hziu81tPEeS_U_Le4RccVQ" name="Step1" incoming="_HzivEFtPEeS_U_Le4RccVQ" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_Hziu9FtPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Hziu9VtPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Hziu9ltPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Hziu91tPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Hziu-FtPEeS_U_Le4RccVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Hziu-VtPEeS_U_Le4RccVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Hziu-ltPEeS_U_Le4RccVQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Hziu-1tPEeS_U_Le4RccVQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Hziu_FtPEeS_U_Le4RccVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_Hziu_VtPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_Hziu_ltPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_Hziu_1tPEeS_U_Le4RccVQ" name="Start1" outgoing="_HzivEFtPEeS_U_Le4RccVQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_HzivAFtPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HzivAVtPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HzivAltPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HzivA1tPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_H20FYFtPEeS_U_Le4RccVQ" path="_Hziu8VtPEeS_U_Le4RccVQ/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_HzivBVtPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_HzivBltPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_HzivB1tPEeS_U_Le4RccVQ" path="_Hziu8VtPEeS_U_Le4RccVQ/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_HzivCFtPEeS_U_Le4RccVQ" path="_Hziu8VtPEeS_U_Le4RccVQ/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_HzivCVtPEeS_U_Le4RccVQ" path="_Hziu8VtPEeS_U_Le4RccVQ/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_HzivCltPEeS_U_Le4RccVQ" path="_Hziu8VtPEeS_U_Le4RccVQ/html/consultation.html"/>
      <form xmi:type="form:Form" xmi:id="_Pi0u0FtPEeS_U_Le4RccVQ" name="PoolWithInstanciationForm" nLine="3">
        <widgets xmi:type="form:SubmitFormButton" xmi:id="_Pi0u0VtPEeS_U_Le4RccVQ" name="Submit1">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Pi0u0ltPEeS_U_Le4RccVQ" line="2"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_Pi0u01tPEeS_U_Le4RccVQ" name="Submit1" content="Submit1" returnTypeFixed="true"/>
          <injectWidgetScript xmi:type="expression:Expression" xmi:id="_Pi0u1FtPEeS_U_Le4RccVQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </widgets>
        <pageLabel xmi:type="expression:Expression" xmi:id="_Pi0u1VtPEeS_U_Le4RccVQ" name="Pool With Instanciation Form" content="Pool With Instanciation Form" returnTypeFixed="true"/>
      </form>
      <confirmationTemplate xmi:type="process:AssociatedFile" xmi:id="_HzivC1tPEeS_U_Le4RccVQ" path="_Hziu8VtPEeS_U_Le4RccVQ/html/_Hziu8VtPEeS_U_Le4RccVQconfirmation.html"/>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_HzivDFtPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_HzivDVtPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_HzivDltPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_HzivD1tPEeS_U_Le4RccVQ" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HzivEFtPEeS_U_Le4RccVQ" source="_Hziu_1tPEeS_U_Le4RccVQ" target="_Hziu81tPEeS_U_Le4RccVQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HzivEVtPEeS_U_Le4RccVQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HzivEltPEeS_U_Le4RccVQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_HzivE1tPEeS_U_Le4RccVQ" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HzivFFtPEeS_U_Le4RccVQ">
        <name xmi:type="expression:Expression" xmi:id="_HzivFVtPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HzivFltPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HzivF1tPEeS_U_Le4RccVQ">
        <name xmi:type="expression:Expression" xmi:id="_HzivGFtPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HzivGVtPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HzivGltPEeS_U_Le4RccVQ">
        <name xmi:type="expression:Expression" xmi:id="_HzivG1tPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HzivHFtPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HzivHVtPEeS_U_Le4RccVQ">
        <name xmi:type="expression:Expression" xmi:id="_HzivHltPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HzivH1tPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_HzivIFtPEeS_U_Le4RccVQ">
        <name xmi:type="expression:Expression" xmi:id="_HzivIVtPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_HzivIltPEeS_U_Le4RccVQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_HzivI1tPEeS_U_Le4RccVQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_HzivJFtPEeS_U_Le4RccVQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_HzivJVtPEeS_U_Le4RccVQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_HzivJltPEeS_U_Le4RccVQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_HzivJ1tPEeS_U_Le4RccVQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_HzivKFtPEeS_U_Le4RccVQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_HzivKVtPEeS_U_Le4RccVQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_HzivKltPEeS_U_Le4RccVQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_HzivK1tPEeS_U_Le4RccVQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_HzivLFtPEeS_U_Le4RccVQ" type="Process" element="_Hziu8FtPEeS_U_Le4RccVQ" name="MyDiagram2" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_HzivLVtPEeS_U_Le4RccVQ" type="2007" element="_Hziu8VtPEeS_U_Le4RccVQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_HzivLltPEeS_U_Le4RccVQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_HzivL1tPEeS_U_Le4RccVQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_HzivMFtPEeS_U_Le4RccVQ" type="3007" element="_Hziu8ltPEeS_U_Le4RccVQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_HzivMVtPEeS_U_Le4RccVQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_HzivMltPEeS_U_Le4RccVQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_HzivM1tPEeS_U_Le4RccVQ" type="3005" element="_Hziu81tPEeS_U_Le4RccVQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HzivNFtPEeS_U_Le4RccVQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HzivNVtPEeS_U_Le4RccVQ" x="160" y="55"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HzivNltPEeS_U_Le4RccVQ" type="3002" element="_Hziu_1tPEeS_U_Le4RccVQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HzivN1tPEeS_U_Le4RccVQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HzivOFtPEeS_U_Le4RccVQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HzivOVtPEeS_U_Le4RccVQ" x="60" y="65"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_HzivOltPEeS_U_Le4RccVQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_HzivO1tPEeS_U_Le4RccVQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_HzivPFtPEeS_U_Le4RccVQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_HzivPVtPEeS_U_Le4RccVQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HzivPltPEeS_U_Le4RccVQ" x="-40" y="-20"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_HzivP1tPEeS_U_Le4RccVQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_HzivQFtPEeS_U_Le4RccVQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_HzivQVtPEeS_U_Le4RccVQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_HzivQltPEeS_U_Le4RccVQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HzivQ1tPEeS_U_Le4RccVQ"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_HzivRFtPEeS_U_Le4RccVQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_HzivRVtPEeS_U_Le4RccVQ" type="4001" element="_HzivEFtPEeS_U_Le4RccVQ" source="_HzivNltPEeS_U_Le4RccVQ" target="_HzivM1tPEeS_U_Le4RccVQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HzivRltPEeS_U_Le4RccVQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HzivR1tPEeS_U_Le4RccVQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HzivSFtPEeS_U_Le4RccVQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HzivSVtPEeS_U_Le4RccVQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_Pi_t8FtPEeS_U_Le4RccVQ" type="Form" element="_Pi0u0FtPEeS_U_Le4RccVQ" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Pi_t8VtPEeS_U_Le4RccVQ"/>
  </notation:Diagram>
</xmi:XMI>
