<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:form="http://www.bonitasoft.org/ns/studio/form" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_GDs4sQc9EeKnAKrJ9eggtA" name="DemoMessageContentCorrelation" bonitaVersion="6.0.0-GA" bonitaModelVersion="6.0.0-ga-004" configId="ACED000574003144656D6F4D657373616765436F6E74656E74436F7272656C6174696F6E362E302E302D67612D303034362E302E302D4741">
    <elements xmi:type="process:Pool" xmi:id="_GU-O4Ac9EeKnAKrJ9eggtA" name="Customer" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Task" xmi:id="_Gca6sAc9EeKnAKrJ9eggtA" name="Choose Products" outgoing="_f44G8Ac9EeKnAKrJ9eggtA" incoming="_Gn38wAc9EeKnAKrJ9eggtA" actor="_QyQtIAc9EeKnAKrJ9eggtA"/>
      <elements xmi:type="process:StartEvent" xmi:id="_Gm1a8Ac9EeKnAKrJ9eggtA" name="Start1" outgoing="_Gn38wAc9EeKnAKrJ9eggtA"/>
      <elements xmi:type="process:Task" xmi:id="_aTzU0Ac9EeKnAKrJ9eggtA" name="Order Products" outgoing="_PZEIwAdBEeKnAKrJ9eggtA" incoming="_f44G8Ac9EeKnAKrJ9eggtA" actor="_QyQtIAc9EeKnAKrJ9eggtA">
        <form xmi:type="form:Form" xmi:id="_7M6rQAl_EeKCufEP31yKhg" name="Order_Products" nLine="6">
          <widgets xmi:type="form:TextFormField" xmi:id="_7M6rQQl_EeKCufEP31yKhg" name="product" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_7M6rQgl_EeKCufEP31yKhg"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_7M6rQwl_EeKCufEP31yKhg" name="product" content="product" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_7M6rRAl_EeKCufEP31yKhg" name="product" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgSoALbmEeKtmP3ff0v-WQ" content=""/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_7M6rRgl_EeKCufEP31yKhg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgT2J7bmEeKtmP3ff0v-WQ" name="product" content="product" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_IgT2KLbmEeKtmP3ff0v-WQ" name="product" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgT2KbbmEeKtmP3ff0v-WQ" content=""/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_7M6rSgl_EeKCufEP31yKhg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgT2KrbmEeKtmP3ff0v-WQ" name="field_product" content="field_product" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_IgT2K7bmEeKtmP3ff0v-WQ" name="product" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgT2LLbmEeKtmP3ff0v-WQ"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgT2LbbmEeKtmP3ff0v-WQ" name="product" content="product" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgT2LrbmEeKtmP3ff0v-WQ" name="product" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgT2L7bmEeKtmP3ff0v-WQ" content=""/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgT2MLbmEeKtmP3ff0v-WQ" name="product" content="product"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_7M6rUgl_EeKCufEP31yKhg" name="product" content="product"/>
          </widgets>
          <widgets xmi:type="form:TextFormField" xmi:id="_7M6rUwl_EeKCufEP31yKhg" name="orderInformation" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_7M6rVAl_EeKCufEP31yKhg" line="1"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_7M6rVQl_EeKCufEP31yKhg" name="orderInformation" content="orderInformation" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_7M6rVgl_EeKCufEP31yKhg" name="orderInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgSoAbbmEeKtmP3ff0v-WQ"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_7M6rWAl_EeKCufEP31yKhg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgT2MrbmEeKtmP3ff0v-WQ" name="orderInformation" content="orderInformation" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_IgUdMLbmEeKtmP3ff0v-WQ" name="orderInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgUdMbbmEeKtmP3ff0v-WQ"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_7M6rXAl_EeKCufEP31yKhg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgUdMrbmEeKtmP3ff0v-WQ" name="field_orderInformation" content="field_orderInformation" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_IgUdM7bmEeKtmP3ff0v-WQ" name="orderInformation" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgUdNLbmEeKtmP3ff0v-WQ" line="1"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgUdNbbmEeKtmP3ff0v-WQ" name="orderInformation" content="orderInformation" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgUdNrbmEeKtmP3ff0v-WQ" name="orderInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgUdN7bmEeKtmP3ff0v-WQ"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgUdOLbmEeKtmP3ff0v-WQ" name="orderInformation" content="orderInformation"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_7M7SVQl_EeKCufEP31yKhg" name="orderInformation" content="orderInformation"/>
          </widgets>
          <widgets xmi:type="form:TextFormField" xmi:id="_7M7SVgl_EeKCufEP31yKhg" name="customerId" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_7M7SVwl_EeKCufEP31yKhg" line="2"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_7M7SWAl_EeKCufEP31yKhg" name="customerId" content="customerId" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_7M7SWQl_EeKCufEP31yKhg" name="customerId" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPELbmEeKtmP3ff0v-WQ"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_7M7SWwl_EeKCufEP31yKhg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgUdOrbmEeKtmP3ff0v-WQ" name="customerId" content="customerId" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_IgUdO7bmEeKtmP3ff0v-WQ" name="customerId" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgUdPLbmEeKtmP3ff0v-WQ"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_7M7SXwl_EeKCufEP31yKhg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgUdPbbmEeKtmP3ff0v-WQ" name="field_customerId" content="field_customerId" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_IgUdPrbmEeKtmP3ff0v-WQ" name="customerId" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgUdP7bmEeKtmP3ff0v-WQ" line="2"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgUdQLbmEeKtmP3ff0v-WQ" name="customerId" content="customerId" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgUdQbbmEeKtmP3ff0v-WQ" name="customerId" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgUdQrbmEeKtmP3ff0v-WQ"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgUdQ7bmEeKtmP3ff0v-WQ" name="customerId" content="customerId"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_7M7SZwl_EeKCufEP31yKhg" name="customerId" content="customerId"/>
          </widgets>
          <widgets xmi:type="form:DateFormField" xmi:id="_7M7SaAl_EeKCufEP31yKhg" name="orderDate" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgVrXLbmEeKtmP3ff0v-WQ" line="3"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_IgVrXbbmEeKtmP3ff0v-WQ" name="orderDate" content="orderDate" type="TYPE_VARIABLE" returnType="java.util.Date">
              <referencedElements xmi:type="process:Data" xmi:id="_IgVrXrbmEeKtmP3ff0v-WQ" name="orderDate" dataType="_GDs4swc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgVrX7bmEeKtmP3ff0v-WQ" name="" content="&quot;2012/09/25/20/21/38&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
              </referencedElements>
              <referencedElements xmi:type="process:Data" xmi:id="_IgVrYLbmEeKtmP3ff0v-WQ" name="orderDate" dataType="_GDs4swc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgVrYbbmEeKtmP3ff0v-WQ" name="" content="&quot;2012/09/25/20/21/38&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_IgVrY7bmEeKtmP3ff0v-WQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgVrZLbmEeKtmP3ff0v-WQ" name="orderDate" content="orderDate" type="TYPE_VARIABLE" returnType="java.util.Date">
                <referencedElements xmi:type="process:Data" xmi:id="_IgVrZbbmEeKtmP3ff0v-WQ" name="orderDate" dataType="_GDs4swc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgVrZrbmEeKtmP3ff0v-WQ" name="" content="&quot;2012/09/25/20/21/38&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
                </referencedElements>
                <referencedElements xmi:type="process:Data" xmi:id="_IgVrZ7bmEeKtmP3ff0v-WQ" name="orderDate" dataType="_GDs4swc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgVraLbmEeKtmP3ff0v-WQ" name="" content="&quot;2012/09/25/20/21/38&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_IgVra7bmEeKtmP3ff0v-WQ" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgVrabbmEeKtmP3ff0v-WQ" name="field_orderDate" content="field_orderDate" type="TYPE_INPUT" returnType="java.util.Date">
                <referencedElements xmi:type="form:DateFormField" xmi:id="_7M7Scwl_EeKCufEP31yKhg" name="orderDate" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgWSYLbmEeKtmP3ff0v-WQ" line="3"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgWSYbbmEeKtmP3ff0v-WQ" name="orderDate" content="orderDate" type="TYPE_VARIABLE" returnType="java.util.Date">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgWSYrbmEeKtmP3ff0v-WQ" name="orderDate" dataType="_GDs4swc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgWSY7bmEeKtmP3ff0v-WQ" name="" content="&quot;2012/09/25/20/21/38&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
                    </referencedElements>
                    <referencedElements xmi:type="process:Data" xmi:id="_IgWSZLbmEeKtmP3ff0v-WQ" name="orderDate" dataType="_GDs4swc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgWSZbbmEeKtmP3ff0v-WQ" name="" content="&quot;2012/09/25/20/21/38&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgWSZrbmEeKtmP3ff0v-WQ" name="orderDate" content="orderDate"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_IgVrYrbmEeKtmP3ff0v-WQ" name="orderDate" content="orderDate"/>
          </widgets>
          <widgets xmi:type="form:TextFormField" xmi:id="_7M7Segl_EeKCufEP31yKhg" name="customerInformation" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_7M7Sewl_EeKCufEP31yKhg" line="4"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_7M7SfAl_EeKCufEP31yKhg" name="customerInformation" content="customerInformation" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_7M7SfQl_EeKCufEP31yKhg" name="customerInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPEbbmEeKtmP3ff0v-WQ"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_7M75YAl_EeKCufEP31yKhg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgUdRbbmEeKtmP3ff0v-WQ" name="customerInformation" content="customerInformation" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_IgUdRrbmEeKtmP3ff0v-WQ" name="customerInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgUdR7bmEeKtmP3ff0v-WQ"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_7M75ZAl_EeKCufEP31yKhg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgUdSLbmEeKtmP3ff0v-WQ" name="field_customerInformation" content="field_customerInformation" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_IgUdSbbmEeKtmP3ff0v-WQ" name="customerInformation" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgUdSrbmEeKtmP3ff0v-WQ" line="4"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgUdS7bmEeKtmP3ff0v-WQ" name="customerInformation" content="customerInformation" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgUdTLbmEeKtmP3ff0v-WQ" name="customerInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgUdTbbmEeKtmP3ff0v-WQ"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgUdTrbmEeKtmP3ff0v-WQ" name="customerInformation" content="customerInformation"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_7M75bAl_EeKCufEP31yKhg" name="customerInformation" content="customerInformation"/>
          </widgets>
          <widgets xmi:type="form:SubmitFormButton" xmi:id="_7M75bQl_EeKCufEP31yKhg" name="Submit1" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgWSZ7bmEeKtmP3ff0v-WQ" line="5"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_IgWSaLbmEeKtmP3ff0v-WQ" name="Submit1" content="Submit1"/>
          </widgets>
          <pageLabel xmi:type="expression:Expression" xmi:id="_7M75cAl_EeKCufEP31yKhg" name="Order Products" content="Order Products" returnTypeFixed="true"/>
        </form>
        <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_6CWVkAl_EeKCufEP31yKhg" content=""/>
      </elements>
      <elements xmi:type="process:EndMessageEvent" xmi:id="_OjzUsAdBEeKnAKrJ9eggtA" name="send order" incoming="_PZEIwAdBEeKnAKrJ9eggtA">
        <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_IgWSbbbmEeKtmP3ff0v-WQ" content=""/>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_Grl_IAc9EeKnAKrJ9eggtA" path="_GU-O4Ac9EeKnAKrJ9eggtA/application/application"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_Grl_Iwc9EeKnAKrJ9eggtA" path="_GU-O4Ac9EeKnAKrJ9eggtA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_Grl_IQc9EeKnAKrJ9eggtA" path="_GU-O4Ac9EeKnAKrJ9eggtA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_Grl_JAc9EeKnAKrJ9eggtA" path="_GU-O4Ac9EeKnAKrJ9eggtA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_Grl_Igc9EeKnAKrJ9eggtA" path="_GU-O4Ac9EeKnAKrJ9eggtA/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_zBn5cAc9EeKnAKrJ9eggtA" name="customerId" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPErbmEeKtmP3ff0v-WQ"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_i-gfIAmCEeKCufEP31yKhg" name="orderDate" dataType="_GDs4swc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPE7bmEeKtmP3ff0v-WQ" name="" content="&quot;2012/09/25/20/21/38&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_9jtYIAc9EeKnAKrJ9eggtA" name="customerInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPFLbmEeKtmP3ff0v-WQ"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_2QTnUAl_EeKCufEP31yKhg" name="product" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPFbbmEeKtmP3ff0v-WQ" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_KjzKUAc-EeKnAKrJ9eggtA" name="orderInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPFrbmEeKtmP3ff0v-WQ"/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_GVH_4Ac9EeKnAKrJ9eggtA" content=""/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Gn38wAc9EeKnAKrJ9eggtA" source="_Gm1a8Ac9EeKnAKrJ9eggtA" target="_Gca6sAc9EeKnAKrJ9eggtA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Gn38wQc9EeKnAKrJ9eggtA"/>
        <condition xmi:type="expression:Expression" xmi:id="_IgWSb7bmEeKtmP3ff0v-WQ" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_f44G8Ac9EeKnAKrJ9eggtA" source="_Gca6sAc9EeKnAKrJ9eggtA" target="_aTzU0Ac9EeKnAKrJ9eggtA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_f44G8Qc9EeKnAKrJ9eggtA"/>
        <condition xmi:type="expression:Expression" xmi:id="_IgWScbbmEeKtmP3ff0v-WQ" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PZEIwAdBEeKnAKrJ9eggtA" source="_aTzU0Ac9EeKnAKrJ9eggtA" target="_OjzUsAdBEeKnAKrJ9eggtA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PZN5wAdBEeKnAKrJ9eggtA"/>
        <condition xmi:type="expression:Expression" xmi:id="_IgW5cbbmEeKtmP3ff0v-WQ" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_QyQtIAc9EeKnAKrJ9eggtA" name="Customer" initiator="true"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNIg7bmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_IgZ8ybbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IgZ8yrbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNIhLbmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_IgZ8y7bmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IgZ8zLbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNIhbbmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_IgZ8zbbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IgZ8zrbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNIhrbmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_IgZ8z7bmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IgZ80LbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNIh7bmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_IgZ80bbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IgZ80rbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_H4AH4Ac9EeKnAKrJ9eggtA" name="Online shop" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Task" xmi:id="_nHcmcAc9EeKnAKrJ9eggtA" name="Order processing" outgoing="_1u3JgAdCEeKnAKrJ9eggtA" incoming="_RT9IIAdBEeKnAKrJ9eggtA" actor="_o7L08Ac9EeKnAKrJ9eggtA">
        <form xmi:type="form:Form" xmi:id="_Cs_xgAmAEeKCufEP31yKhg" name="Order_processing" nLine="6">
          <widgets xmi:type="form:TextFormField" xmi:id="_Cs_xgQmAEeKCufEP31yKhg" name="customerId" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_Cs_xggmAEeKCufEP31yKhg"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_CtAYkAmAEeKCufEP31yKhg" name="customerId" content="customerId" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_CtAYkQmAEeKCufEP31yKhg" name="customerId" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPF7bmEeKtmP3ff0v-WQ"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_CtAYkwmAEeKCufEP31yKhg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgUdULbmEeKtmP3ff0v-WQ" name="customerId" content="customerId" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_IgUdUbbmEeKtmP3ff0v-WQ" name="customerId" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgUdUrbmEeKtmP3ff0v-WQ"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_CtAYlwmAEeKCufEP31yKhg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgUdU7bmEeKtmP3ff0v-WQ" name="field_customerId" content="field_customerId" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_IgVEQLbmEeKtmP3ff0v-WQ" name="customerId" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgVEQbbmEeKtmP3ff0v-WQ"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgVEQrbmEeKtmP3ff0v-WQ" name="customerId" content="customerId" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgVEQ7bmEeKtmP3ff0v-WQ" name="customerId" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgVERLbmEeKtmP3ff0v-WQ"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgVERbbmEeKtmP3ff0v-WQ" name="customerId" content="customerId"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_CtA_oAmAEeKCufEP31yKhg" name="customerId" content="customerId"/>
          </widgets>
          <widgets xmi:type="form:TextFormField" xmi:id="_CtA_oQmAEeKCufEP31yKhg" name="customerInformation" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_CtA_ogmAEeKCufEP31yKhg" line="1"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_CtA_owmAEeKCufEP31yKhg" name="customerInformation" content="customerInformation" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_CtA_pAmAEeKCufEP31yKhg" name="customerInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPGLbmEeKtmP3ff0v-WQ"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_CtA_pgmAEeKCufEP31yKhg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgVER7bmEeKtmP3ff0v-WQ" name="customerInformation" content="customerInformation" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_IgVESLbmEeKtmP3ff0v-WQ" name="customerInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgVESbbmEeKtmP3ff0v-WQ"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_CtA_qgmAEeKCufEP31yKhg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgVESrbmEeKtmP3ff0v-WQ" name="field_customerInformation" content="field_customerInformation" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_IgVES7bmEeKtmP3ff0v-WQ" name="customerInformation" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgVETLbmEeKtmP3ff0v-WQ" line="1"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgVETbbmEeKtmP3ff0v-WQ" name="customerInformation" content="customerInformation" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgVETrbmEeKtmP3ff0v-WQ" name="customerInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgVET7bmEeKtmP3ff0v-WQ"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgVEULbmEeKtmP3ff0v-WQ" name="customerInformation" content="customerInformation"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_CtBmsAmAEeKCufEP31yKhg" name="customerInformation" content="customerInformation"/>
          </widgets>
          <widgets xmi:type="form:TextFormField" xmi:id="_CtBmsQmAEeKCufEP31yKhg" name="orderDate" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_CtBmsgmAEeKCufEP31yKhg" line="2"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_CtBmswmAEeKCufEP31yKhg" name="orderDate" content="orderDate" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_CtBmtAmAEeKCufEP31yKhg" name="orderDate" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgTPGbbmEeKtmP3ff0v-WQ"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_CtBmtgmAEeKCufEP31yKhg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgVEUrbmEeKtmP3ff0v-WQ" name="orderDate" content="orderDate" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_IgVEU7bmEeKtmP3ff0v-WQ" name="orderDate" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgVEVLbmEeKtmP3ff0v-WQ"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_CtBmugmAEeKCufEP31yKhg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgVEVbbmEeKtmP3ff0v-WQ" name="field_orderDate" content="field_orderDate" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_IgVEVrbmEeKtmP3ff0v-WQ" name="orderDate" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgVEV7bmEeKtmP3ff0v-WQ" line="2"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgVEWLbmEeKtmP3ff0v-WQ" name="orderDate" content="orderDate" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgVEWbbmEeKtmP3ff0v-WQ" name="orderDate" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgVEWrbmEeKtmP3ff0v-WQ"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgVEW7bmEeKtmP3ff0v-WQ" name="orderDate" content="orderDate"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_CtCNwQmAEeKCufEP31yKhg" name="orderDate" content="orderDate"/>
          </widgets>
          <widgets xmi:type="form:TextFormField" xmi:id="_CtCNwgmAEeKCufEP31yKhg" name="orderInformation" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_CtCNwwmAEeKCufEP31yKhg" line="3"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_CtCNxAmAEeKCufEP31yKhg" name="orderInformation" content="orderInformation" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_CtCNxQmAEeKCufEP31yKhg" name="orderInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgT2ILbmEeKtmP3ff0v-WQ"/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_CtCNxwmAEeKCufEP31yKhg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgVEXbbmEeKtmP3ff0v-WQ" name="orderInformation" content="orderInformation" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_IgVEXrbmEeKtmP3ff0v-WQ" name="orderInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgVEX7bmEeKtmP3ff0v-WQ"/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_CtCNywmAEeKCufEP31yKhg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgVEYLbmEeKtmP3ff0v-WQ" name="field_orderInformation" content="field_orderInformation" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_IgVEYbbmEeKtmP3ff0v-WQ" name="orderInformation" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgVEYrbmEeKtmP3ff0v-WQ" line="3"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgVEY7bmEeKtmP3ff0v-WQ" name="orderInformation" content="orderInformation" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgVEZLbmEeKtmP3ff0v-WQ" name="orderInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgVEZbbmEeKtmP3ff0v-WQ"/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgVEZrbmEeKtmP3ff0v-WQ" name="orderInformation" content="orderInformation"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_CtC00QmAEeKCufEP31yKhg" name="orderInformation" content="orderInformation"/>
          </widgets>
          <widgets xmi:type="form:TextFormField" xmi:id="_CtC00gmAEeKCufEP31yKhg" name="product" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_CtC00wmAEeKCufEP31yKhg" line="4"/>
            <inputExpression xmi:type="expression:Expression" xmi:id="_CtC01AmAEeKCufEP31yKhg" name="product" content="product" type="TYPE_VARIABLE">
              <referencedElements xmi:type="process:Data" xmi:id="_CtC01QmAEeKCufEP31yKhg" name="product" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                <defaultValue xmi:type="expression:Expression" xmi:id="_IgT2IbbmEeKtmP3ff0v-WQ" content=""/>
              </referencedElements>
            </inputExpression>
            <action xmi:type="expression:Operation" xmi:id="_CtC01wmAEeKCufEP31yKhg">
              <leftOperand xmi:type="expression:Expression" xmi:id="_IgVrUbbmEeKtmP3ff0v-WQ" name="product" content="product" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_IgVrUrbmEeKtmP3ff0v-WQ" name="product" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                  <defaultValue xmi:type="expression:Expression" xmi:id="_IgVrU7bmEeKtmP3ff0v-WQ" content=""/>
                </referencedElements>
              </leftOperand>
              <operator xmi:type="expression:Operator" xmi:id="_CtC02wmAEeKCufEP31yKhg" type="ASSIGNMENT"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_IgVrVLbmEeKtmP3ff0v-WQ" name="field_product" content="field_product" type="TYPE_INPUT">
                <referencedElements xmi:type="form:TextFormField" xmi:id="_IgVrVbbmEeKtmP3ff0v-WQ" name="product" labelPosition="Left">
                  <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgVrVrbmEeKtmP3ff0v-WQ" line="4"/>
                  <inputExpression xmi:type="expression:Expression" xmi:id="_IgVrV7bmEeKtmP3ff0v-WQ" name="product" content="product" type="TYPE_VARIABLE">
                    <referencedElements xmi:type="process:Data" xmi:id="_IgVrWLbmEeKtmP3ff0v-WQ" name="product" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
                      <defaultValue xmi:type="expression:Expression" xmi:id="_IgVrWbbmEeKtmP3ff0v-WQ" content=""/>
                    </referencedElements>
                  </inputExpression>
                  <displayLabel xmi:type="expression:Expression" xmi:id="_IgVrWrbmEeKtmP3ff0v-WQ" name="product" content="product"/>
                </referencedElements>
              </rightOperand>
            </action>
            <displayLabel xmi:type="expression:Expression" xmi:id="_CtDb4QmAEeKCufEP31yKhg" name="product" content="product"/>
          </widgets>
          <widgets xmi:type="form:SubmitFormButton" xmi:id="_CtDb4gmAEeKCufEP31yKhg" name="Submit1" labelPosition="Left">
            <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgWSabbmEeKtmP3ff0v-WQ" line="5"/>
            <displayLabel xmi:type="expression:Expression" xmi:id="_IgWSarbmEeKtmP3ff0v-WQ" name="Submit1" content="Submit1"/>
          </widgets>
          <pageLabel xmi:type="expression:Expression" xmi:id="_CtDb5QmAEeKCufEP31yKhg" name="Order processing" content="Order processing" returnTypeFixed="true"/>
        </form>
        <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_9OSGEAl_EeKCufEP31yKhg" content=""/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_0pO-MAdCEeKnAKrJ9eggtA" name="..." incoming="_1u3JgAdCEeKnAKrJ9eggtA" actor="_o7L08Ac9EeKnAKrJ9eggtA">
        <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_khfmwAmAEeKCufEP31yKhg" content=""/>
      </elements>
      <elements xmi:type="process:IntermediateCatchMessageEvent" xmi:id="_KMbZsLbmEeKtmP3ff0v-WQ" name="receive order" outgoing="_RT9IIAdBEeKnAKrJ9eggtA">
        <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_IgW5drbmEeKtmP3ff0v-WQ" content=""/>
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_IgW5d7bmEeKtmP3ff0v-WQ"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_IgW5eLbmEeKtmP3ff0v-WQ"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_IgW5ebbmEeKtmP3ff0v-WQ" content=""/>
        <correlation xmi:type="expression:TableExpression" xmi:id="_esTVAAmAEeKCufEP31yKhg"/>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_H5yQkAc9EeKnAKrJ9eggtA" path="_H4AH4Ac9EeKnAKrJ9eggtA/application/application"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_H5yQkwc9EeKnAKrJ9eggtA" path="_H4AH4Ac9EeKnAKrJ9eggtA/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_H5yQkQc9EeKnAKrJ9eggtA" path="_H4AH4Ac9EeKnAKrJ9eggtA/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_H5yQlAc9EeKnAKrJ9eggtA" path="_H4AH4Ac9EeKnAKrJ9eggtA/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_H5yQkgc9EeKnAKrJ9eggtA" path="_H4AH4Ac9EeKnAKrJ9eggtA/html/consultation.html"/>
      <data xmi:type="process:Data" xmi:id="_0ZsfoAc9EeKnAKrJ9eggtA" name="customerId" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgT2IrbmEeKtmP3ff0v-WQ"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_7kqRgAc9EeKnAKrJ9eggtA" name="orderDate" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgT2I7bmEeKtmP3ff0v-WQ"/>
      </data>
      <data xmi:type="process:Data" xmi:id="__CLhQAc9EeKnAKrJ9eggtA" name="customerInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgT2JLbmEeKtmP3ff0v-WQ"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_4xzTsAl_EeKCufEP31yKhg" name="product" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgT2JbbmEeKtmP3ff0v-WQ" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_MBFAoAc-EeKnAKrJ9eggtA" name="orderInformation" dataType="_GDs4uAc9EeKnAKrJ9eggtA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IgT2JrbmEeKtmP3ff0v-WQ"/>
      </data>
      <form xmi:type="form:Form" xmi:id="__-eVwAl_EeKCufEP31yKhg" name="Online_shop" nLine="3">
        <widgets xmi:type="form:SubmitFormButton" xmi:id="__-e80Al_EeKCufEP31yKhg" name="Submit1" labelPosition="Left">
          <widgetLayoutInfo xmi:type="form:WidgetLayoutInfo" xmi:id="_IgWSa7bmEeKtmP3ff0v-WQ" line="2"/>
          <displayLabel xmi:type="expression:Expression" xmi:id="_IgWSbLbmEeKtmP3ff0v-WQ" name="Submit1" content="Submit1"/>
        </widgets>
        <pageLabel xmi:type="expression:Expression" xmi:id="__-e80wl_EeKCufEP31yKhg" name="Online shop" content="Online shop" returnTypeFixed="true"/>
      </form>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_H4JR0Ac9EeKnAKrJ9eggtA" content=""/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RT9IIAdBEeKnAKrJ9eggtA" source="_KMbZsLbmEeKtmP3ff0v-WQ" target="_nHcmcAc9EeKnAKrJ9eggtA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RT9IIQdBEeKnAKrJ9eggtA"/>
        <condition xmi:type="expression:Expression" xmi:id="_IgW5c7bmEeKtmP3ff0v-WQ" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1u3JgAdCEeKnAKrJ9eggtA" source="_nHcmcAc9EeKnAKrJ9eggtA" target="_0pO-MAdCEeKnAKrJ9eggtA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1u3JgQdCEeKnAKrJ9eggtA"/>
        <condition xmi:type="expression:Expression" xmi:id="_IgW5dbbmEeKtmP3ff0v-WQ" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_o7L08Ac9EeKnAKrJ9eggtA" name="Employee"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNvkrbmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_IgZ807bmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_IgZ81LbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNvk7bmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_IgZ81bbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Igaj0LbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNvlLbmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_Igaj0bbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Igaj0rbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNvlbbmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_Igaj07bmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Igaj1LbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_IgNvlrbmEeKtmP3ff0v-WQ">
        <name xmi:type="expression:Expression" xmi:id="_Igaj1bbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Igaj1rbmEeKtmP3ff0v-WQ" name="" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_GDs4sgc9EeKnAKrJ9eggtA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_GDs4swc9EeKnAKrJ9eggtA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_GDs4tAc9EeKnAKrJ9eggtA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_GDs4tQc9EeKnAKrJ9eggtA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_GDs4tgc9EeKnAKrJ9eggtA" name="Double"/>
    <datatypes xmi:type="process:FloatType" xmi:id="_GDs4twc9EeKnAKrJ9eggtA" name="Decimal"/>
    <datatypes xmi:type="process:StringType" xmi:id="_GDs4uAc9EeKnAKrJ9eggtA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_GDs4uQc9EeKnAKrJ9eggtA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_GDs4ugc9EeKnAKrJ9eggtA" name="XML"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_GDs4uwc9EeKnAKrJ9eggtA" type="Process" element="_GDs4sQc9EeKnAKrJ9eggtA" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_GWwXkAc9EeKnAKrJ9eggtA" type="2007" element="_GU-O4Ac9EeKnAKrJ9eggtA">
      <children xmi:type="notation:DecorationNode" xmi:id="_GWwXlQc9EeKnAKrJ9eggtA" type="5008" element="_GU-O4Ac9EeKnAKrJ9eggtA"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_GWwXlgc9EeKnAKrJ9eggtA" type="7001" element="_GU-O4Ac9EeKnAKrJ9eggtA">
        <children xmi:type="notation:Shape" xmi:id="_GckrsAc9EeKnAKrJ9eggtA" type="3005" element="_Gca6sAc9EeKnAKrJ9eggtA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_IgYHmrbmEeKtmP3ff0v-WQ" type="5005" element="_Gca6sAc9EeKnAKrJ9eggtA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GckrsQc9EeKnAKrJ9eggtA" x="110" y="55"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Gm_L8Ac9EeKnAKrJ9eggtA" type="3002" element="_Gm1a8Ac9EeKnAKrJ9eggtA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_IgYHnLbmEeKtmP3ff0v-WQ" type="5024" element="_Gm1a8Ac9EeKnAKrJ9eggtA">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Gm_L8wc9EeKnAKrJ9eggtA" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Gm_L8Qc9EeKnAKrJ9eggtA" x="40" y="65"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_aTzU0Qc9EeKnAKrJ9eggtA" type="3005" element="_aTzU0Ac9EeKnAKrJ9eggtA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_IgYuorbmEeKtmP3ff0v-WQ" type="5005" element="_aTzU0Ac9EeKnAKrJ9eggtA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aTzU0gc9EeKnAKrJ9eggtA" x="314" y="57"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_OjzUsQdBEeKnAKrJ9eggtA" type="3011" element="_OjzUsAdBEeKnAKrJ9eggtA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_IgYupLbmEeKtmP3ff0v-WQ" type="5028" element="_OjzUsAdBEeKnAKrJ9eggtA">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_OjzUtAdBEeKnAKrJ9eggtA" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OjzUsgdBEeKnAKrJ9eggtA" x="349" y="168"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_GWwXkQc9EeKnAKrJ9eggtA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_GWwXkgc9EeKnAKrJ9eggtA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_GWwXkwc9EeKnAKrJ9eggtA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_GWwXlwc9EeKnAKrJ9eggtA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GWwXlAc9EeKnAKrJ9eggtA"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_H5yQlQc9EeKnAKrJ9eggtA" type="2007" element="_H4AH4Ac9EeKnAKrJ9eggtA">
      <children xmi:type="notation:DecorationNode" xmi:id="_H5yQmgc9EeKnAKrJ9eggtA" type="5008" element="_H4AH4Ac9EeKnAKrJ9eggtA"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_H5yQmwc9EeKnAKrJ9eggtA" type="7001" element="_H4AH4Ac9EeKnAKrJ9eggtA">
        <children xmi:type="notation:Shape" xmi:id="_nHcmcQc9EeKnAKrJ9eggtA" type="3005" element="_nHcmcAc9EeKnAKrJ9eggtA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_IgYup7bmEeKtmP3ff0v-WQ" type="5005" element="_nHcmcAc9EeKnAKrJ9eggtA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nHcmcgc9EeKnAKrJ9eggtA" x="445" y="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_0pYvMAdCEeKnAKrJ9eggtA" type="3005" element="_0pO-MAdCEeKnAKrJ9eggtA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_IgYurLbmEeKtmP3ff0v-WQ" type="5005" element="_0pO-MAdCEeKnAKrJ9eggtA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0pYvMQdCEeKnAKrJ9eggtA" x="617" y="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_KMlKsLbmEeKtmP3ff0v-WQ" type="3013" element="_KMbZsLbmEeKtmP3ff0v-WQ" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_KMlxwLbmEeKtmP3ff0v-WQ" type="5027">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_KMlxwbbmEeKtmP3ff0v-WQ" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KMlKsbbmEeKtmP3ff0v-WQ" x="337" y="60" width="30" height="30"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_H5yQlgc9EeKnAKrJ9eggtA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_H5yQlwc9EeKnAKrJ9eggtA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_H5yQmAc9EeKnAKrJ9eggtA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_H5yQnAc9EeKnAKrJ9eggtA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_H5yQmQc9EeKnAKrJ9eggtA"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_GDs4vAc9EeKnAKrJ9eggtA"/>
    <edges xmi:type="notation:Connector" xmi:id="_Gn38wwc9EeKnAKrJ9eggtA" type="4001" element="_Gn38wAc9EeKnAKrJ9eggtA" source="_Gm_L8Ac9EeKnAKrJ9eggtA" target="_GckrsAc9EeKnAKrJ9eggtA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IgZVsLbmEeKtmP3ff0v-WQ" type="6001" element="_Gn38wAc9EeKnAKrJ9eggtA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IgZVsbbmEeKtmP3ff0v-WQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IgZVsrbmEeKtmP3ff0v-WQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Gn38xQc9EeKnAKrJ9eggtA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_f44G8wc9EeKnAKrJ9eggtA" type="4001" element="_f44G8Ac9EeKnAKrJ9eggtA" source="_GckrsAc9EeKnAKrJ9eggtA" target="_aTzU0Qc9EeKnAKrJ9eggtA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IgZVtLbmEeKtmP3ff0v-WQ" type="6001" element="_f44G8Ac9EeKnAKrJ9eggtA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IgZVtbbmEeKtmP3ff0v-WQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IgZVtrbmEeKtmP3ff0v-WQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_f44G9Qc9EeKnAKrJ9eggtA" points="[50, 6, -145, -13]$[188, 44, -7, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PZN5wgdBEeKnAKrJ9eggtA" type="4001" element="_PZEIwAdBEeKnAKrJ9eggtA" source="_aTzU0Qc9EeKnAKrJ9eggtA" target="_OjzUsQdBEeKnAKrJ9eggtA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IgZVuLbmEeKtmP3ff0v-WQ" type="6001" element="_PZEIwAdBEeKnAKrJ9eggtA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IgZVubbmEeKtmP3ff0v-WQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IgZVurbmEeKtmP3ff0v-WQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PZN5xAdBEeKnAKrJ9eggtA" points="[-2, 25, -2, -78]$[-2, 86, -2, -17]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RUGSEAdBEeKnAKrJ9eggtA" type="4001" element="_RT9IIAdBEeKnAKrJ9eggtA" source="_KMlKsLbmEeKtmP3ff0v-WQ" target="_nHcmcQc9EeKnAKrJ9eggtA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IgZ8wLbmEeKtmP3ff0v-WQ" type="6001" element="_RT9IIAdBEeKnAKrJ9eggtA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IgZ8wbbmEeKtmP3ff0v-WQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IgZ8wrbmEeKtmP3ff0v-WQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RUGSEgdBEeKnAKrJ9eggtA" points="[15, 6, -128, -2]$[93, 6, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1u3JgwdCEeKnAKrJ9eggtA" type="4001" element="_1u3JgAdCEeKnAKrJ9eggtA" source="_nHcmcQc9EeKnAKrJ9eggtA" target="_0pYvMAdCEeKnAKrJ9eggtA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IgZ8xLbmEeKtmP3ff0v-WQ" type="6001" element="_1u3JgAdCEeKnAKrJ9eggtA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IgZ8xbbmEeKtmP3ff0v-WQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IgZ8xrbmEeKtmP3ff0v-WQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1u3JhQdCEeKnAKrJ9eggtA" points="[19, 0, -133, -4]$[102, 0, -50, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1vKEcAdCEeKnAKrJ9eggtA" id="(0.81,0.42)"/>
    </edges>
  </notation:Diagram>
  <notation:Diagram xmi:id="_7NUT4Al_EeKCufEP31yKhg" type="Form" element="_7M6rQAl_EeKCufEP31yKhg" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_7NUT4Ql_EeKCufEP31yKhg"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="__-pU4Al_EeKCufEP31yKhg" type="Form" element="__-eVwAl_EeKCufEP31yKhg" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="__-pU4Ql_EeKCufEP31yKhg"/>
  </notation:Diagram>
  <notation:Diagram xmi:id="_CtXk8AmAEeKCufEP31yKhg" type="Form" element="_Cs_xgAmAEeKCufEP31yKhg" measurementUnit="Pixel">
    <styles xmi:type="notation:DiagramStyle" xmi:id="_CtXk8QmAEeKCufEP31yKhg"/>
  </notation:Diagram>
</xmi:XMI>
