<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process">
  <process:MainProcess xmi:id="_IZHaQdHHEeKWbdP5jPLa2Q" name="TestCatchMessageSelectionTest" bonitaVersion="6.0.1" bonitaModelVersion="6.0.0-ga-005" configId="ACED000574002E5465737443617463684D65737361676553656C656374696F6E54657374362E302E302D67612D303035362E302E31">
    <elements xsi:type="process:Pool" xmi:id="_Iprl0NHHEeKWbdP5jPLa2Q" name="Pool" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xsi:type="process:Lane" xmi:id="_IufNUNHHEeKWbdP5jPLa2Q" name="Employee lane" actor="_IuJPENHHEeKWbdP5jPLa2Q">
        <elements xsi:type="process:Task" xmi:id="_Ivw_sNHHEeKWbdP5jPLa2Q" name="Step1" outgoing="_VYKDkNHHEeKWbdP5jPLa2Q" incoming="_I2t8QNHHEeKWbdP5jPLa2Q" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:id="_Iv0qE9HHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_Iv0qEdHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_Iv0qENHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_Iv0qEtHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
          <multiInstantiation xmi:id="_Iv2fQNHHEeKWbdP5jPLa2Q">
            <cardinality xmi:id="_bObWkNHLEeK6_4X9cK65_w" returnType="java.lang.Integer" returnTypeFixed="true"/>
          </multiInstantiation>
          <loopCondition xmi:id="_Iv1RINHHEeKWbdP5jPLa2Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:id="_Iv1RIdHHEeKWbdP5jPLa2Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:StartEvent" xmi:id="_I0qGwNHHEeKWbdP5jPLa2Q" name="Start1" outgoing="_I2t8QNHHEeKWbdP5jPLa2Q">
          <viewPageFlowRedirectionURL xmi:id="_bOb9oNHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_bOb9odHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_bOb9otHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_bOb9o9HLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xsi:type="process:EndMessageEvent" xmi:id="_VXbDwNHHEeKWbdP5jPLa2Q" name="Message1" incoming="_VYKDkNHHEeKWbdP5jPLa2Q">
          <viewPageFlowRedirectionURL xmi:id="_bOb9pNHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:id="_bOb9pdHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:id="_bOb9ptHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:id="_bOb9p9HLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:id="_I9ddcNHHEeKWbdP5jPLa2Q" path="_Iprl0NHHEeKWbdP5jPLa2Q/application/application"/>
      <mandatorySymbol xmi:id="_IpupItHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_IpupIdHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_I9ddc9HHEeKWbdP5jPLa2Q" path="_Iprl0NHHEeKWbdP5jPLa2Q/html/error.html"/>
      <processTemplate xmi:id="_I9ddcdHHEeKWbdP5jPLa2Q" path="_Iprl0NHHEeKWbdP5jPLa2Q/html/process.html"/>
      <pageTemplate xmi:id="_I9dddNHHEeKWbdP5jPLa2Q" path="_Iprl0NHHEeKWbdP5jPLa2Q/html/page.html"/>
      <consultationTemplate xmi:id="_I9ddctHHEeKWbdP5jPLa2Q" path="_Iprl0NHHEeKWbdP5jPLa2Q/html/consultation.html"/>
      <entryRedirectionURL xmi:id="_IpupJNHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_IpupI9HHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_IpupJdHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_IpupINHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_I2t8QNHHEeKWbdP5jPLa2Q" source="_I0qGwNHHEeKWbdP5jPLa2Q" target="_Ivw_sNHHEeKWbdP5jPLa2Q">
        <decisionTable xmi:id="_I2vKYNHHEeKWbdP5jPLa2Q"/>
        <condition xmi:id="_bOcksdHLEeK6_4X9cK65_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xsi:type="process:SequenceFlow" xmi:id="_VYKDkNHHEeKWbdP5jPLa2Q" source="_Ivw_sNHHEeKWbdP5jPLa2Q" target="_VXbDwNHHEeKWbdP5jPLa2Q">
        <decisionTable xmi:id="_VYKDkdHHEeKWbdP5jPLa2Q"/>
        <condition xmi:id="_bOcks9HLEeK6_4X9cK65_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:id="_IuJPENHHEeKWbdP5jPLa2Q" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <searchIndexes xmi:id="_IpuCENHHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOckttHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOckt9HLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_IpuCE9HHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOckuNHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOckudHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_IpuCFtHHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOckutHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOcku9HLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_IpuCGdHHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOckvNHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOckvdHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_IpuCHNHHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOckvtHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOckv9HLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xsi:type="process:Pool" xmi:id="_Up2zINHHEeKWbdP5jPLa2Q" name="Pool1" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xsi:type="process:StartMessageEvent" xmi:id="_V0YFgNHHEeKWbdP5jPLa2Q" name="Message2" outgoing="_WYzoQNHHEeKWbdP5jPLa2Q">
        <viewPageFlowRedirectionURL xmi:id="_bOdL1NHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <dynamicLabel xmi:id="_bOdL1dHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:id="_bOdL1tHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:id="_bOdy0NHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xsi:type="process:EndMessageEvent" xmi:id="_WYgtUNHHEeKWbdP5jPLa2Q" name="Message3" incoming="_WYzoQNHHEeKWbdP5jPLa2Q" outgoingMessages="_b-K40NHIEeKWbdP5jPLa2Q">
        <viewPageFlowRedirectionURL xmi:id="_bOb9qNHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <dynamicLabel xmi:id="_bOb9qdHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:id="_bOb9qtHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:id="_bOb9q9HLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <events xmi:id="_aG08sNHIEeKWbdP5jPLa2Q" name="theMessage">
          <correlation xmi:id="_b9-rkdHIEeKWbdP5jPLa2Q">
            <correlationAssociation xmi:id="_b9-rktHIEeKWbdP5jPLa2Q"/>
          </correlation>
          <messageContent xmi:id="_b9-rk9HIEeKWbdP5jPLa2Q"/>
          <targetProcessExpression xmi:id="_bOdy1tHLEeK6_4X9cK65_w" name="Pool2" content="Pool2" returnTypeFixed="true"/>
          <targetElementExpression xmi:id="_bOdy19HLEeK6_4X9cK65_w" name="Message4" content="Message4" returnTypeFixed="true"/>
        </events>
      </elements>
      <resourceFolders xmi:id="_Uqd3INHHEeKWbdP5jPLa2Q" path="_Up2zINHHEeKWbdP5jPLa2Q/application/application"/>
      <mandatorySymbol xmi:id="_Up85wtHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_Up85wdHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_Uqd3I9HHEeKWbdP5jPLa2Q" path="_Up2zINHHEeKWbdP5jPLa2Q/html/error.html"/>
      <processTemplate xmi:id="_Uqd3IdHHEeKWbdP5jPLa2Q" path="_Up2zINHHEeKWbdP5jPLa2Q/html/process.html"/>
      <pageTemplate xmi:id="_Uqd3JNHHEeKWbdP5jPLa2Q" path="_Up2zINHHEeKWbdP5jPLa2Q/html/page.html"/>
      <consultationTemplate xmi:id="_Uqd3ItHHEeKWbdP5jPLa2Q" path="_Up2zINHHEeKWbdP5jPLa2Q/html/consultation.html"/>
      <entryRedirectionURL xmi:id="_Up9g0NHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_Up85w9HHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_Up9g0dHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_Up85wNHHEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <connections xsi:type="process:SequenceFlow" xmi:id="_WYzoQNHHEeKWbdP5jPLa2Q" source="_V0YFgNHHEeKWbdP5jPLa2Q" target="_WYgtUNHHEeKWbdP5jPLa2Q">
        <decisionTable xmi:id="_WYzoQdHHEeKWbdP5jPLa2Q"/>
        <condition xmi:id="_bOcktdHLEeK6_4X9cK65_w" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <searchIndexes xmi:id="_Up7roNHHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdLwNHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdLwdHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_Up7ro9HHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdLwtHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdLw9HLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_Up7rptHHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdLxNHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdLxdHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_Up8SsdHHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdLxtHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdLx9HLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_Up8StNHHEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdLyNHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdLydHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xsi:type="process:Pool" xmi:id="_RqBIcNHIEeKWbdP5jPLa2Q" name="Pool2" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xsi:type="process:StartMessageEvent" xmi:id="_SGfpENHIEeKWbdP5jPLa2Q" name="Message4" event="theMessage" incomingMessag="_b-K40NHIEeKWbdP5jPLa2Q">
        <viewPageFlowRedirectionURL xmi:id="_bOdy0dHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <dynamicLabel xmi:id="_bOdy0tHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:id="_bOdy09HLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:id="_bOdy1NHLEeK6_4X9cK65_w" name="" content="" returnTypeFixed="true"/>
      </elements>
      <resourceFolders xmi:id="_RqpakNHIEeKWbdP5jPLa2Q" path="_RqBIcNHIEeKWbdP5jPLa2Q/application/application"/>
      <mandatorySymbol xmi:id="_RqHPEtHIEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:id="_RqHPEdHIEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:id="_RqqBotHIEeKWbdP5jPLa2Q" path="_RqBIcNHIEeKWbdP5jPLa2Q/html/error.html"/>
      <processTemplate xmi:id="_RqqBoNHIEeKWbdP5jPLa2Q" path="_RqBIcNHIEeKWbdP5jPLa2Q/html/process.html"/>
      <pageTemplate xmi:id="_RqqBo9HIEeKWbdP5jPLa2Q" path="_RqBIcNHIEeKWbdP5jPLa2Q/html/page.html"/>
      <consultationTemplate xmi:id="_RqqBodHIEeKWbdP5jPLa2Q" path="_RqBIcNHIEeKWbdP5jPLa2Q/html/consultation.html"/>
      <entryRedirectionURL xmi:id="_RqH2IdHIEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:id="_RqH2INHIEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <recapPageFlowRedirectionURL xmi:id="_RqH2ItHIEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <viewPageFlowRedirectionURL xmi:id="_RqHPENHIEeKWbdP5jPLa2Q" name="" content="" returnTypeFixed="true"/>
      <searchIndexes xmi:id="_RqGA8NHIEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdLytHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdLy9HLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_RqGoAtHIEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdLzNHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdLzdHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_RqGoBdHIEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdLztHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdLz9HLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_RqGoCNHIEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdL0NHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdL0dHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:id="_RqGoC9HIEeKWbdP5jPLa2Q">
        <name xmi:id="_bOdL0tHLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
        <value xmi:id="_bOdL09HLEeK6_4X9cK65_w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xsi:type="process:BooleanType" xmi:id="_IZIBUNHHEeKWbdP5jPLa2Q" name="Boolean"/>
    <datatypes xsi:type="process:DateType" xmi:id="_IZIBUdHHEeKWbdP5jPLa2Q" name="Date"/>
    <datatypes xsi:type="process:IntegerType" xmi:id="_IZIBUtHHEeKWbdP5jPLa2Q" name="Integer"/>
    <datatypes xsi:type="process:LongType" xmi:id="_IZIBU9HHEeKWbdP5jPLa2Q" name="Long"/>
    <datatypes xsi:type="process:DoubleType" xmi:id="_IZIBVNHHEeKWbdP5jPLa2Q" name="Double"/>
    <datatypes xsi:type="process:StringType" xmi:id="_IZIBVdHHEeKWbdP5jPLa2Q" name="Text"/>
    <datatypes xsi:type="process:JavaType" xmi:id="_IZIoYNHHEeKWbdP5jPLa2Q" name="Java_object"/>
    <datatypes xsi:type="process:XMLType" xmi:id="_IZIoYdHHEeKWbdP5jPLa2Q" name="XML"/>
    <messageConnections xmi:id="_b-K40NHIEeKWbdP5jPLa2Q" name="theMessage" source="_WYgtUNHHEeKWbdP5jPLa2Q" target="_SGfpENHIEeKWbdP5jPLa2Q"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_IZIoYtHHEeKWbdP5jPLa2Q" type="Process" element="_IZHaQdHHEeKWbdP5jPLa2Q" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:id="_IrBCkNHHEeKWbdP5jPLa2Q" type="2007" element="_Iprl0NHHEeKWbdP5jPLa2Q">
      <children xsi:type="notation:DecorationNode" xmi:id="_IrDe0NHHEeKWbdP5jPLa2Q" type="5008" element="_Iprl0NHHEeKWbdP5jPLa2Q"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_IrDe0dHHEeKWbdP5jPLa2Q" type="7001" element="_Iprl0NHHEeKWbdP5jPLa2Q">
        <children xmi:id="_bOfA99HLEeK6_4X9cK65_w" type="3007" element="_IufNUNHHEeKWbdP5jPLa2Q">
          <children xsi:type="notation:DecorationNode" xmi:id="_Iul7ANHHEeKWbdP5jPLa2Q" type="5007" element="_IufNUNHHEeKWbdP5jPLa2Q"/>
          <children xsi:type="notation:DecorationNode" xmi:id="_IumiENHHEeKWbdP5jPLa2Q" type="7002" element="_IufNUNHHEeKWbdP5jPLa2Q">
            <children xsi:type="notation:Shape" xmi:id="_Iv6wsNHHEeKWbdP5jPLa2Q" type="3005" element="_Ivw_sNHHEeKWbdP5jPLa2Q" fontName="Ubuntu" fillColor="14334392" lineColor="10710316">
              <children xsi:type="notation:DecorationNode" xmi:id="_bOfoAdHLEeK6_4X9cK65_w" type="5005" element="_Ivw_sNHHEeKWbdP5jPLa2Q"/>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_Iv6wsdHHEeKWbdP5jPLa2Q" x="110" y="55"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_I0u_QNHHEeKWbdP5jPLa2Q" type="3002" element="_I0qGwNHHEeKWbdP5jPLa2Q" fontName="Ubuntu">
              <children xsi:type="notation:DecorationNode" xmi:id="_bOfoA9HLEeK6_4X9cK65_w" type="5024" element="_I0qGwNHHEeKWbdP5jPLa2Q">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_I0vmUdHHEeKWbdP5jPLa2Q" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_I0u_QdHHEeKWbdP5jPLa2Q" x="40" y="65"/>
            </children>
            <children xsi:type="notation:Shape" xmi:id="_VXdgANHHEeKWbdP5jPLa2Q" type="3011" element="_VXbDwNHHEeKWbdP5jPLa2Q" fontName="Ubuntu">
              <children xsi:type="notation:DecorationNode" xmi:id="_bOfoBtHLEeK6_4X9cK65_w" type="5028" element="_VXbDwNHHEeKWbdP5jPLa2Q">
                <layoutConstraint xsi:type="notation:Location" xmi:id="_VXdgA9HHEeKWbdP5jPLa2Q" y="5"/>
              </children>
              <layoutConstraint xsi:type="notation:Bounds" xmi:id="_VXdgAdHHEeKWbdP5jPLa2Q" x="347" y="75"/>
            </children>
          </children>
          <styles xsi:type="notation:DescriptionStyle" xmi:id="_IulT8dHHEeKWbdP5jPLa2Q"/>
          <styles xsi:type="notation:FontStyle" xmi:id="_IulT8tHHEeKWbdP5jPLa2Q" fontName="Ubuntu"/>
          <styles xsi:type="notation:LineStyle" xmi:id="_IulT89HHEeKWbdP5jPLa2Q"/>
          <styles xsi:type="notation:FillStyle" xmi:id="_IumiEdHHEeKWbdP5jPLa2Q"/>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_IulT9NHHEeKWbdP5jPLa2Q" x="-40" y="-20"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_IrBCkdHHEeKWbdP5jPLa2Q"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_IrBCktHHEeKWbdP5jPLa2Q" fontName="Ubuntu"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_IrBCk9HHEeKWbdP5jPLa2Q"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_IrEF4NHHEeKWbdP5jPLa2Q"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_IrBClNHHEeKWbdP5jPLa2Q"/>
    </children>
    <children xmi:id="_UqgTYNHHEeKWbdP5jPLa2Q" type="2007" element="_Up2zINHHEeKWbdP5jPLa2Q">
      <children xsi:type="notation:DecorationNode" xmi:id="_Uqg6ctHHEeKWbdP5jPLa2Q" type="5008" element="_Up2zINHHEeKWbdP5jPLa2Q"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_Uqg6c9HHEeKWbdP5jPLa2Q" type="7001" element="_Up2zINHHEeKWbdP5jPLa2Q">
        <children xsi:type="notation:Shape" xmi:id="_V0faQNHHEeKWbdP5jPLa2Q" type="3012" element="_V0YFgNHHEeKWbdP5jPLa2Q" fontName="Ubuntu">
          <children xsi:type="notation:DecorationNode" xmi:id="_bOfoCdHLEeK6_4X9cK65_w" type="5029" element="_V0YFgNHHEeKWbdP5jPLa2Q">
            <layoutConstraint xsi:type="notation:Location" xmi:id="_V0goYdHHEeKWbdP5jPLa2Q" y="5"/>
          </children>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_V0gBUNHHEeKWbdP5jPLa2Q" x="62" y="118"/>
        </children>
        <children xsi:type="notation:Shape" xmi:id="_WYll0NHHEeKWbdP5jPLa2Q" type="3011" element="_WYgtUNHHEeKWbdP5jPLa2Q" fontName="Ubuntu">
          <children xsi:type="notation:DecorationNode" xmi:id="_bOfoDNHLEeK6_4X9cK65_w" type="5028" element="_WYgtUNHHEeKWbdP5jPLa2Q">
            <layoutConstraint xsi:type="notation:Location" xmi:id="_WYmz8dHHEeKWbdP5jPLa2Q" y="5"/>
          </children>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_WYll0dHHEeKWbdP5jPLa2Q" x="350" y="137"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_UqgTYdHHEeKWbdP5jPLa2Q"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_UqgTYtHHEeKWbdP5jPLa2Q" fontName="Ubuntu"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_Uqg6cNHHEeKWbdP5jPLa2Q"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_Uqg6dNHHEeKWbdP5jPLa2Q"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_Uqg6cdHHEeKWbdP5jPLa2Q"/>
    </children>
    <children xmi:id="_Rqsd4NHIEeKWbdP5jPLa2Q" type="2007" element="_RqBIcNHIEeKWbdP5jPLa2Q">
      <children xsi:type="notation:DecorationNode" xmi:id="_RqtE8tHIEeKWbdP5jPLa2Q" type="5008" element="_RqBIcNHIEeKWbdP5jPLa2Q"/>
      <children xsi:type="notation:DecorationNode" xmi:id="_RqtE89HIEeKWbdP5jPLa2Q" type="7001" element="_RqBIcNHIEeKWbdP5jPLa2Q">
        <children xsi:type="notation:Shape" xmi:id="_SGkhkNHIEeKWbdP5jPLa2Q" type="3012" element="_SGfpENHIEeKWbdP5jPLa2Q" fontName="Ubuntu">
          <children xsi:type="notation:DecorationNode" xmi:id="_bOgPEtHLEeK6_4X9cK65_w" type="5029" element="_SGfpENHIEeKWbdP5jPLa2Q">
            <layoutConstraint xsi:type="notation:Location" xmi:id="_SGlvsdHIEeKWbdP5jPLa2Q" y="5"/>
          </children>
          <layoutConstraint xsi:type="notation:Bounds" xmi:id="_SGkhkdHIEeKWbdP5jPLa2Q" x="91" y="114"/>
        </children>
      </children>
      <styles xsi:type="notation:DescriptionStyle" xmi:id="_Rqsd4dHIEeKWbdP5jPLa2Q"/>
      <styles xsi:type="notation:FontStyle" xmi:id="_Rqsd4tHIEeKWbdP5jPLa2Q" fontName="Ubuntu"/>
      <styles xsi:type="notation:LineStyle" xmi:id="_RqtE8NHIEeKWbdP5jPLa2Q"/>
      <styles xsi:type="notation:FillStyle" xmi:id="_RqtE9NHIEeKWbdP5jPLa2Q"/>
      <layoutConstraint xsi:type="notation:Bounds" xmi:id="_RqtE8dHIEeKWbdP5jPLa2Q"/>
    </children>
    <styles xsi:type="notation:DiagramStyle" xmi:id="_IZIoY9HHEeKWbdP5jPLa2Q"/>
    <edges xsi:type="notation:Connector" xmi:id="_I20p8NHHEeKWbdP5jPLa2Q" type="4001" element="_I2t8QNHHEeKWbdP5jPLa2Q" source="_I0u_QNHHEeKWbdP5jPLa2Q" target="_Iv6wsNHHEeKWbdP5jPLa2Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_bOgPFdHLEeK6_4X9cK65_w" type="6001" element="_I2t8QNHHEeKWbdP5jPLa2Q">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_bOgPFtHLEeK6_4X9cK65_w" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_bOgPF9HLEeK6_4X9cK65_w" fontName="Ubuntu"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_I20p8tHHEeKWbdP5jPLa2Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_VYLRsNHHEeKWbdP5jPLa2Q" type="4001" element="_VYKDkNHHEeKWbdP5jPLa2Q" source="_Iv6wsNHHEeKWbdP5jPLa2Q" target="_VXdgANHHEeKWbdP5jPLa2Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_bOg2IdHLEeK6_4X9cK65_w" type="6001" element="_VYKDkNHHEeKWbdP5jPLa2Q">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_bOg2ItHLEeK6_4X9cK65_w" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_bOg2I9HLEeK6_4X9cK65_w" fontName="Ubuntu"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_VYLRstHHEeKWbdP5jPLa2Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_WY02YNHHEeKWbdP5jPLa2Q" type="4001" element="_WYzoQNHHEeKWbdP5jPLa2Q" source="_V0faQNHHEeKWbdP5jPLa2Q" target="_WYll0NHHEeKWbdP5jPLa2Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_bOg2JdHLEeK6_4X9cK65_w" type="6001" element="_WYzoQNHHEeKWbdP5jPLa2Q">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_bOg2JtHLEeK6_4X9cK65_w" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_bOg2J9HLEeK6_4X9cK65_w" fontName="Ubuntu"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_WY02YtHHEeKWbdP5jPLa2Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xsi:type="notation:Connector" xmi:id="_b-N8INHIEeKWbdP5jPLa2Q" type="4002" element="_b-K40NHIEeKWbdP5jPLa2Q" source="_WYll0NHHEeKWbdP5jPLa2Q" target="_SGkhkNHIEeKWbdP5jPLa2Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xsi:type="notation:DecorationNode" xmi:id="_bOg2KdHLEeK6_4X9cK65_w" type="6003" element="_b-K40NHIEeKWbdP5jPLa2Q">
        <layoutConstraint xsi:type="notation:Location" xmi:id="_bOg2KtHLEeK6_4X9cK65_w" y="-10"/>
      </children>
      <styles xsi:type="notation:FontStyle" xmi:id="_bOg2K9HLEeK6_4X9cK65_w" fontName="Ubuntu"/>
      <bendpoints xsi:type="notation:RelativeBendpoints" xmi:id="_b-N8ItHIEeKWbdP5jPLa2Q" points="[0, 14, 259, -233]$[0, 175, 259, -72]$[-262, 175, -3, -72]$[-262, 232, -3, -15]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
