/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.w3._1999.xhtml.validation;

import java.math.BigInteger;
import java.util.List;

import org.w3._1999.xhtml.CheckedType;
import org.w3._1999.xhtml.DirType;
import org.w3._1999.xhtml.DisabledType5;
import org.w3._1999.xhtml.InputType;
import org.w3._1999.xhtml.ReadonlyType1;

/**
 * A sample validator interface for {@link org.w3._1999.xhtml.InputType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputType1Validator {
	boolean validate();

	boolean validateAccept(String value);
	boolean validateAccesskey(String value);
	boolean validateAlt(Object value);
	boolean validateChecked(CheckedType value);
	boolean validateClass(String value);

	boolean validateClass(List<String> value);
	boolean validateDir(DirType value);
	boolean validateDisabled(DisabledType5 value);
	boolean validateId(String value);
	boolean validateLang(String value);
	boolean validateLang1(String value);
	boolean validateMaxlength(BigInteger value);
	boolean validateName(Object value);
	boolean validateOnblur(String value);
	boolean validateOnchange(String value);
	boolean validateOnclick(String value);
	boolean validateOndblclick(String value);
	boolean validateOnfocus(String value);
	boolean validateOnkeydown(String value);
	boolean validateOnkeypress(String value);
	boolean validateOnkeyup(String value);
	boolean validateOnmousedown(String value);
	boolean validateOnmousemove(String value);
	boolean validateOnmouseout(String value);
	boolean validateOnmouseover(String value);
	boolean validateOnmouseup(String value);
	boolean validateOnselect(String value);
	boolean validateReadonly(ReadonlyType1 value);
	boolean validateSize(Object value);
	boolean validateSrc(String value);
	boolean validateStyle(String value);
	boolean validateTabindex(BigInteger value);
	boolean validateTitle(String value);
	boolean validateType(InputType value);
	boolean validateUsemap(String value);
	boolean validateValue(Object value);
}
