/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.w3._1999.xhtml.validation;

import java.math.BigInteger;
import java.util.List;

import org.eclipse.emf.common.util.EList;
import org.w3._1999.xhtml.CaptionType;
import org.w3._1999.xhtml.ColType;
import org.w3._1999.xhtml.ColgroupType;
import org.w3._1999.xhtml.DirType;
import org.w3._1999.xhtml.TFrame;
import org.w3._1999.xhtml.TRules;
import org.w3._1999.xhtml.TbodyType;
import org.w3._1999.xhtml.TfootType;
import org.w3._1999.xhtml.TheadType;
import org.w3._1999.xhtml.TrType;

/**
 * A sample validator interface for {@link org.w3._1999.xhtml.TableType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableTypeValidator {
	boolean validate();

	boolean validateCaption(CaptionType value);
	boolean validateCol(EList<ColType> value);
	boolean validateColgroup(EList<ColgroupType> value);
	boolean validateThead(TheadType value);
	boolean validateTfoot(TfootType value);
	boolean validateTbody(EList<TbodyType> value);
	boolean validateTr(EList<TrType> value);
	boolean validateBorder(BigInteger value);
	boolean validateCellpadding(String value);
	boolean validateCellspacing(String value);
	boolean validateClass(String value);

	boolean validateClass(List<String> value);
	boolean validateDir(DirType value);
	boolean validateFrame(TFrame value);
	boolean validateId(String value);
	boolean validateLang(String value);
	boolean validateLang1(String value);
	boolean validateOnclick(String value);
	boolean validateOndblclick(String value);
	boolean validateOnkeydown(String value);
	boolean validateOnkeypress(String value);
	boolean validateOnkeyup(String value);
	boolean validateOnmousedown(String value);
	boolean validateOnmousemove(String value);
	boolean validateOnmouseout(String value);
	boolean validateOnmouseover(String value);
	boolean validateOnmouseup(String value);
	boolean validateRules(TRules value);
	boolean validateStyle(String value);
	boolean validateSummary(String value);
	boolean validateTitle(String value);
	boolean validateWidth(String value);
}
